### PR TITLE
test: limit temp dhcp6 changes to < NOBLE

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
test: limit temp dhcp6 changes to < NOBLE

#4474 landed in Noble, so this block isn't needed.
```

## Additional Context
https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-noble-gce/49/testReport/junit/tests.integration_tests/test_upgrade/test_clean_boot_of_upgraded_package/

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by a-dubs** [comment]
Nice catch! Looks good. My eyes don't work too well tho...

**Comment by blackboxsw** [comment]
@TheRealFalcon @holmanb don't we need to patch out this dhcp6 in network config from generate_fallback_config to avoid change in behavior on stable releases?

**Comment by TheRealFalcon** [comment]
Is there reason to think this would break anything? I didn't think we needed to patch this one.

**Comment by blackboxsw** [comment]
> Is there reason to think this would break anything? I didn't think we needed to patch this one.

As long as our rendered network config definition is not blocking/waiting indefinitely on marking the network interface "up" on having a viable dhcp6 route/response from the DHCP server, then it shouldn't impact anything such as boot time while we await for network-online.target.

**Comment by TheRealFalcon** [comment]
>  not blocking/waiting indefinitely on marking the network interface "up"

Yeah, that's a valid concern. I initially reverted this one because it would cause exactly that on NetworkManager, but we were able to get that fixed in a follow-up to https://github.com/canonical/cloud-init/pull/4474

**Comment by blackboxsw** [comment]
Thanks for this. I found the supplemental commit that fixed this issue for NetworkManager rendered config 29dd5ace73ad60c7452c39b840045fb47fe0711f.  And also confirmed that on systemd-networkd environments rendered from netplan config, we don't see issues with timing in environments with no dhcp6 provided from the dhcp service with /run/systemd/network/*.network   config setting `[Network]\nDHCP=yes` which is generated due to dhcp6 and dhcp4 vs just `DHCP=ipv4` which is rendered when we only specific `dhcp4: true` config in netplan.

I approve this work and it looks like our common net config rendered cases won't introduce blocking in environments where the DHCP service is not providing IPV6 config attributes.

**Review by blackboxsw — APPROVED** [review]

**Pull request merged**
