### PR TITLE
Holmanb/completion schema fix

### PR DESCRIPTION
**Pull request by holmanb**
```
completion: update schema command

LP: #1979547
```

## Additional Context
I borked this in [commit 3bcffacb2](https://github.com/canonical/cloud-init/pull/1402). Oops.

## Test Steps
```bash
. bash_completion/cloud-init  # source locally
cloud-init       (Press TAB)
cloud-init sch   (Press TAB)
cloud-init devel (Press twice TAB)
```

## Test Output
```bash
arc~/cloud-init-e(cloud-init-e|✚1…) bash 
holmanb@arc:~/cloud-init-e$ . bash_completion/cloud-init 
holmanb@arc:~/cloud-init-e$ cloud-init 
analyze        collect-logs   devel          features       --force        init           query          single         --version      
clean          --debug        dhclient-hook  --file         --help         modules        schema         status               
holmanb@arc:~/cloud-init-e$ cloud-init schema --
--annotate     --config-file  --docs         --help         --system       
holmanb@arc:~/cloud-init-e$ cloud-init devel 
--help        hotplug-hook  net-convert   
```

### CODE REVIEW

**Review by aciba90 — APPROVED** [review]
+1. Thanks for the fix.

**Review by TheRealFalcon — APPROVED** [review]
Verified that on an instance with the broken completion, this PR adds completion for `cloud-init schema` along with its arguments, and removes the schema completion for `cloud-init devel`

**Comment by TheRealFalcon** [comment]
@holmanb rebase needed with the setuptools fix.

**Comment by holmanb** [comment]
> @holmanb rebase needed with the setuptools fix.

Thanks, done. Interesting, the Github UI doesn't mention the force push I just did:

```
git fetch upstream && git reset --hard upstream/main && git cherry-pick cb1538cd83522357f288bc94134e82171001a184 && git push --force
```

**Pull request merged**
