### PR TITLE
Add miraclelinux support

### PR DESCRIPTION
**Pull request by tSU-RooT**
## Proposed Commit Message
Add miraclelinux support

## Additional Context
https://www.cybertrust.co.jp/miracle-linux/
Install ISO is available from here: https://repo.dist.miraclelinux.net/miraclelinux/isos/8.4-released/x86_64/

## Test Steps
tox
```
_____________________________________________________________ summary _____________________________________________________________
  py3: commands succeeded
  xenial-dev: commands succeeded
  flake8: commands succeeded
  pylint: commands succeeded
  congratulations :)

```
## Checklist:
 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by holmanb — APPROVED** [review]
Thanks for the PR @tSU-RooT. This looks good to me.

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
Thanks @tSU-RooT . This PR looks good.

Before we can merge, you'll need to perform a rebase. There's a merge conflict due to `cloudinit/tests/test_util.py` being moved to `tests/unittests/test_util.py` , so your changes will have to be moved there as well.

**Comment by tSU-RooT** [comment]
Thanks for reviews, I will rebase my changes.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
