### PR TITLE
Ubuntu/focal

### PR DESCRIPTION
**Pull request by TheRealFalcon**
DO NOT SQUASH

Main thing to review here is the two status quilt patches as they need manual updating.

Process:
```
new_upstream_snapshot.py -c main
# script fails
# manually refresh quilt patches
git commit -am "refresh patches against upstream/main
    
patches:
debian/patches/status-do-not-remove-duplicated-data.patch
debian/patches/status-retain-recoverable-error-exit-code.patch
debian/patches/revert-551f560d-cloud-config-after-snap-seeding.patch"
new_upstream_snapshot.py -c main --post quilt
# manually update changelog with refreshed quilt patches
```

### CODE REVIEW

**Review by blackboxsw — COMMENTED** [review]
I'm seeing a functional diff in d/patches/status-do-not-remove-duplicated-data.patch
```diff
-@@ -598,6 +636,30 @@ PATH=/usr/local/sbin:/usr/local/bin:/usr
+@@ -598,6 +636,32 @@ PATH=/usr/local/sbin:/usr/local/bin:/usr
                      },
                      "last_update": "Thu, 01 Jan 1970 00:02:05 +0000",
                      "recoverable_errors": {},
@@ -96,7 +95,7 @@ This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
 +                            "detail": "DataSourceNoCloud "
 +                            "[seed=/var/.../seed/nocloud-net][dsmode=net]",
 +                            "errors": ["error1", "error2", "error3"],
-+                            "extended_status": "error - running",
++                            "extended_status": "error",
 +                            "init": {
 +                                "errors": ["error1"],
 +                                "finished": 125.678,
@@ -113,10 +112,12 @@ This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
 +                            "status": "error",
 +                        }
 +                    },
++                    "last_update": "Thu, 01 Jan 1970 00:02:05 +0000",
++                    "recoverable_errors": {},
                      "stage": None,
:
```

Your branch is exposing the extended_status: "error - running". I need to determine why my branch isn't pulling in that changeset on the quilt refresh.

**Comment by TheRealFalcon** [comment]
Sorry, I should have mentioned that I manually added that. Tests won't pass without it.

**Comment by blackboxsw** [comment]
> Sorry, I should have mentioned that I manually added that. Tests won't pass without it.

All good, caught that now. and had manually added it as well to pass unittests on the duplicated schema "1" stuff we were trying to retain on stable releases +1

**Review by blackboxsw — APPROVED** [review]
Changeset and manual quilt patch refresh looks good given the additional adds to the extended_status duplication in JSON status output.

**Pull request merged**
