### PR TITLE
24.1.4 release 

### PR DESCRIPTION
**Pull request by blackboxsw**
Cherry-pick remaining high-impact fixes for 24.1.3 as an upstream 24.1.4 release

- support of dhcpcd bringing down the interface before attempting interface renaming in cloud-init
- dhcpcd empty lease handling when lease response is not able to be parsed
- better empty dhcpcd lease handling and error reporting
- BSD runtime support for distro-specific run_dir changes

## Additional Context
Procedure to make this branch:
```
git fetch upstream
git checkout upstream/24.1.x -B 24.1.x  
git cherry-pick accdfe6a8b2ffff82731c8bae2d672ff7c3f0974 # import log module directly to avoid mock test failures
git cherry-pick 144782a838123099334fe44c07566b07503fd67b # test updates to avoid side-effects
git cherry-pick f74b61eae24706dd313efc06792198a718f06672 # ephemeral dhcp rename
git cherry-pick 8f806e20bda1bdf0e00ff180183990470e241837 # warn when interface rename fails
git cherry-pick 372e80f8e6e01441e69d277782e2367678994abb  #  dchpcd timeout 300
git cherry-pick a6e09d9bfd3ef0770bc4d9452d978ba93dbe1245 # run_dir support BSD
git cherry-pick 77771023ab5bda43a25cdc3dd4eb69a79169b3cb # dhcpcd empty/bad lease
git cherry-pick f6ac6ee8a4321ba959ae8f3ae9f1b9ac3b9fafd0 # dhcpcd robust handling

# create hotfix changelog
echo 24.1.4 > ChangeLog.new
git log 24.1.3..HEAD | log2dch | sed 's/    / /' >> ChangeLog.new
echo >> ChangeLog.new
cat ChangeLog >> ChangeLog.new
mv Changelog.new ChangeLog
sed -i 's/24.1.3/24.1.4/' cloudinit/version.py 
git commit -a
```
## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [x] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by holmanb — CHANGES_REQUESTED** [review]
I think we want https://github.com/canonical/cloud-init/pull/5115 as well

**Comment by blackboxsw** [comment]
> I think we want #5115 as well

Good catch, I got it in the description, but not my creation procedure . I added both commits from https://github.com/canonical/cloud-init/pull/5115/commits

**Review by holmanb — APPROVED** [review]
Thanks @blackboxsw, this looks good to me now!

**Comment by blackboxsw** [comment]
@holmanb thanks for the review. the unittests were failing because a known mocking issue fixed in accdfe6a8b2ffff82731c8bae2d672ff7c3f0974. I was able to reproduce pkg build failures in sbuild on noble without this commit. I've added that commit to our series and we should be good now

**Review by holmanb — APPROVED** [review]

**Pull request merged**
