### PR TITLE
net: refactor find_candidate_nics_on_linux() to use get_interfaces()

### PR DESCRIPTION
**Pull request by cjp256**
Much of the filtering logic used in get_interfaces() is duplicated in find_candidate_nics_on_linux().  Consolidate the two interfaces by updating find_candidate_nics_on_linux() to use get_interfaces() and provide boolean toggles to maintain existing behavior.

The following parameters have been added to get_interfaces():
- log_filtered_reasons: bool = False
- filter_openvswitch_internal: bool = True
- filter_vlan: bool = True
- filter_without_own_mac: bool = True
- filter_zero_mac: bool = True

It may be that these deltas are unwanted or harmless, but the toggles could be removed independently with more deliberate consideration. Similarly, logging could be extended if desired for log_filtered_reasons.

### CODE REVIEW

**Review by anhvoms — APPROVED** [review]
LGTM!

**Review by TheRealFalcon — APPROVED** [review]
I think the new arguments feel a bit awkward, but it's certainly an improvement, so LGTM.

**Comment by TheRealFalcon** [comment]
@cjp256 , so do you want me to merge this one, then you'll rebase #2153 and we merge that one? Or something else?

**Comment by cjp256** [comment]
> @cjp256 , so do you want me to merge this one, then you'll rebase #2153 and we merge that one? Or something else?

#2153 first, then i'll rebase this.

**Comment by cjp256** [comment]
> @cjp256 , so do you want me to merge this one, then you'll rebase #2153 and we merge that one? Or something else?

Yeah, merge this first then I'll update 2153.

**Comment by cjp256** [comment]
> I think the new arguments feel a bit awkward, but it's certainly an improvement, so LGTM.

Curious what you would prefer.  I

> I think the new arguments feel a bit awkward, but it's certainly an improvement, so LGTM.

Any thoughts on how to improve it? I can update this or come back to it later

**Comment by TheRealFalcon** [comment]
> Any thoughts on how to improve it? I can update this or come back to it later

I think it's fine as-is. I think it's mainly because we're combining two functions without breaking any behavior, so that gets exposed as some extra options. I'm not sure there's a better way to do it without breaking behavior.

**Pull request merged**
