### PR TITLE
Ensure network ready before cloud-init service runs on RHEL

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
Ensure network ready before cloud-init service runs on RHEL

LP: #1998655
```

## Additional Context
See https://bugs.launchpad.net/cloud-init/+bug/1998655

### CODE REVIEW

**Comment by xiaoge1001** [comment]
This modification will take effect on all "almalinux", "centos", "cloudlinux", "eurolinux", "fedora","miraclelinux", "openEuler", "openmandriva", "rhel", "rocky","virtuozzo" systems, not only "rhel". Does it affect other distro?

**Comment by TheRealFalcon** [comment]
`Does it affect other distro?`

That's hard to answer tbh. Many other distros use other networking utilities. Since we haven't seen issues from non-rhel distros, I would prefer to keep this change limited to the rhel-derived distros.

**Comment by esposem** [comment]
Thank you for pinging us!
Just to be safe, I asked our QE team to test if this causes regression. I'll keep you posted, thanks

**Comment by esposem** [comment]
@TheRealFalcon green from our side, thanks!

**Review by holmanb — APPROVED** [review]
LGTM!

**Comment by thatsk** [comment]
does it pushed to new version because I am seeing this issues in almalinux 8.7

**Comment by igalic** [comment]
the new release: https://github.com/canonical/cloud-init/pull/2028
is happening right now

**Pull request merged**
