### PR TITLE
Add verify_commit and inventory to ansible.pull schema

### PR DESCRIPTION
**Pull request by fionn**
We pass the parameters straight through to `ansible-pull`, which supports this flag since https://github.com/ansible/ansible/pull/11219.

### CODE REVIEW

**Review by holmanb — APPROVED** [review]
We typically require [a CLA signature](https://ubuntu.com/legal/contributors) for new contributors, but this is trivial and correct so no need for this contribution!

**Comment by fionn** [comment]
Thanks! I should have added `inventory` as well, should I make another PR or just tack it on here?

**Comment by holmanb** [comment]
> Thanks! I should have added `inventory` as well, should I make another PR or just tack it on here?

Feel free to tack it on

**Comment by holmanb** [comment]
> We typically require [a CLA signature](https://ubuntu.com/legal/contributors) for new contributors, but this is trivial and correct so no need for this contribution!

Bleh, I was mistaken sorry @fionn - that only applies to trivial docs changes.

Could you please sign and add yourself to the cla signers list?

**Comment by fionn** [comment]
I tried to sign the CLA but the server returned a 503 when redirected to https://ubuntu.com/legal/contributors/thank-you.

**Comment by holmanb** [comment]
@fionn Thanks! I can see the signature, we're all good on our end. Can you please add your username to the [signer's list](https://github.com/canonical/cloud-init/blob/main/tools/.github-cla-signers) in this PR?

**Pull request merged**
