### PR TITLE
CloudStack: fix data-server DNS resolution

### PR DESCRIPTION
**Pull request by olivierlemasle**
## Proposed Commit Message

```
CloudStack: fix data-server DNS resolution

CloudStack DNS resolution should be done against 
the DNS search domain (with the final dot, DNS
resolution does not work with e.g. Fedora 34)

LP: #1942232
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Hey @olivierlemasle , thanks for this PR.  I have some questions over at https://bugs.launchpad.net/cloud-init/+bug/1942232 . I'll leave this PR open while we have a conversation over there.

**Comment by olivierlemasle** [comment]
Hi @onitake @joschi36,
As you recently updated CloudStack and cloud-init documentation regarding the CloudStack meta-data service (@onitake) and you added the `data-server.` DNS request to cloud-init (@joschi36), could you please look at my bug report in https://bugs.launchpad.net/cloud-init/+bug/1942232 ?

With Fedora 34, something changed compared to Fedora 33, and the `data-server.` request fails (`data-server` or the complete FQDN are still ok). Can you reproduce the issue? Why did you use `data-server.` and not `data-server`?

**Comment by onitake** [comment]
This is a bit odd. I remember that we specifically had to add a dot, so data-server would _not_ be searched in the network/VPC domain. Maybe this has changed on the CloudStack side?

**Comment by TheRealFalcon** [comment]
It's hard to know the "right" solution without more context, but is there any harm in trying the FQDN first, and then try the relative address if that fails?

**Comment by TheRealFalcon** [comment]
Given the discussion on https://bugs.launchpad.net/cloud-init/+bug/1942232 , it seems it was never intended for `data-server` to be a FQDN, so I'm ok merging this change. Thanks everybody!

**Review by TheRealFalcon — APPROVED** [review]

**Comment by onitake** [comment]
> Given the discussion on https://bugs.launchpad.net/cloud-init/+bug/1942232 , it seems it was never intended for `data-server` to be a FQDN, so I'm ok merging this change. Thanks everybody!

I don't fully agree. Yes, the justification given by @smoser for adding the dot didn't seem conclusive, but I'd prefer a clarification first.

**Comment by onitake** [comment]
On another note: If the trailing dot in cloud-init is removed, the CloudStack documentation needs to be updated as well.

For reference: https://github.com/apache/cloudstack-documentation/pull/132

**Comment by TheRealFalcon** [comment]
I see. I mistook your comments in launchpad as justification for removing the dot. We can wait to see if @smoser has any further information.

**Comment by onitake** [comment]
@weizhouapache What do you think? You commented on the Launchpad issue that the dot should be removed.

IMHO, there is a risk that the wrong DNS server could be asked about the host configuration. Imagine for example someone writing Google's DNS servers and a custom domain into their VM's /etc/resolv.conf. This would cause the DNS request to never reach the virtual router, and consequently cloud-init not getting the correct data-server address. If someone impersonates the data-server and introduces a suitable record into public DNS, you'd have a serious security issue. Obviously, resolving `data-server.` wouldn't work either in this case, but at least there would be no risk.

Perhaps this should be solved on the virtual router instead? If it always returns a correct result for `data-server.` (with the dot), then this wouldn't be an issue at all.

**Comment by olivierlemasle** [comment]
FYI, I did some additional tests in another environment (original tests in the [Launchpad ticket](https://bugs.launchpad.net/cloud-init/+bug/1942232)):

- CloudStack version: 4.15
- VM instance: Ubuntu 20.04
- **both VPC** and **non-VPC** networks

Again, `data-server.` was not resolved:

```
ubuntu@test:~$ host data-server.
Host data-server not found: 2(SERVFAIL)

ubuntu@test:~$ host data-server
data-server.cs2cloud.internal has address 10.0.100.1

ubuntu@test:~$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
>>> from socket import getaddrinfo
>>> getaddrinfo("data-server.", 80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

>>> getaddrinfo("data-server", 80)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.0.100.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('10.0.100.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('10.0.100.1', 80))]
```

**Comment by weizhouapache** [comment]
same results in ubuntu 18.04

(but it works in centos 5.5 created from default template in cloudstack)

@onitake 
I tried to add "data-server." in /etc/hosts and reload dnsmasq, but still cannot resolve 'data-server.' in ubuntu 18.04 vm.


> FYI, I did some additional tests in another environment (original tests in the [Launchpad ticket](https://bugs.launchpad.net/cloud-init/+bug/1942232)):
> 
> * CloudStack version: 4.15
> * VM instance: Ubuntu 20.04
> * **both VPC** and **non-VPC** networks
> 
> Again, `data-server.` was not resolved:
> 
> ```
> ubuntu@test:~$ host data-server.
> Host data-server not found: 2(SERVFAIL)
> 
> ubuntu@test:~$ host data-server
> data-server.cs2cloud.internal has address 10.0.100.1
> 
> ubuntu@test:~$ python3
> Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
> >>> from socket import getaddrinfo
> >>> getaddrinfo("data-server.", 80)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> >>> getaddrinfo("data-server", 80)
> [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.0.100.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('10.0.100.1', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('10.0.100.1', 80))]
> ```

**Comment by TheRealFalcon** [comment]
Is there any reason we shouldn't do my previous suggestion?
> trying the FQDN first, and then try the relative address if that fails?

**Review by weizhouapache — APPROVED** [review]
code lgtm

**Comment by weizhouapache** [comment]
@TheRealFalcon @onitake @olivierlemasle 

I just had an idea in cloudstack. I will test it and update you next week.

**Comment by weizhouapache** [comment]
@TheRealFalcon @onitake @olivierlemasle

small update: 
it seems to be caused by systemd-resolved.
If I add "nameserver 10.x.x.x" in /etc/resolv.conf, or create /etc/resolv.conf as symbolic link of /run/systemd/resolve/resolv.conf, the domain "data-server." can be resolved.

I am not going to fix it in cloudstack, as it is a cloudstack issue in my opinion.

**Comment by TheRealFalcon** [comment]
I'm going to go ahead and merge this. We got feedback and evidence from multiple people that the current solution doesn't work but that this proposed solution does work. Additionally, I have asked for feedback multiple times about any possible reservations and/or workarounds and have not heard anything.

**Comment by weizhouapache** [comment]
> I'm going to go ahead and merge this. We got feedback and evidence from multiple people that the current solution doesn't work but that this proposed solution does work. Additionally, I have asked for feedback multiple times about any possible reservations and/or workarounds and have not heard anything.

@TheRealFalcon 
thanks for merging !

**Comment by synergiator** [comment]
side question - what is to expect with regards of the backward compatibility here, if this has been tested only with 4.15?

**Comment by weizhouapache** [comment]
Hi @synergiator 
from my understanding,
if `addrinfo = getaddrinfo("data-server.", 80)` works, `addrinfo = getaddrinfo("data-server", 80)` works as well.
if `addrinfo = getaddrinfo("data-server.", 80)` does not work in some guest os, `addrinfo = getaddrinfo("data-server", 80)` still works.
I did not see any backward compatibility issue.
Please correct me if I am wrong.

**Comment by synergiator** [comment]
thx - indeed the implementation seems to be independent of the ACS version.
 p.s. I see now some discussion on the Apache CloudStack user mailing list where indeed OS compatibility might be a topic, but my queston was about the ACS bc.

**Pull request closed without merging**
