### PR TITLE
Use `partprobe` to re-read partition table

### PR DESCRIPTION
**Pull request by nicolasbock**
The `blkdev` command is fragile re-reading partition tables if a
partition is mounted. This change replaces it with the `partprobe`
command.

Closes-Bug: https://bugs.launchpad.net/cloud-init/+bug/1920939
Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
I just sigend the CLA.

**Comment by giggsoff** [comment]
> I just sigend the CLA.

Seems, you should do the last step from [hacking](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#submitting-your-first-pull-request):

`If you already have a change that you want to submit, you can also include the change to tools/.github-cla-signers`

**Comment by nicolasbock** [comment]
Done

**Comment by TheRealFalcon** [comment]
@nicolasbock , thanks for this submission!

The overall idea is a good one, but unfortunately `partprobe` doesn't come pre-installed on very many linux distributions. Can you update the change to use `partprobe` if it exists, but fall back to using `blockdev` if `partprobe` does not exist?

**Comment by nicolasbock** [comment]
Thanks @TheRealFalcon for the review! I have updated the PR to include `blkdev` as fallback as you suggested.

**Comment by nicolasbock** [comment]
Hi @mitechie ! Could you have a look at this PR? Thanks!

**Comment by mitechie** [comment]
Thanks for the ping. Let me check in with @TheRealFalcon about getting another look.

**Comment by nicolasbock** [comment]
> Thanks for the ping. Let me check in with @TheRealFalcon about getting another look.

Thanks!

**Review by TheRealFalcon — APPROVED** [review]
@nicolasbock My apologies! I saw your comment earlier but I misread it as you were going to make the change, not that you had already made the change.

This looks good to me now. Thanks!

**Pull request merged**
