### PR TITLE
Fix missing continue

### PR DESCRIPTION
**Pull request by eb3095**
## Proposed Commit Message
Fix missing continue

```
A continue was missing to allow interface seeking.
```

## Test Steps
Deploy an image with a private network on Vultr

## Checklist:

 - [ X ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ X ] I have updated or added any unit tests accordingly
 - [ X ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by eb3095** [comment]
Sorry, this one is a bit embarrassing. Apparently a continue went missing somewhere along the lines of the last pull request.

**Comment by TheRealFalcon** [comment]
@eb3095 , would it be better for the `return` to go inside the `try`? We can return the data once we have it, and if more exceptions pop up each one doesn't need to have it's own `continue`.

**Comment by eb3095** [comment]
> @eb3095 , would it be better for the `return` to go inside the `try`? We can return the data once we have it, and if more exceptions pop up each one doesn't need to have it's own `continue`.

The idea is not to have it fail out on the first exception and only the last. We are seeing private networks and lo get pushed through that loop. We want every interface from 0 to last to be tried until none are left to try.

**Comment by TheRealFalcon** [comment]
Sure, I'm just saying currently you have a structure like
```
for:
    try:
        ...
    except:
        ...
        continue
    return ...
```

Would it be better to replace with a structure like
```
for:
    try:
        ...
        return ...
    except:
        ...
```

Either way the return is still in the loop and `return`s when we find valid metadata and `continue`s when we don't.

**Comment by eb3095** [comment]
> Sure, I'm just saying currently you have a structure like
> 
> ```
> for:
>     try:
>         ...
>     except:
>         ...
>         continue
>     return ...
> ```
> 
> Would it be better to replace with a structure like
> 
> ```
> for:
>     try:
>         ...
>         return ...
>     except:
>         ...
> ```
> 
> Either way the return is still in the loop and `return`s when we find valid metadata and `continue`s when we don't.

Ah, my mistake, yeah, that actually makes a lot of sense! Not sure how I missed that one either! Getting it fixed now.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
