### PR TITLE
Changelog capture 22.3.1-4

### PR DESCRIPTION
**Pull request by blackboxsw**
## Proposed Commit Message

```
changelog: capture 22.3.1-4 releases

Manually capture in changelog published releases and security fixes.
```

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]

**Comment by blackboxsw** [comment]
Dropped trailing whitespace in Changelog just because every byte is precious :)

**Comment by holmanb** [comment]
My local version has a couple of more entries:
```diff
  diff --git a/ChangeLog b/ChangeLog
  index 9651093e4..6a23d2c45 100644
  --- a/ChangeLog
  +++ b/ChangeLog
  @@ -137,6 +137,14 @@
    - make: drop broken targets (#1688)
    - net: Passthough v2 netconfigs in netplan systems (#1650)
      [Alberto Contreras] (LP: #1978543)
  + - NM ipv6 connection does not work on Azure and Openstack (#1616)
  +   [Emanuele Giuseppe Esposito]
  + - Fix check_format_tip (#1679) [Alberto Contreras]
  + - DataSourceVMware: fix var use before init (#1674)
  +   [Andrew Kutz] (LP: #1987005)
  + - rpm/copr: ensure RPM represents new clean.d dir artifacts (#1680)
  + - test: avoid centos leaked check of /etc/yum.repos.d/epel-testing.repo
  +   (#1676)
   
   22.3
...
```

Were those droped just since they were "fixes"? Or some other reason?

**Comment by blackboxsw** [comment]
> 

Thanks @holmanb I had neglected to grab the entire changeset from our previous release. +1 pushed.

**Review by holmanb — APPROVED** [review]
Looks good to me. Thanks!

**Pull request merged**
