### PR TITLE
Fix arch systemd ordering cycle.

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

See individual commits. One is a fix for https://github.com/canonical/cloud-init/issues/5755 and the other cleans up redundant dependencies that were introduced in the single process change.

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [x] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by a-dubs — APPROVED** [review]
CI is happy so i am happy :)

Thank you for adding detailed context in each commit message @holmanb.

Also I assume you would like to rebase and not squash (you have the squash merge checkbox selected atm)

**Comment by TheRealFalcon** [comment]
+1 to the 2nd commit

**Comment by holmanb** [comment]
> ```
> {% if variant in ["almalinux", "cloudlinux", "ubuntu", "unknown", "debian", "rhel"] %}
> DefaultDependencies=no
> {% endif %}
> ...
> {% if variant in ["ubuntu", "unknown", "debian"] %}
> Before=sysinit.target
> {% endif %}
> ```
> 
> Should the rest of the OSes in the first section be extended to the 2nd section? Since it was part of the larger service file earlier, I would think yes for any distro that has `DefaultDependencies=no`

This ordering was inherited from `cloud-init-local.service`. I think that the answer is "yes", but I'd prefer to make service file cleanups in a separate PR.

**Review by TheRealFalcon — APPROVED** [review]
LGTM! Thanks for the extra context.

**Pull request merged**
