### PR TITLE
test: Run Alpine tests without network

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
test: Run Alpine tests without network

None of the unit tests should be reaching out to the network.
Since Alpine tests run under LXD, we can still easily run tests there
without network.

Also, include the tzdata package that was missed in 725f5fb and
remove unneeded network debug lines.
```

## Additional Context
See https://github.com/canonical/cloud-init/pull/5212#pullrequestreview-2023557564

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Requires https://github.com/canonical/cloud-init/pull/5210 or a more creative solution

**Comment by holmanb** [comment]
> Requires #5210 or a more creative solution

Just needs a rebase on main then, right?

**Comment by TheRealFalcon** [comment]
> Just needs a rebase on main then, right?

Apparently not. :smile:

**Comment by TheRealFalcon** [comment]
@holmanb should be good now

**Review by holmanb — APPROVED** [review]
@TheRealFalcon Ship it!

**Pull request merged**
