### PR TITLE
Add ajmyyra as contributor

### PR DESCRIPTION
**Pull request by ajmyyra**
Add ajmyyra as contributor in the project.

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
I was unable to find an individual signing the Canonical Contributor license agreement with the github username `ajmyyra`  please sign the agreement  and provide the appropriate github username from which you intend to make pull request submissions.

https://ubuntu.com/legal/contributors/agreement

**Comment by ajmyyra** [comment]
Hi @blackboxsw! We signed CLA as a company by sending the signed form to contributor-agreement@canonical.com. Should I still sign it individually as well? Not a problem for me, but just asking to avoid later hassles with that entity CLA.

**Comment by OddBloke** [comment]
> Hi @blackboxsw! We signed CLA as a company by sending the signed form to [contributor-agreement@canonical.com](mailto:contributor-agreement@canonical.com). Should I still sign it individually as well? Not a problem for me, but just asking to avoid later hassles with that entity CLA.

Canonical take a couple of weeks off over New Year, so it's likely there's a bit of a backlog for the folks who process those forms. Individual signatures are handled automatically so we can verify them almost immediately; that's probably the best route to go with for now.

Thanks!

**Comment by ajmyyra** [comment]
Alright, good to know! Signed it individually now. :)

**Review by OddBloke — APPROVED** [review]
I've confirmed the individual signature, thanks!

**Pull request merged**
