### PR TITLE
Fix nm bridges

### PR DESCRIPTION
**Pull request by TheRealFalcon**
In draft state until https://github.com/canonical/cloud-init/pull/5674 merges.

## Proposed Commit Message

```
fix: Render v2 bridges correctly on network-manager with set-name

Similar to the recent sysconfig fix, ensure bridges render correctly
for configs that contain `set-name`.

Fixes GH-5717
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
FYI @xiachen-rh . I am less familiar with network manager keyfile definition, so please let me know if this works for you.

**Comment by xiachen-rh** [comment]
> FYI @xiachen-rh . I am less familiar with network manager keyfile definition, so please let me know if this works for you.

OK, I will test it and let you know the result.

**Comment by xiachen-rh** [comment]
@TheRealFalcon  It works when using NM,  thanks!

**Review by holmanb — APPROVED** [review]
Thanks @TheRealFalcon, this look good to me!

**Pull request merged**
