### PR TITLE
lp-to-git-users: adding B1Sandmann

### PR DESCRIPTION
**Pull request by B1Sandmann**
Mapped from b1sandmann

### CODE REVIEW

**Comment by B1Sandmann** [comment]
Hi, I'm still waiting for a review could you check @mitechie ? Thanks :)

**Comment by mitechie** [comment]
Apologies, first day back post-holiday time. Let me get it updated.

**Comment by OddBloke** [comment]
Hi Jens, apologies for dropping this!

It looks like you signed the CLA before we had a GitHub field in the form: could you either resubmit the form at https://ubuntu.com/legal/contributors including it, or follow the process at https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#transferring-cla-signatures-from-launchpad-to-github to give us evidence that the Launchpad account attached to your previous signature is owned by the same person as this GitHub account, please?


Thanks!

**Comment by B1Sandmann** [comment]
Hi @OddBloke this PR was created using the migrate tool. Did I miss something? The PR on launchpad side is https://code.launchpad.net/~b1sandmann/cloud-init/+git/cloud-init/+merge/399100

**Comment by OddBloke** [comment]
> Hi @OddBloke this PR was created using the migrate tool. Did I miss something? The PR on launchpad side is https://code.launchpad.net/~b1sandmann/cloud-init/+git/cloud-init/+merge/399100

Oh, my apologies! I didn't see the corresponding email from Launchpad (for whatever reason) and failed to read the filename here correctly. Let me take a look now.

**Review by OddBloke — APPROVED** [review]
Thanks! Confirmed in concert with https://code.launchpad.net/~b1sandmann/cloud-init/+git/cloud-init/+merge/399100

**Pull request merged**
