### PR TITLE
systemd: add Before=shutdown.target when Conflicts=shutdown.target is used

### PR DESCRIPTION
**Pull request by paride**
Lintian spotted the following issue:

>   The specified systemd .service file contains both DefaultDependencies=no
>   and Conflicts=shutdown.target directives without Before=shutdown.target.
> 
>   This can lead to problems during shutdown because the service may linger
>   until the very end of shutdown sequence as nothing requests to stop it
>   before (due to DefaultDependencies=no).
> 
>   There is race condition between stopping units and systemd getting a
>   request to exit the main loop, so it may proceed with shutdown before
>   all pending stop jobs have been processed.

  Please add Before=shutdown.target.

[1] https://lintian.debian.org/tags/systemd-service-file-shutdown-problems.html

### CODE REVIEW

**Comment by paride** [comment]
In the case of cloud-init this is probably not a real issue, but I don't see why not doing it in the safest way given that there are no side effects, as far as I can tell.

**Comment by paride** [comment]
Well, the cloud_tests integration testing should tell us if we regressed the systemd services. The CI runs a subset of them on a LXD instance, but I can make a full run and make sure nothing breaks.

**Comment by paride** [comment]
I ran the full cloud_tests suite on Groovy on lxd, nocloud-kvm, ec2 and all the tests passed with no errors:
```
results/ec2/groovy/bugs/lp1628337/result.json:  "errors": []
results/ec2/groovy/main/command_output_simple/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_conf/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_disable_suites/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_primary/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_proxy/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_security/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_sources_key/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_sources_keyserver/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_sources_list/result.json:  "errors": []
results/ec2/groovy/modules/apt_configure_sources_ppa/result.json:  "errors": []
results/ec2/groovy/modules/apt_pipelining_disable/result.json:  "errors": []
results/ec2/groovy/modules/apt_pipelining_os/result.json:  "errors": []
results/ec2/groovy/modules/bootcmd/result.json:  "errors": []
results/ec2/groovy/modules/byobu/result.json:  "errors": []
results/ec2/groovy/modules/ca_certs/result.json:  "errors": []
results/ec2/groovy/modules/debug_disable/result.json:  "errors": []
results/ec2/groovy/modules/debug_enable/result.json:  "errors": []
results/ec2/groovy/modules/final_message/result.json:  "errors": []
results/ec2/groovy/modules/keys_to_console/result.json:  "errors": []
results/ec2/groovy/modules/locale/result.json:  "errors": []
results/ec2/groovy/modules/lxd_bridge/result.json:  "errors": []
results/ec2/groovy/modules/lxd_dir/result.json:  "errors": []
results/ec2/groovy/modules/ntp/result.json:  "errors": []
results/ec2/groovy/modules/ntp_chrony/result.json:  "errors": []
results/ec2/groovy/modules/ntp_pools/result.json:  "errors": []
results/ec2/groovy/modules/ntp_servers/result.json:  "errors": []
results/ec2/groovy/modules/ntp_timesyncd/result.json:  "errors": []
results/ec2/groovy/modules/package_update_upgrade_install/result.json:  "errors": []
results/ec2/groovy/modules/runcmd/result.json:  "errors": []
results/ec2/groovy/modules/seed_random_data/result.json:  "errors": []
results/ec2/groovy/modules/set_hostname/result.json:  "errors": []
results/ec2/groovy/modules/set_hostname_fqdn/result.json:  "errors": []
results/ec2/groovy/modules/set_password/result.json:  "errors": []
results/ec2/groovy/modules/set_password_expire/result.json:  "errors": []
results/ec2/groovy/modules/set_password_list/result.json:  "errors": []
results/ec2/groovy/modules/set_password_list_string/result.json:  "errors": []
results/ec2/groovy/modules/ssh_auth_key_fingerprints_disable/result.json:  "errors": []
results/ec2/groovy/modules/ssh_auth_key_fingerprints_enable/result.json:  "errors": []
results/ec2/groovy/modules/ssh_import_id/result.json:  "errors": []
results/ec2/groovy/modules/ssh_keys_generate/result.json:  "errors": []
results/ec2/groovy/modules/timezone/result.json:  "errors": []
results/ec2/groovy/modules/user_groups/result.json:  "errors": []
results/ec2/groovy/modules/write_files/result.json:  "errors": []
results/lxd/groovy/bugs/lp1628337/result.json:  "errors": []
results/lxd/groovy/main/command_output_simple/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_conf/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_disable_suites/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_primary/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_proxy/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_security/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_sources_key/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_sources_keyserver/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_sources_list/result.json:  "errors": []
results/lxd/groovy/modules/apt_configure_sources_ppa/result.json:  "errors": []
results/lxd/groovy/modules/apt_pipelining_disable/result.json:  "errors": []
results/lxd/groovy/modules/apt_pipelining_os/result.json:  "errors": []
results/lxd/groovy/modules/bootcmd/result.json:  "errors": []
results/lxd/groovy/modules/byobu/result.json:  "errors": []
results/lxd/groovy/modules/ca_certs/result.json:  "errors": []
results/lxd/groovy/modules/debug_disable/result.json:  "errors": []
results/lxd/groovy/modules/debug_enable/result.json:  "errors": []
results/lxd/groovy/modules/final_message/result.json:  "errors": []
results/lxd/groovy/modules/keys_to_console/result.json:  "errors": []
results/lxd/groovy/modules/locale/result.json:  "errors": []
results/lxd/groovy/modules/lxd_bridge/result.json:  "errors": []
results/lxd/groovy/modules/lxd_dir/result.json:  "errors": []
results/lxd/groovy/modules/ntp/result.json:  "errors": []
results/lxd/groovy/modules/ntp_chrony/result.json:  "errors": []
results/lxd/groovy/modules/ntp_pools/result.json:  "errors": []
results/lxd/groovy/modules/ntp_servers/result.json:  "errors": []
results/lxd/groovy/modules/ntp_timesyncd/result.json:  "errors": []
results/lxd/groovy/modules/package_update_upgrade_install/result.json:  "errors": []
results/lxd/groovy/modules/runcmd/result.json:  "errors": []
results/lxd/groovy/modules/seed_random_data/result.json:  "errors": []
results/lxd/groovy/modules/set_hostname/result.json:  "errors": []
results/lxd/groovy/modules/set_hostname_fqdn/result.json:  "errors": []
results/lxd/groovy/modules/set_password/result.json:  "errors": []
results/lxd/groovy/modules/set_password_expire/result.json:  "errors": []
results/lxd/groovy/modules/set_password_list/result.json:  "errors": []
results/lxd/groovy/modules/set_password_list_string/result.json:  "errors": []
results/lxd/groovy/modules/ssh_auth_key_fingerprints_disable/result.json:  "errors": []
results/lxd/groovy/modules/ssh_auth_key_fingerprints_enable/result.json:  "errors": []
results/lxd/groovy/modules/ssh_import_id/result.json:  "errors": []
results/lxd/groovy/modules/ssh_keys_generate/result.json:  "errors": []
results/lxd/groovy/modules/timezone/result.json:  "errors": []
results/lxd/groovy/modules/user_groups/result.json:  "errors": []
results/lxd/groovy/modules/write_files/result.json:  "errors": []
results/nocloud-kvm/groovy/bugs/lp1628337/result.json:  "errors": []
results/nocloud-kvm/groovy/main/command_output_simple/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_conf/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_disable_suites/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_primary/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_proxy/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_security/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_sources_key/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_sources_keyserver/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_sources_list/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_configure_sources_ppa/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_pipelining_disable/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/apt_pipelining_os/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/bootcmd/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/byobu/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ca_certs/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/debug_disable/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/debug_enable/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/final_message/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/keys_to_console/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/locale/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/lxd_bridge/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/lxd_dir/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ntp/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ntp_chrony/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ntp_pools/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ntp_servers/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ntp_timesyncd/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/package_update_upgrade_install/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/runcmd/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/seed_random_data/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_hostname/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_hostname_fqdn/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_password/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_password_expire/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_password_list/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/set_password_list_string/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ssh_auth_key_fingerprints_disable/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ssh_auth_key_fingerprints_enable/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ssh_import_id/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/ssh_keys_generate/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/timezone/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/user_groups/result.json:  "errors": []
results/nocloud-kvm/groovy/modules/write_files/result.json:  "errors": []
```

**Comment by igalic** [comment]
https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/rc-scripts.html perhaps in FreeBSD we should also add

```sh
# KEYWORD: shutdown
```

in our service templates
at least before we merge https://github.com/canonical/cloud-init/pull/48  ;)

**Pull request merged**
