### PR TITLE
Fix the distro.osfamily output problem in the openEuler system.

### PR DESCRIPTION
**Pull request by xiaoge1001**
fix https://bugs.launchpad.net/cloud-init/+bug/1999042

### CODE REVIEW

**Comment by xiaoge1001** [comment]
https://stackoverflow.com/questions/28159539/how-to-fix-the-w293-blank-line-contains-whitespace

I didn't find a problem using the above method.

**Comment by xiaoge1001** [comment]
Lint Tests / Check black  failed, I use the following command to check：
python -m black . --check

**Comment by TheRealFalcon** [comment]
@xiaoge1001 do you work on openEuler? I was under the impression it is a derivative of Ret Hat. Why do we need to distinguish it with a separate osfamily here?

If this change is needed, I think it also makes sense to remove it from here: https://github.com/canonical/cloud-init/blob/main/cloudinit/distros/__init__.py#L60

**Comment by xiaoge1001** [comment]
I think OSFAMILIES needs to be modified, I'll deal with it later.

**Comment by xiaoge1001** [comment]
I've discussed it with my team and we all agree that this is really wrong and needs to be changed.

**Comment by xiaoge1001** [comment]
@TheRealFalcon Hello, any more questions?

**Review by TheRealFalcon — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
