### PR TITLE
Fix issue regarding cache and region codes

### PR DESCRIPTION
**Pull request by eb3095**
## Proposed Commit Message

```
Fix a bug related to the region being reassigned and breaking init-local when cache is used. 
```

## Additional Context
image

## Test Steps
* Deploy vultr instance
* Reboot

## Checklist:
 - [X] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [X] I have updated or added any unit tests accordingly
 - [X] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by holmanb** [comment]
I see this bug was introduced in https://github.com/canonical/cloud-init/commit/69f9a7888ea770f4dc0454be91dea225bdd5957. This datastructure is pickled, so we probably shouldn't be modifying the type of the data structure. What was wrong with the region code handling before 69f9a7888ea770f4? I don't see any explanation given in [that PR](https://github.com/canonical/cloud-init/pull/1192), and with a quick scan I'm not seeing where that gets used.

**Comment by eb3095** [comment]
The data structure we used for metadata prior to that commit changed. Before we assigned a string with the VM's region's airport code, but this broke several distros that use that to setup the repos such as Ubuntu, something we were requested to resolve. However the metadata is now provided as such,

```
 "region": {
  "countrycode": "US",
  "regioncode": "EWR"
 },
 ```
 
region however is the metadata portion used so it cant just be dropped into the region variable like that. Note this fix has been tested and is working as expected and we are likely moving this patch into production for the time being.

**Comment by eb3095** [comment]
Eh, I went ahead and just did that. This is cleaner and feels better overall. I can revert however if its not ideal.

**Review by holmanb — APPROVED** [review]
> This is cleaner and feels better overall.

Agreed. Putting the transformations in a function seems cleaner, and shifting the callsite to within `get_metadata()` avoids applying the transformation multiple times.

**Pull request merged**
