### PR TITLE
feat(freebsd): support freebsd find part by gptid and ufsid

### PR DESCRIPTION
**Pull request by jinkkkang**
## Proposed Commit Message

```
feat(freebsd): support freebsd find part by gptid and ufsid

freebsd obtained device partition name by the function find_freebsd_part, the params of function is the device name mounted,  usually is first  field of /etc/fstab ,  like /dev/gpt/rootfs,  but freebsd fstab also support gptid or ufsid for a unique id to identify  
 partitions, like /dev/gptid/xxx, /dev/ufsid/xxx,  update function to  support
```

## Additional Context

Regarding the FreeBSD fstab configuration supporting  gptid  and ufsid , can refer to these two links
[ufsid](https://forums.freebsd.org/threads/how-to-use-drive-unique-id-in-fstab.19690/)
[gptid](https://forums.freebsd.org/threads/how-to-use-uuid-to-identify-partitions-on-freebsd.89163/)

### CODE REVIEW

**Comment by holmanb** [comment]
@jinkkkang thanks for this PR, [can you please sign the CLA](https://cloudinit.readthedocs.io/en/latest/development/index.html#prerequisites)?

**Comment by jinkkkang** [comment]
> @jinkkkang thanks for this PR, [can you please sign the CLA](https://cloudinit.readthedocs.io/en/latest/development/index.html#prerequisites) and then add yourself to the signers file?

have signed，thanks

**Comment by jinkkkang** [comment]
fixed  error of lint check

**Review by igalic — APPROVED** [review]
looks good! Thank you for the contribution!

---
apparently, AWS (without ZFS) uses this form:
```
ec2-user@freebsd:~ $ glabel status -s
                                gpt/bootfs  N/A  nda0p1
gptid/053c5311-7fcb-11ee-a7ba-002590ec5bf2  N/A  nda0p1
                                gpt/efiesp  N/A  nda0p2
                                gpt/rootfs  N/A  nda0p3
```

**Review by holmanb — APPROVED** [review]
LGTM, thanks and welcome to cloud-init @jinkkkang!

**Pull request merged**
