### PR TITLE
fix(cacerts): Correct configuration customizations for Photon

### PR DESCRIPTION
**Pull request by dark2phoenix**
## Proposed Commit Message
- Fixes certificates being placed in the wrong folder 
  (/etc/pki/tls/certs/ instead of the correct /etc/ssl/certs/)
- Fixes certificates having the wrong extension (.crt instead of .pem)

## Test Steps
1.  Add cacerts: stanza to cloud-init
2.  Deploy config to VMware Photon OS (4.x or 5.x)
3.  Find created cert in the /etc/ssl/certs/ directory with the .pem extension
4.  Find the contents of the cert inside /etc/pki/tls/certs/ca-bundle.crt

## Checklist
- [ x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
@sshedi , sorry the last one I pinged you on was closed. Do you mind reviewing this one?

**Comment by sshedi** [comment]
No problem @TheRealFalcon 

@dark2phoenix 
I don't see the test related changes I provided in this CR.

**Comment by dark2phoenix** [comment]
> e the test related changes I provided in this CR.

Umm...I pulled from the main branch before I made these changes (had to create a whole new PR to do it).  Are you saying they disappeared from the repo, or where you expecting me to write some additional tests?

**Comment by TheRealFalcon** [comment]
Just as context for everybody, we had two previous PRs related to this functionality:
https://github.com/canonical/cloud-init/pull/4763 did merge and is in main. In that PR, @sshedi specifically requested to use different paths than were initially proposed. If by "test related changes I provided in this CR" you're referring to the changes in #4763 , those changes are already in main.
https://github.com/canonical/cloud-init/pull/5048 had some git issues and so never merged.

This one is similar to #4763 , but uses different paths than before. @sshedi , in #4763, you suggested to use some different paths, so I'm pinging you again here to see if these updates make sense. I'm not familiar enough with photon to know what the paths should be.

**Comment by dark2phoenix** [comment]
I based the path and filename extension based on the content of the tool that integrates custom certs( "/usr/bin/rehash_ca_certificates.sh") into photon :

```
#!/bin/bash

set -e

CERTIFICATES_PATH="/etc/ssl/certs/"
CONCATENATED_CERT_FILE="/etc/pki/tls/certs/ca-bundle.crt"

openssl rehash $CERTIFICATES_PATH

if [ $? != 0 ]; then
    echo "Error while c_rehashing"
fi

cat $CERTIFICATES_PATH*.pem > $CONCATENATED_CERT_FILE
```

In this file, you can ee it only looks in '/etc/ssl/certs/' for custom certificates and it only operates on .pem files.

**Review by sshedi — APPROVED** [review]
My bad, I forgot about the previous CR.

**Comment by dark2phoenix** [comment]
Am I responsible for the "linkcheck in CI/linkcheck" errors?  They are not in any code/doc I submitted.

**Review by TheRealFalcon — APPROVED** [review]
> Am I responsible for the "linkcheck in CI/linkcheck" errors? They are not in any code/doc I submitted.

No, things look good now. Thanks!

**Pull request merged**
