### PR TITLE
d/control: remove netifaces [noble]

### PR DESCRIPTION
**Pull request by catmsred**
netifaces is being removed from tip of main in GH-4634.  This change also removes it from the Ubuntu packaging.

## Test Steps
Untested

## Checklist

- [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by holmanb** [comment]
@catmsred this needs to be refreshed against the recent updates to ubuntu/devel

**Review by holmanb — CHANGES_REQUESTED** [review]
This looks really close @catmsred, however since this builds directly against 24.1, which still requires netifaces, build fails with the following error:

```
==================================== ERRORS ====================================
___________ ERROR collecting tests/unittests/sources/test_common.py ____________
ImportError while importing test module '/<<PKGBUILDDIR>>/tests/unittests/sources/test_common.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unittests/sources/test_common.py:34: in <module>
    from cloudinit.sources import DataSourceVMware as VMware
cloudinit/sources/DataSourceVMware.py:75: in <module>
    import netifaces
E   ModuleNotFoundError: No module named 'netifaces'
___________ ERROR collecting tests/unittests/sources/test_vmware.py ____________
ImportError while importing test module '/<<PKGBUILDDIR>>/tests/unittests/sources/test_vmware.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unittests/sources/test_vmware.py:17: in <module>
    from cloudinit.sources import DataSourceVMware
cloudinit/sources/DataSourceVMware.py:75: in <module>
    import netifaces
E   ModuleNotFoundError: No module named 'netifaces'
=============================== warnings summary ===============================
../../../usr/lib/python3/dist-packages/_pytest/config/__init__.py:1316
  /usr/lib/python3/dist-packages/_pytest/config/__init__.py:1316: PytestRemovedIn8Warning: The --strict option is deprecated, use --strict-markers instead.
    self.issue_config_time_warning(

tests/unittests/helpers.py:554
  /<<PKGBUILDDIR>>/tests/unittests/helpers.py:554: DeprecationWarning: Accessing jsonschema.__version__ is deprecated and will be removed in a future release. Use importlib.metadata directly to query for jsonschema's version.
    int(part) for part in jsonschema.__version__.split(".")  # type: ignore

cloudinit/sources/DataSourceAzure.py:52
  /<<PKGBUILDDIR>>/cloudinit/sources/DataSourceAzure.py:52: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
    import crypt

tests/unittests/config/test_cc_ubuntu_pro.py:451
  /<<PKGBUILDDIR>>/tests/unittests/config/test_cc_ubuntu_pro.py:451: DeprecationWarning: Accessing jsonschema.__version__ is deprecated and will be removed in a future release. Use importlib.metadata directly to query for jsonschema's version.
    if Version.from_str(getattr(jsonschema, "__version__", "999"))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/unittests/sources/test_common.py
ERROR tests/unittests/sources/test_vmware.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 4 warnings, 2 errors in 2.11s =========================
make[2]: *** [Makefile:30: unittest] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
make[1]: *** [debian/rules:13: override_dh_auto_test] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:9: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2024-03-08T01:54:56Z

Finished
--------


+------------------------------------------------------------------------------+
| Cleanup                                                                      |
+------------------------------------------------------------------------------+

Purging /<<BUILDDIR>>
Not cleaning session: cloned chroot in use
E: Build failure (dpkg-buildpackage died)

+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+

Build Architecture: amd64
Build Type: binary
Build-Space: 22640
Build-Time: 4
Distribution: noble
Fail-Stage: build
Host Architecture: amd64
Install-Time: 17
Job: /home/holmanb/ci-a/../out/cloud-init_24.1-0ubuntu2.dsc
Machine Architecture: amd64
Package: cloud-init
Package-Time: 88
Source-Version: 24.1-0ubuntu2
Space: 22640
Status: attempted
Version: 24.1-0ubuntu2
--------------------------------------------------------------------------------
Finished at 2024-03-08T01:54:56Z
Build needed 00:01:28, 22640k disk space
E: Build failure (dpkg-buildpackage died)
```

You can reproduce this by running:
```
build-package -- -S -d
sbuild --dist=noble --arch=amd64 ../out/cloud-init_24.1-0ubuntu2.dsc
```

To rectify this, we'll need a new upstream snapshot first. Hopefully in the near future we won't need new upstream snapshots, but for now we do.

**Comment by catmsred** [comment]
I have (I think) created the requisite new upstream snapshot

**Comment by holmanb** [comment]
```
Status: successful
Version: 24.2~1g621c522c-0ubuntu1
--------------------------------------------------------------------------------
Finished at 2024-03-09T19:57:27Z
Build needed 00:02:15, 27684k disk space
```

@catmsred Nice, that looks much better!

Question: How did you end up with b392d725d3528fe0b2c8cf1403c3d62547aecc3c and b60e4c184b8c25f8c26f67eb0ed7ba87f9a688c6 in the middle of the merge commits? Maybe a manual rebase after the snapshot? This technically works, but normally I don't think we insert commits into the middle of a block of commits introduced by a merge. Would you mind rebasing those commits to the end of the this PR? Once you do, I think this is ready to merge!

**Review by holmanb — CHANGES_REQUESTED** [review]
see comment

**Comment by catmsred** [comment]
> Question: How did you end up with https://github.com/canonical/cloud-init/commit/b392d725d3528fe0b2c8cf1403c3d62547aecc3c and https://github.com/canonical/cloud-init/commit/b60e4c184b8c25f8c26f67eb0ed7ba87f9a688c6 in the middle of the merge commits? Maybe a manual rebase after the snapshot? This technically works, but normally I don't think we insert commits into the middle of a block of commits introduced by a merge. Would you mind rebasing those commits to the end of the this PR? Once you do, I think this is ready to merge!

I have no idea how that happened, to be honest.  I ran `new_upstream_snapshot.py` uss-tableflip and this was the result.  I will rebase to fix that.

**Comment by catmsred** [comment]
Linkcheck failure is not related to this code

**Comment by TheRealFalcon** [comment]
@catmsred , sorry for the churn on this one. Since we've already independently merged an upstream snapshot for this branch, I'm closing this PR in favor of https://github.com/canonical/cloud-init/pull/5081 .

**Pull request closed without merging**
