### PR TITLE
daily build recipe fix (mantic): new-upstream-snapshot to resolve merge conflicts with tip of main

### PR DESCRIPTION
**Pull request by blackboxsw**
## Additional Context
Failed mantic daily recipe https://launchpadlibrarian.net/732786413/buildlog.txt.gz

Fix daily builds for mantic due to drift in tip of main being incompatible with downstream quilt patches. Not intended for release, just a sync and quilt patch fix.
Following some of the docs at https://github.com/canonical/uss-tableflip/blob/main/doc/cloud-init-daily-builds.md

### Procedure to make this pull request 
```
git fetch upstream
git checktout -B upstream/ubuntu/mantic -B ubuntu/mantic
new_upstream_snapshot.py   
# See quilt push failures
quilt push -a
quilt push -f
# Manually apply rejected quilt patch issues
tests/unittests/cmd/test_status.py.rej tests/unittests/cmd/test_status.py
quilt refresh
quilt pop -a
# Test quilt patch apply/removal individually and refresh to address fuzz warnings
while true; do quilt push; RC=$?; quilt refresh; if [ $RC == 2 ]; then  break; fi; done
quilt pop -a
git commit -am 'refresh patches'
# continue new_upstream_snapshot
 new_upstream_snapshot.py --post quilt
# cleanup duplicated "refresh" messages and "Upstream snapshot based on ..." in debian/changelog 
vi debian/changelog
```
## Test Steps

Esure we can merge against main and apply the downstream patches as this is what our daily recipe does
```
git checkout upstream/main -B main
git merge upstream/ubuntu/mantic
quilt push -a
quilt pop -a
```

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by blackboxsw** [comment]
Also performed same procedure above to create:
- jammy: https://github.com/blackboxsw/cloud-init/tree/ubuntu/jammy
- focal: https://github.com/blackboxsw/cloud-init/tree/ubuntu/focal

**Review by TheRealFalcon — APPROVED** [review]
LGTM though this PR is still in draft state. Is that intentional?

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
Scratch that. We get `test_status.py` failures using the current version of the quilt patch. In particular, for the tests that fail, text needs to be `enabled-by-kernel-command-line` rather than `enabled-by-kernel-cmdline`.

Here is an example for Focal:
https://github.com/canonical/cloud-init/blob/ubuntu/focal/debian/patches/status-do-not-remove-duplicated-data.patch

**Comment by blackboxsw** [comment]
@TheRealFalcon thanks for looking this over yesterday. Yes it was in draft as I thought I saw a merge conflict causing a problem for me when trying to build the package. You nailed the problem there. thx I've reflect these changes to my jammy, focal and mantic branches as well as syncing the upstream/ubuntu/(focal|jammy|mantic)-24.1.x debian/changelog released content to tidy up these branches for our next SRU of 24.2

**Pull request merged**
