### PR TITLE
Deprecate the users ssh-authorized-keys property

### PR DESCRIPTION
**Pull request by afbjorklund**
The previous cloud-config still works without any issues, but it doesn't pass validation - not even as deprecated.

Example from https://lima-vm.io default

Currently it does not validate, therefore.

commit b27f713ae5b4c5b38eda63758dbaeab92be13b9d

## Proposed Commit Message

```
fix: deprecate ssh-authorized-keys in schema

Deprecate the users ssh-authorized-keys property
```

## Checklist

- [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [x] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by catmsred** [comment]
Thank you for helping improve cloud-init!  Your change looks good to me.  Have you done any additional testing to ensure that this change unblocks your use case?  If so, feel free to add a comment expanding on it.

Additionally, can you also [sign the CLA](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#sign-the-cla) as part of this PR?

**Comment by afbjorklund** [comment]
> Have you done any additional testing to ensure that this change unblocks your use case?

By allowing "ssh-authorized-keys" to pass, the rest of our generated cloud-config now passes.

* https://github.com/lima-vm/lima/pull/2267

There are two deprecations, but if I "fix" these they will break with older/other cloud-init...

We did find one bug, where we were passing `trusted: null` instead of omitting the field.

**Comment by afbjorklund** [comment]
Closes #3984

**Comment by TheRealFalcon** [comment]
@afbjorklund , To my knowledge, that isn't a valid key on any supported version of cloud-init. Do you have an example of a cloud-config that works when `ssh-authorized-keys` is used? If so, can you tell me what version of cloud-init that it works on for you?

**Comment by afbjorklund** [comment]
There is still code in cloud-unit, that replaces dashes in keys with underscores. I can get you versions, but all major distros

**Comment by TheRealFalcon** [comment]
@afbjorklund , thanks for updated info. You are correct. I filed https://github.com/canonical/cloud-init/issues/5187 to fix the remaining keys.

The rest of the PR looks good, but for the CLA, I noticed that you signed the CLA, but haven't yet added yourself to the CLA signers file. As part of this PR, please also add your name (alphabetically) to [the CLA signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers). The full details are described [in the documentation](https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#add-your-name-to-the-cla-signers-list).

**Review by TheRealFalcon — APPROVED** [review]
LGTM! Assuming CI passes, I'll merge it as-is.

**Comment by TheRealFalcon** [comment]
Bah, one more CI failure. JSON formatting:
```diff
diff --git a/cloudinit/config/schemas/schema-cloud-config-v1.json b/cloudinit/config/schemas/schema-cloud-config-v1.json
index 863c0c200..94a356747 100644
--- a/cloudinit/config/schemas/schema-cloud-config-v1.json
+++ b/cloudinit/config/schemas/schema-cloud-config-v1.json
@@ -361,7 +361,7 @@
           },
           "minItems": 1
         },
-       "ssh-authorized-keys": {
+        "ssh-authorized-keys": {
           "allOf": [
             {
               "type": "array",
```

**Comment by afbjorklund** [comment]
Weird, I thought I had updated that stray tab once already....

**Comment by CalvoM** [comment]
Tracking at https://warthogs.atlassian.net/browse/SC-1777

**Pull request merged**
