### PR TITLE
Ubuntu/jammy: 24.3.1 upstream snapshot release

### PR DESCRIPTION
**Pull request by blackboxsw**
### Full package diff review branch
For full package dff please see: https://github.com/blackboxsw/cloud-init/pull/28

The upstream/ubuntu/jammy branch receives multiple unreleased pull request merges between the time the previous 24.2 published release and a new upstream release 24.3 for a couple of reasons:
  -  add quilt patches to retain stable behavior when new features are land in main that we know we want to revert on stable branches
  -  perform interim unreleased new_upstream_snapshots to fix daily build recipes when commits to main cause drift that quilt is unable to resolve with fuzz handling

Given that this PR is only the latest unreleased changeset proposed into upstream/ubuntu/jammy, it doesn't represent the full debdiff SRU reviewers would expect to see of all unreleased content since latest published cloud-init in jammy-updates. To aid the  review of this changeset, we propose a secondary PR to containing the entire diff of all unreleased content to make that coordination and discussion easier in github prior to landing this PR and performing an upload to jammy:

Note: https://github.com/canonical/cloud-init/pull/5669#discussion_r1747615596 approved the fix to d/patches/no-single-process.patch. cherry-picked this change from noble into focal and jammy 

## Testing
- quilt push -a ; tox -e py3; quilt pop -a  # confirm no remaining functional `cloud-init-(network|main).service` references
- build-package
- -build # no new lintian warnings/errors
- package upgrade test (also covered anyway in daily integration tests) # specifically validate no systemd unit or target inconsistencies w/ cloud-init-main or cloud-init-network.service vs cloud-init.service

## Expected CI failures on this PR 
- packaging tests should fail due to drift in main after 24.3.1 upstream release was cut rendering the no-single-process.patch unable to apply even with fuzz. this broke [our daily recipe PPA builder](https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+recipebuild/3781794) and will be resolved just after this release is cut by performing another new_upstream_snapshot to refresh quilt patches against tip of main

### CODE REVIEW

**Comment by holmanb** [comment]
@blackboxsw it looks like the check patch test is failing on both PRs

**Comment by blackboxsw** [comment]
> @blackboxsw it looks like the check patch test is failing on both PRs

@holmanb This is expected (and started [failing on daily builds 3 days ago](https://launchpadlibrarian.net/747450627/buildlog.txt.gz) after the 24.3.1 upstream release cut. We do need to fix daily recipes and can do this w/ an unreleased new_upstream_snapshot.py against tip of main once this branch clears review. I'm adding context to this PR now to aid review for @panlinux

**Review by TheRealFalcon — COMMENTED** [review]
d/changelog has some repeated lines for refreshing patches and the upstream snapshot line but otherwise LGTM.

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Pull request merged**
