### PR TITLE
net: Fix static routes to host in eni renderer

### PR DESCRIPTION
**Pull request by tnt-dev**
Route '-net' parameter is incompatible with /32 IPv4 networks without 'netmask' part so we have to use '-host' in that case.

## Checklist: ##
- [x] My code follows the process laid out in the documentation
- [x] I have updated or added any unit tests accordingly
- [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by igalic — COMMENTED** [review]
is this equally broken for IPv6?

**Comment by tnt-dev** [comment]
No, in IPv6 mode route works well without [-host|-net] part:

> $ route -A inet6 add 2a00:1450:400e:80d::200e/128 gw $GW_IP
> $ route -A inet6 add 2000::/3 gw 2a02:6ea0:c007::1337 gw $GW_IP

**Comment by igalic** [comment]
@mitechie this doesn't seem to be on anyone's radar (but that's understandable, given the current SRU work)

**Comment by mitechie** [comment]
Thanks, it's on the board of things to review/get landed after the release. We'll get caught up on it. Thanks Mina!

**Comment by TheRealFalcon** [comment]
Hey @tnt-dev , thanks for the contribution!

I noticed you added yourself to the CLA signers file, but have you signed the [actual CLA](https://ubuntu.com/legal/contributors/agreement) too? I'm not seeing your information there. If you did, can you provide the date that you signed it?

We have also recently introduced [integration testing](https://cloudinit.readthedocs.io/en/latest/topics/integration_tests.html) into cloud-init. As part of this PR, would you be able to add an integration test for this change? [test_gh626.py](https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_gh626.py) also uses a network config and would probably be the best example to base your test on.

**Comment by tnt-dev** [comment]
CLA is signed, integration test has been added.

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
This update looks good. Just two more minor comments inline and then I think it'll be good to land.

**Comment by tnt-dev** [comment]
Yes, I have removed SRU pytest decorator and have added a short comment about the source of the original problem.

**Review by TheRealFalcon — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
