### PR TITLE
remove unnecessary reboot from gpart resize

### PR DESCRIPTION
**Pull request by igalic**
## Proposed Commit Message

> remove unnecessary reboot from gpart resize
>
> a reboot after `gpart resize` hasn't been necessary for a long while!

## Additional Context

ref https://wiki.freebsd.org/GrowingFilesystemsOnline
LP# 1902370

## Test Steps

- resize the server's disk image (in my case this was done with qemu-img resize while the server was off, i think that's probably not necessary) 
- start server up
- `gpart list` should show the partitions as it "corrupt"
- run `gpart recover…` as per our code
- run `gpart resize…` as per our code
- `gpart list` should  now show the new size
- run `zpool online…` as per our code
- `zfs list` should show the new size

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I haven't updated or added any unit tests accordingly, because there's no tests right now, and I'm not sure I wanna be the first…
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by mitechie** [comment]
Thanks for this, I'm trying to look and see if this is true regardless of file system and the OS at play but I'm struggling to find the pertinent proof. Do you happen to know if this changed in a specific version of gparted we can trace across our support matrix or something?

**Comment by igalic** [comment]
according to https://wiki.freebsd.org/GrowingFilesystemsOnline this change first appeared in 10-CURRENT (the then development branch) and was merged into 9.2-RELEASE. [9.2 release notes](https://www.freebsd.org/releases/9.2R/relnotes.html) don't seem to mention it. [10.0 release notes](https://www.freebsd.org/releases/10.R/relnotes.html) don't mention it either)

- [9.2 was released on the 30th September 2013](https://www.freebsd.org/releases/9.2R/schedule.html) 
- [10.0 was released on the 20th January ](https://www.freebsd.org/releases/10.0R/schedule.html) 

the code i fixed is from 2014, so maybe it was just overly cautious?

the two currently supported releases of FreeBSD are 11.4 and 12.2

**Comment by OddBloke** [comment]
> Thanks for this, I'm trying to look and see if this is true regardless of file system and the OS at play but I'm struggling to find the pertinent proof. Do you happen to know if this changed in a specific version of gparted we can trace across our support matrix or something?

This PR relates to gpart, not gparted. gpart is FreeBSD's partition manager: https://www.freebsd.org/cgi/man.cgi?gpart(8). (Not to be confused with the `gpart` that we have in Ubuntu, which is also a different thing.) See https://github.com/canonical/cloud-init/commit/bb4131a2bd36d9e8932fdcb61432260f16159cde and https://github.com/canonical/cloud-init/blob/master/cloudinit/config/cc_growpart.py#L25.

**Comment by mitechie** [comment]
> This PR relates to gpart, not gparted. gpart is FreeBSD's partition manager: (Not to be confused with the `gpart` that we have in Ubuntu, which is also a different thing.)

oooooohhhhhhhhh yea I messed that one up. Thanks for clarifying.

**Review by mitechie — APPROVED** [review]

**Pull request merged**
