### PR TITLE
Added / fixed support for static routes on OpenBSD and FreeBSD

### PR DESCRIPTION
**Pull request by kadiron**
## Proposed Commit Message
OpenBSD: Added support for static routes
FreeBSD: Fixed creation of static routes
- Corrected syntax in usage of route(8)
- Added the needed space separated list of route names in the /etc/rc.conf-variable "static_routes"

### CODE REVIEW

**Review by igalic — COMMENTED** [review]
can we extend tests for this?

**Comment by kadiron** [comment]
> can we extend tests for this?

What are you thinking about?

**Comment by igalic** [comment]
> > can we extend tests for this?
> 
> What are you thinking about?

I'm thinking of creating a pull request on top of yours, which adds tests for these kinds of things

**Comment by TheRealFalcon** [comment]
@kadiron , thank you for the contribution! 
I noticed you signed the CLA, but haven't yet added yourself to the CLA signers file. As part of this PR, please also add your name (alphabetically) to [the CLA signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers). The full details are described in the last bullet point [of the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request).

Additionally, we need flake8 and black to be passing before we can merge. You can click the links here, or run `tox -e check_format` to run it locally. Finally, rather than `%s` formatting, we prefer using f-strings where possible. Can you update the strings to be f-strings? The content itself looks good though!

@igalic , you mentioned adding tests. Do you want me to merge this PR as-is (after fixes) and then you'd submit your PR separately? Also, can you provide your overall +1? You know the BSD stuff much better than I do.

**Comment by kadiron** [comment]
@TheRealFalcon thanks, I hope I've changed everything accordingly.

One question: OpenBSD needs to get static routes configured within the interface context, should/can that be documented somewhere?

**Comment by TheRealFalcon** [comment]
> OpenBSD needs to get static routes configured within the interface context, should/can that be documented somewhere?

Can that documentation be within the code (i.e., comments)? That's not a detail an end-user would need to know about, right?

**Comment by kadiron** [comment]
> > OpenBSD needs to get static routes configured within the interface context, should/can that be documented somewhere?
> 
> Can that documentation be within the code (i.e., comments)? That's not a detail an end-user would need to know about, right?

I'm not sure who has to know about it. A guy that's building an virtualization environment might have Linux and Windows in mind, while the "user" getting his VM just keeps going without cloud-init because it's not working completely.
However, I don't want to introduce another new failed formatting check. That said, I've just pushed the correction for the last fail. Sadly, I can't find out how to initiate these checks myself and running tox locally just gives me stacktraces.

**Comment by igalic** [comment]
a good 130+ unit tests are currently failing on FreeBSD. I reckon the situation will be similar on OpenBSD.

**Comment by igalic** [comment]
> > > OpenBSD needs to get static routes configured within the interface context, should/can that be documented somewhere?
> > 
> > 
> > Can that documentation be within the code (i.e., comments)? That's not a detail an end-user would need to know about, right?
> 
> I'm not sure who has to know about it. A guy that's building an virtualization environment might have Linux and Windows in mind, while the "user" getting his VM just keeps going without cloud-init because it's not working completely.

cloud-init does not run on Windows

> However, I don't want to introduce another new failed formatting check. That said, I've just pushed the correction for the last fail. Sadly, I can't find out how to initiate these checks myself and running tox locally just gives me stacktraces.

a good 130+ unit tests are currently failing on FreeBSD. I reckon the situation will be similar on OpenBSD.

but, formatting should just work with [black](https://pypi.org/project/black/)

**Comment by aciba90** [comment]
Thanks for signing the CLA. 

A `tox -e do_format,check_format` does not work on your side ?

**Comment by kadiron** [comment]
> A `tox -e do_format,check_format` does not work on your side ?

No, here is what it gives me on a fresh install of Debian 11.7:

cameron@marvin:~/src/github.com/kadiron/cloud-init$ tox -e do_format,check_format
GLOB sdist-make: /home/cameron/src/github.com/kadiron/cloud-init/setup.py
ERROR: invocation failed (exit code 1), logfile: /home/cameron/src/github.com/kadiron/cloud-init/.tox/log/GLOB-0.log
============================================================ log start =============================================================
Traceback (most recent call last):
  File "/home/cameron/src/github.com/kadiron/cloud-init/tools/read-version", line 94, in <module>
    version = tiny_p(cmd).strip()
  File "/home/cameron/src/github.com/kadiron/cloud-init/tools/read-version", line 16, in tiny_p
    return subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', 'main']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/cameron/src/github.com/kadiron/cloud-init/setup.py", line 337, in <module>
    version=get_version(),
  File "/home/cameron/src/github.com/kadiron/cloud-init/setup.py", line 78, in get_version
    ver = subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/read-version']' returned non-zero exit status 1.

============================================================= log end ==============================================================
ERROR: FAIL could not package project - v = InvocationError('/usr/bin/python3 setup.py sdist --formats=zip --dist-dir /home/cameron/src/github.com/kadiron/cloud-init/.tox/dist', 1)

**Comment by aciba90** [comment]
@kadiron, what is the output of `git describe main` ?

It looks like `tools/read-version` is not able to get the current cloud-init's tag/version. See: https://github.com/canonical/cloud-init/blob/e0a96d78c7c94c735cbf03f93b06134136b9b922/tools/read-version#L94

**Comment by kadiron** [comment]
> git describe main

Thanks @aciba90 for getting into this! I'm just getting an "fatal: No names found" inside my fork. I'm not familiar with the workflow here or anywhere else on github.com... looks like I have to create an release inside my fork and tag that for getting this to work?
Anyways, I have copied my updated openbsd.py into a clone of canonical/cloud-init and ran tox there, which reformatted the file. Copied that back into my tree and pushed that now.

**Comment by aciba90** [comment]
> > git describe main
> 
> Thanks @aciba90 for getting into this! I'm just getting an "fatal: No names found" inside my fork. I'm not familiar with the workflow here or anywhere else on github.com... looks like I have to create an release inside my fork and tag that for getting this to work? Anyways, I have copied my updated openbsd.py into a clone of canonical/cloud-init and ran tox there, which reformatted the file. Copied that back into my tree and pushed that now.

The typical workflow is explained here: https://canonical-cloud-init.readthedocs-hosted.com/en/latest/development/contributing.html#the-detailed-instructions

Assuming your remote is not named as `upstream`, the following would fetch the tags and presumably fix the issue:

```
git remote add upstream git@github.com:canonical/cloud-init.git
git fetch upstream --tags
```

**Comment by TheRealFalcon** [comment]
@igalic are you +1 on this?

**Comment by igalic** [comment]
> @igalic are you +1 on this?

yes, +1 from me

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Pull request merged**
