### PR TITLE
fix: move DS VMware to be in front of DS OVF

### PR DESCRIPTION
**Pull request by PengpengSun**
## Proposed Commit Message

```
fix: move DS VMware to be in front of DS OVF

This commit is changing the sequence of data transports on VMware platform to: 
EnvVars (VMware)
GuestInfo (VMware)
customization cfg (VMware)
local seed_dir (OVF)
guestinfo.ovfEnv (OVF)
ISO cdrom (OVF)

Before PR 1573 change, if both an ovf xml and metadata/userdata from customization cfg(imc) are available,
metadata/userdata from customization will be loaded firstly, so this commit actually reverts to previous
behavior on VMware platform.

For the other rpctool data transports (EnvVars, GuestInfo) in VMware DS, they must be configured
intentionally on VMware VM, not like pre-existing OVF properties in ova/ovf template.

Fixes GH-4030
LP: #1992509
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
Thanks @PengpengSun . This LGTM! Note that in Ubuntu, we also have a [separate datasource list](https://github.com/canonical/cloud-init/blob/ubuntu/devel/debian/cloud-init-base.templates) that is used on package install, and so these will need to be updated there as well.

I'm assuming that is something you want done?

**Comment by PengpengSun** [comment]
Thanks @TheRealFalcon. And Yes, I want this [separate datasource list](https://github.com/canonical/cloud-init/blob/ubuntu/devel/debian/cloud-init-base.templates) get updated too, will create a PR soon.

**Comment by solarpp** [comment]
Hi @TheRealFalcon , about updating this [separate datasource list](https://github.com/canonical/cloud-init/blob/ubuntu/devel/debian/cloud-init-base.templates), I don't find where to do so, would you please help to conduct it?

**Comment by PengpengSun** [comment]
> Thanks @TheRealFalcon. And Yes, please help to update this [separate datasource list](https://github.com/canonical/cloud-init/blob/ubuntu/devel/debian/cloud-init-base.templates) too.
> 
> For "VMware: reads data from guestinfo table or env vars", could you please update it to "VMware: reads data from guestinfo table or guest customization configuration or env vars".

Hi @TheRealFalcon , about updating this [separate datasource list](https://github.com/canonical/cloud-init/blob/ubuntu/devel/debian/cloud-init-base.templates), I don't find where to do so, would you please help to conduct it?

**Comment by TheRealFalcon** [comment]
@PengpengSun , I put up a PR at https://github.com/canonical/cloud-init/pull/5950 . When that one merges I can put up similar PRs for the other downstream branches.

**Pull request merged**
