### PR TITLE
Support reboot on SUSE distros on package install/update/upgrade

### PR DESCRIPTION
**Pull request by rjschwei**
On SUSE distributions the reboot marker file is written as /run/reboot-needed. Recognize this as an additional indicator that a reboot is needed on package update/upgrade.

## Proposed Commit Message

feat(SUSE): On SUSE distributions the reboot marker file is written as /run/reboot-needed. Recognize this as an additional indicator that a reboot is needed on package update/upgrade.

## Checklist

- [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
LGTM, would be nice to have a unit test on this in  tests/unittests/config/test_cc_package_update_upgrade_install.py. I can draw one up next week if needed

**Comment by blackboxsw** [comment]
@rjschwei I've added a commit with some unittest coverage here. If that all looks good we can merge this.

**Review by blackboxsw — APPROVED** [review]
Will await a +1 from @rjschwei on this before merging

**Comment by rjschwei** [comment]
@blackboxsw LGTM, thanks for adding the tests, much appreciated.

**Pull request merged**
