### PR TITLE
Ubuntu/bionic

### PR DESCRIPTION
**Pull request by blackboxsw**
Correct previous squash merge. We should never squash merge to ubuntu/<series> branches as it create merge conflicts in daily recipes. I had "fat-fingered" squash merge through the github UI instead of git pushing the approved PR upstream from the command line. 

The only changes approved on the ubuntu/bionic branch were #1203 and #1220. But 1203 was accidentally squashed.

resolve this by checking out the approve branch for #1203 and add the LXD datasource commit from #1220
```bash
git remote add holmanb git@github.com:holmanb/cloud-init.git
git checkout holmanb/ubuntu/bionic-fix-patches   # Approved branch from #1203
git cherry-pick 2c2ddb36843a55edde1790fa94b005231f0ffcf2  # Approved commit from #1220 
```

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
`git diff blackboxsw/ubuntu/bionic upstream/ubuntu/bionic` is clean. +1 and thanks for jumping on this so quick.

**Comment by holmanb** [comment]
LGTM

**Comment by blackboxsw** [comment]
* git diff upstream/ubuntu/bionic  no diff
* build recipe is based on revno which is number of commits beyond upstream annotated version, so won't break bionic recipe build (which is already  broken)

* build-package/sbuild successful no new lints and package builds
```bash
Status: successful
Version: 21.4-82-g0d364a29-0ubuntu1~18.04.1
--------------------------------------------------------------------------------
Finished at 2022-02-03T22:53:50Z
Build needed 00:02:50, 19044k disk space
```
* manual merge into main for recipe build procedure works without mege conflicts.
```bash
git checkout upstream/main
git merge cs/ubuntu/bionic
quilt push -a 
tox -e py3
quilt pop -a
# Success no errors
```

**Comment by blackboxsw** [comment]
Also known expected black/isort issues in debian/apport-launcher.py which we can sort separately (and existed before any of these merges took place)

**Pull request merged**
