### PR TITLE
readme: Alpine Linux is now supported

### PR DESCRIPTION
**Pull request by oxr463**
Add Alpine Linux in the list of supported Operating System.

### CODE REVIEW

**Comment by igalic** [comment]
https://github.com/canonical/cloud-init/tree/master/cloudinit/distros ⬅️ there isn't an alpine distro here, so how, exactly, is it supported?

**Comment by oxr463** [comment]
> 
> 
> https://github.com/canonical/cloud-init/tree/master/cloudinit/distros ⬅️ there isn't an alpine distro here, so how, exactly, is it supported?

Apologies. Looks like it was not submitted upstream properly [[1]]. Let me fix that.

[1]: https://git.alpinelinux.org/aports/tree/testing/cloud-init/alpine.py

**Comment by dermotbradley** [comment]
Hi

I'm the person who just released an updated Alpine cloud-init package for version 20.2 and expanded its functionality for more cloud-init modules.

I have **recently signed the cloud-init CLA** and fully intend to upstream Alpine support into upstream. **Please give me the time to submit these changes in an organised fashion** - the patches I prepared for 20.2 will need to modified for cloud-init master.

**Comment by oxr463** [comment]
> Hi
> 
> I'm the person who just released an updated Alpine cloud-init package for version 20.2, took over the Alpine maintainership for cloud-init, and expanded the Alpine functionality to more cloud-init modules.
> 
> I have **recently signed the cloud-init CLA** and fully intend to upstream Alpine support into upstream. **Please give me the time to submit these changes in an organised fashion** - the patches I prepared for 20.2 will need to modified for cloud-init master.

Please open a PR when you're ready, and we can close this in favor of that.

**Comment by OddBloke** [comment]
Thanks @dermotbradley, we look forward to those submissions! If you need any assistance, you can use the avenues listed [here](https://cloudinit.readthedocs.io/en/latest/topics/code_review.html#asking-for-help) to find us; please don't hesitate!

(As this PR won't land, I'm going to close it out.)

**Comment by dermotbradley** [comment]
@oxr463 Alpine support (including documentation references) has just been merged and cloud-init 20.3 is due for release later today which will include this.

I will be updating the Alpine cloud-init packages in the next day or so from 20.2 to 20.3. All the Alpine packages that cloud-init depends on are now in either main or community, rather than testing, and so I also expect to move the cloud-init packages themselves from testing to community in time for them to be included in the Alpine 3.13 release (rather than only in Edge as they are currently).

**Pull request closed without merging**
