### PR TITLE
fix: bump azure key size to 3072

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

```
fix: bump azure key size to 3072

For post 2030 FIPS 140-3 compliance for key size transition as per NIST SP 800-131A Rev. 2
and NIST SP 800-57 Part 1 Rev. 5. 

Per @xnox.
```

## Additional Context
SRU Everywhere please :)
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf
https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-57pt1r5.pdf

Per @xnox
## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by xnox — CHANGES_REQUESTED** [review]
In presubmit tests I do not see this change deployed in an azure image, across every Ubuntu release and azure instance types on x86-64 and arm64.

Please ensure successful launch, certificate issued, and encrypted authentication working in Azure.

**Prior** to merging this PR in mainline.

**Comment by xnox** [comment]
Can we tag someone from Azure to review this?

**Comment by TheRealFalcon** [comment]
cc @cjp256

**Comment by cjp256** [comment]
Tested fine, thanks!

**Review by cjp256 — APPROVED** [review]
Testing looks good, thanks!

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Review by xnox — APPROVED** [review]

**Pull request merged**
