### PR TITLE
tox: add link checker environment, fix some links (SC-1087)

### PR DESCRIPTION
**Pull request by holmanb**
The linkchecker currently works as-is, but running it shows broken links I'd like to fix as well in this PR.

```
tox: add link checker environment, fix some links
```

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Am I doing something wrong? I checked out the branch and see a handful of errors and it hangs after the last line
```
(cloud-init36) newt:cloud-init (pr_tox) $ tox -e linkcheck   
GLOB sdist-make: /home/james/c/cloud-init/setup.py
linkcheck inst-nodeps: /home/james/c/cloud-init/.tox/.tmp/package/1/cloud-init-22.2.zip
linkcheck installed: alabaster==0.7.12,attrs==21.4.0,Babel==2.10.1,certifi==2022.5.18.1,charset-normalizer==2.0.12,cloud-init @ file:///home/james/c/cloud-init/.tox/.tmp/package/1/cloud-init-22.2.zip,configobj==5.0.6,doc8==0.11.2,docutils==0.16,idna==3.3,imagesize==1.3.0,importlib-metadata==4.8.3,importlib-resources==3.0.0,Jinja2==3.0.3,jsonpatch==1.32,jsonpointer==2.3,jsonschema==3.2.0,m2r2==0.3.2,MarkupSafe==2.0.1,mistune==0.8.4,netifaces==0.11.0,oauthlib==3.2.0,packaging==21.3,pbr==5.9.0,Pygments==2.12.0,pyparsing==3.0.9,pyrsistent==0.18.0,pyserial==3.5,pytz==2022.1,PyYAML==6.0,requests==2.27.1,restructuredtext-lint==1.4.0,six==1.16.0,snowballstemmer==2.2.0,Sphinx==4.3.0,sphinx-panels==0.6.0,sphinx-rtd-theme==1.0.0,sphinxcontrib-applehelp==1.0.2,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.0,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5,stevedore==3.5.0,typing_extensions==4.1.1,urllib3==1.26.9,zipp==3.6.0
linkcheck run-test-pre: PYTHONHASHSEED='146916035'
linkcheck run-test: commands[0] | /home/james/c/cloud-init/.tox/linkcheck/bin/python -m sphinx -b linkcheck doc/rtd doc/rtd_html
Running Sphinx v4.3.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [linkcheck]: targets for 55 source files that are out of date
updating environment: [new config] 55 added, 0 changed, 0 removed
reading sources... [  1%] index
reading sources... [  3%] topics/analyze
reading sources... [  5%] topics/availability
reading sources... [  7%] topics/boot
reading sources... [  9%] topics/bugs
reading sources... [ 10%] topics/cli
reading sources... [ 12%] topics/code_review
reading sources... [ 14%] topics/contributing
reading sources... [ 16%] topics/datasources
reading sources... [ 18%] topics/datasources/aliyun
reading sources... [ 20%] topics/datasources/altcloud
reading sources... [ 21%] topics/datasources/azure
reading sources... [ 23%] topics/datasources/cloudsigma
reading sources... [ 25%] topics/datasources/cloudstack
reading sources... [ 27%] topics/datasources/configdrive
reading sources... [ 29%] topics/datasources/digitalocean
reading sources... [ 30%] topics/datasources/e24cloud
reading sources... [ 32%] topics/datasources/ec2
reading sources... [ 34%] topics/datasources/exoscale
reading sources... [ 36%] topics/datasources/fallback
reading sources... [ 38%] topics/datasources/gce
reading sources... [ 40%] topics/datasources/lxd
reading sources... [ 41%] topics/datasources/maas
reading sources... [ 43%] topics/datasources/nocloud
reading sources... [ 45%] topics/datasources/opennebula
reading sources... [ 47%] topics/datasources/openstack
reading sources... [ 49%] topics/datasources/oracle
reading sources... [ 50%] topics/datasources/ovf
reading sources... [ 52%] topics/datasources/rbxcloud
reading sources... [ 54%] topics/datasources/smartos
reading sources... [ 56%] topics/datasources/upcloud
reading sources... [ 58%] topics/datasources/vmware
reading sources... [ 60%] topics/datasources/vultr
reading sources... [ 61%] topics/datasources/zstack
reading sources... [ 63%] topics/debugging
reading sources... [ 65%] topics/dir_layout
reading sources... [ 67%] topics/docs
reading sources... [ 69%] topics/events
reading sources... [ 70%] topics/examples
reading sources... [ 72%] topics/faq
reading sources... [ 74%] topics/format
reading sources... [ 76%] topics/instancedata
reading sources... [ 78%] topics/integration_tests
reading sources... [ 80%] topics/logging
reading sources... [ 81%] topics/merging
reading sources... [ 83%] topics/module_creation
reading sources... [ 85%] topics/modules
reading sources... [ 87%] topics/network-config
reading sources... [ 89%] topics/network-config-format-eni
reading sources... [ 90%] topics/network-config-format-v1
reading sources... [ 92%] topics/network-config-format-v2
reading sources... [ 94%] topics/security
reading sources... [ 96%] topics/testing
reading sources... [ 98%] topics/tutorial
reading sources... [100%] topics/vendordata

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] index
writing output... [  3%] topics/analyze
writing output... [  5%] topics/availability
writing output... [  7%] topics/boot
writing output... [  9%] topics/bugs
writing output... [ 10%] topics/cli
writing output... [ 12%] topics/code_review
writing output... [ 14%] topics/contributing
writing output... [ 16%] topics/datasources
writing output... [ 18%] topics/datasources/aliyun
writing output... [ 20%] topics/datasources/altcloud
writing output... [ 21%] topics/datasources/azure
writing output... [ 23%] topics/datasources/cloudsigma
writing output... [ 25%] topics/datasources/cloudstack
writing output... [ 27%] topics/datasources/configdrive
writing output... [ 29%] topics/datasources/digitalocean
writing output... [ 30%] topics/datasources/e24cloud
writing output... [ 32%] topics/datasources/ec2
writing output... [ 34%] topics/datasources/exoscale
writing output... [ 36%] topics/datasources/fallback
writing output... [ 38%] topics/datasources/gce
writing output... [ 40%] topics/datasources/lxd
writing output... [ 41%] topics/datasources/maas
writing output... [ 43%] topics/datasources/nocloud
writing output... [ 45%] topics/datasources/opennebula
writing output... [ 47%] topics/datasources/openstack
writing output... [ 49%] topics/datasources/oracle
writing output... [ 50%] topics/datasources/ovf
writing output... [ 52%] topics/datasources/rbxcloud
writing output... [ 54%] topics/datasources/smartos
writing output... [ 56%] topics/datasources/upcloud
writing output... [ 58%] topics/datasources/vmware
writing output... [ 60%] topics/datasources/vultr
writing output... [ 61%] topics/datasources/zstack
writing output... [ 63%] topics/debugging
writing output... [ 65%] topics/dir_layout
writing output... [ 67%] topics/docs
writing output... [ 69%] topics/events
writing output... [ 70%] topics/examples
writing output... [ 72%] topics/faq
writing output... [ 74%] topics/format
writing output... [ 76%] topics/instancedata
writing output... [ 78%] topics/integration_tests
writing output... [ 80%] topics/logging
writing output... [ 81%] topics/merging
writing output... [ 83%] topics/module_creation
writing output... [ 85%] topics/modules
writing output... [ 87%] topics/network-config
writing output... [ 89%] topics/network-config-format-eni
writing output... [ 90%] topics/network-config-format-v1
writing output... [ 92%] topics/network-config-format-v2
writing output... [ 94%] topics/security
writing output... [ 96%] topics/testing
writing output... [ 98%] topics/tutorial
writing output... [100%] topics/vendordata


(topics/datasources/vmware: line  351) broken    ../network-config-format-v1.html - 
(topics/datasources/vmware: line  351) broken    ../network-config-format-v2.html - 
(topics/datasources/vmware: line   54) broken    ../instancedata.html#using-instance-data - 
(topics/datasources/vmware: line  268) broken    ../boot.html#first-boot-determination - 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/james/.pyenv/versions/3.6.10/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/james/c/cloud-init/.tox/linkcheck/lib/python3.6/site-packages/sphinx/builders/linkcheck.py", line 571, in run
    netloc = urlparse(uri).netloc
  File "/home/james/.pyenv/versions/3.6.10/lib/python3.6/urllib/parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/home/james/.pyenv/versions/3.6.10/lib/python3.6/urllib/parse.py", line 436, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

(topics/datasources/ec2: line   89) broken    http://169.254.169.254 - HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb620984e48>: Failed to establish a new connection: [Errno 113] No route to host',))
(topics/datasources/cloudsigma: line   22) redirect  http://cloudinit.readthedocs.org/en/latest/topics/format.html - with Found to https://cloudinit.readthedocs.io/en/latest/topics/format.html
(topics/datasources/cloudsigma: line   22) redirect  http://cloudsigma-docs.readthedocs.org/en/latest/meta.html - with Found to https://docs.cloudsigma.com/en/latest/meta.html
(topics/datasources/cloudsigma: line    6) redirect  http://cloudsigma-docs.readthedocs.org/en/latest/server_context.html - with Found to https://docs.cloudsigma.com/en/latest/server_context.html
(      topics/faq: line  330) broken    http://brandon.fuller.name/archives/2011/05/02/06.40.57/ - HTTPConnectionPool(host='brandon.fuller.name', port=80): Max retries exceeded with url: /archives/2011/05/02/06.40.57/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb620a3c6d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
(topics/datasources/cloudstack: line    6) redirect  http://cloudstack.apache.org/ - permanently to https://cloudstack.apache.org/
(topics/datasources/altcloud: line   44) redirect  http://deltacloud.apache.org - permanently to https://deltacloud.apache.org/
(topics/datasources/digitalocean: line    6) redirect  http://digitalocean.com/ - permanently to https://www.digitalocean.com/
(topics/datasources/cloudstack: line    6) ok        http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/latest/virtual_machines.html#user-data-and-meta-data
(topics/datasources/cloudsigma: line    6) redirect  http://cloudsigma.com/ - permanently to https://www.cloudsigma.com/
(   topics/format: line  203) ok        http://foss-boss.blogspot.com/2011/01/advanced-cloud-init-custom-handlers.html
(topics/datasources/ec2: line   89) broken    http://instance-data:8773 - HTTPConnectionPool(host='instance-data', port=8773): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb620d79470>: Failed to establish a new connection: [Errno -2] Name or service not known',))
(topics/network-config-format-eni: line   15) ok        http://manpages.ubuntu.com/manpages/trusty/en/man5/interfaces.5.html
(topics/datasources/opennebula: line    6) redirect  http://opennebula.org/ - with Found to https://opennebula.io/
(topics/datasources/opennebula: line    8) redirect  http://opennebula.org/documentation:documentation:cong - permanently to https://archives.opennebula.org/documentation:rel4.4:cong
(topics/datasources/opennebula: line    8) redirect  http://opennebula.org/documentation:documentation:cong#network_configuration - permanently to https://archives.opennebula.org/documentation:rel4.4:cong#network_configuration
(topics/datasources/smartos: line    9) redirect  http://smartos.org/ - permanently to https://www.tritondatacenter.com/smartos
(topics/datasources/opennebula: line    8) redirect  http://opennebula.org/documentation:documentation:context_overview - permanently to https://archives.opennebula.org/documentation:rel4.4:context_overview
( topics/examples: line   38) redirect  http://www.chef.io/chef/ - permanently to https://www.chef.io/products/chef-infra
(topics/datasources/configdrive: line    6) redirect  http://www.openstack.org/ - permanently to https://www.openstack.org/
(      topics/faq: line  331) redirect  http://www.youtube.com/watch?v=-zL3BdbKyGY - permanently to https://www.youtube.com/watch?v=-zL3BdbKyGY
(topics/datasources/rbxcloud: line    6) ok        http://www.hyperone.com/
(      topics/faq: line  328) broken    https://annex.debconf.org/debconf-share/debconf17/slides/164-cloud-init_Building_clouds_one_Linux_box_at_a_time.pdf - HTTPSConnectionPool(host='annex.debconf.org', port=443): Max retries exceeded with url: /debconf-share/debconf17/slides/164-cloud-init_Building_clouds_one_Linux_box_at_a_time.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb620991710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
(     topics/bugs: line   94) ok        https://bugs.archlinux.org/
(     topics/bugs: line   75) ok        https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=cloud-init;dist=unstable
(           index: line   27) redirect  https://bugs.launchpad.net/cloud-init/+filebug - with See Other to https://bugs.launchpad.net/cloud-init/+filebug/+login
(   topics/events: line   74) ok        https://bugs.launchpad.net/cloud-init/+bug/1936229
(     topics/boot: line  237) ok        https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1879530
(     topics/bugs: line   68) redirect  https://bugs.launchpad.net/ubuntu/+source/cloud-init/+filebug - with See Other to https://bugs.launchpad.net/ubuntu/+source/cloud-init/+filebug/+login
(     topics/boot: line  232) ok        https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1885527
(     topics/bugs: line   82) ok        https://bugzilla.redhat.com/
(     topics/bugs: line   88) ok        https://bugzilla.suse.com/index.cgi
(topics/datasources/oracle: line    6) ok        https://cloud.oracle.com/
(topics/contributing: line   80) ok        https://cloudinit.readthedocs.io/en/latest/topics/code_review.html
(topics/contributing: line   21) ok        https://cloudinit.readthedocs.io/en/latest/topics/integration_tests.html
( topics/tutorial: line   49) ok        https://cloudinit.readthedocs.io/en/latest/topics/modules.html#runcmd
(topics/contributing: line   20) ok        https://cloudinit.readthedocs.io/en/latest/topics/testing.html
(topics/datasources/gce: line    6) redirect  https://cloud.google.com/compute/docs/storing-retrieving-metadata - permanently to https://cloud.google.com/compute/docs/metadata/overview
(topics/network-config: line  144) redirect  https://developers.digitalocean.com/documentation/metadata/ - permanently to https://docs.digitalocean.com/documentation/metadata/
(topics/datasources/digitalocean: line    6) redirect  https://developers.digitalocean.com/metadata/ - permanently to https://docs.digitalocean.com/documentation/metadata/
(topics/datasources/upcloud: line    6) ok        https://developers.upcloud.com/1.3/8-servers/#metadata-service
(topics/datasources/azure: line   17) ok        https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service
(topics/datasources/ec2: line   51) ok        https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#work-with-tags-in-IMDS
(topics/datasources/openstack: line    6) ok        https://docs.openstack.org/nova/latest/admin/metadata-service.html
(topics/datasources/configdrive: line    9) ok        https://docs.openstack.org/nova/latest/admin/config-drive.html
(topics/datasources/configdrive: line    9) ok        https://docs.openstack.org/nova/latest/user/metadata.html#config-drives
(  topics/testing: line   13) redirect  https://docs.pytest.org/ - with Found to https://docs.pytest.org/en/7.1.x/
(  topics/testing: line   56) redirect  https://docs.pytest.org/en/latest/assert.html - with Found to https://docs.pytest.org/en/latest/how-to/assert.html
(  topics/modules: line   12) redirect  https://docs.puppet.com/puppet/4.2/reference/whered_it_go.html - permanently to https://github.com/puppetlabs/docs-archive/tree/main/puppet/4.2
(  topics/testing: line   53) redirect  https://docs.pytest.org/en/latest/fixture.html - with Found to https://docs.pytest.org/en/latest/explanation/fixtures.html
(  topics/testing: line   91) ok        https://docs.python.org/3.8/library/unittest.mock.html#autospeccing
(  topics/logging: line  135) ok        https://docs.python.org/3/library/logging.config.html#configuration-file-format
(  topics/logging: line   82) ok        https://docs.python.org/3/library/logging.handlers.html
(  topics/logging: line   91) ok        https://docs.python.org/3/library/logging.html#formatter-objects
(topics/datasources/configdrive: line   28) ok        https://en.wikipedia.org/wiki/File_Allocation_Table
(topics/datasources/ovf: line   44) ok        https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-9A5093A5-C54F-4502-941B-3F9C0F573A39.html
(topics/datasources/configdrive: line   62) ok        https://en.wikipedia.org/wiki/ISO_9660
(topics/datasources/ovf: line    6) ok        https://en.wikipedia.org/wiki/Open_Virtualization_Format
(topics/network-config: line  163) ok        https://eng.joyent.com/mdata/datadict.html
(      topics/faq: line  325) redirect  https://events.linuxfoundation.org/wp-content/uploads/2017/12/cloud-init-The-cross-cloud-Magic-Sauce-Scott-Moser-Chad-Smith-Canonical.pdf - permanently to https://events19.linuxfoundation.org/wp-content/uploads/2017/12/cloud-init-The-cross-cloud-Magic-Sauce-Scott-Moser-Chad-Smith-Canonical.pdf
(topics/datasources/exoscale: line    6) redirect  https://exoscale.com - permanently to https://www.exoscale.com/
(  topics/modules: line   11) redirect  https://fedorahosted.org/spacewalk/ - with Found to https://github.com/spacewalkproject/spacewalk
(topics/contributing: line    4) ok        https://github.com
(topics/contributing: line   69) ok        https://github.com/canonical/cloud-init
(topics/module_creation: line   69) ok        https://github.com/canonical/cloud-init/blob/3bcffacb216d683241cf955e4f7f3e89431c1491/cloudinit/config/schema.py#L58
(topics/module_creation: line   73) ok        https://github.com/canonical/cloud-init/blob/3bcffacb216d683241cf955e4f7f3e89431c1491/cloudinit/distros/__init__.py#L35
(  topics/testing: line   34) ok        https://github.com/canonical/cloud-init/blob/42f69f410ab8850c02b1f53dd67c132aa8ef64f5/cloudinit/distros/tests/test_init.py#L15
(topics/integration_tests: line  149) broken    https://github.com/canonical/cloud-init/blob/af7eb1deab12c7208853c5d18b55228e0ba29c4d/tests/integration_tests/conftest.py#L220-L224 - Anchor 'L220-L224' not found
(topics/integration_tests: line  163) ok        https://github.com/canonical/cloud-init/blob/af7eb1deab12c7208853c5d18b55228e0ba29c4d/tests/integration_tests/clouds.py#L102
(topics/module_creation: line   96) ok        https://github.com/canonical/cloud-init/blob/b4746b6aed7660510071395e70b2d6233fbdc3ab/config/cloud.cfg.tmpl#L144
(topics/module_creation: line   96) ok        https://github.com/canonical/cloud-init/blob/b4746b6aed7660510071395e70b2d6233fbdc3ab/config/cloud.cfg.tmpl#L101
(topics/module_creation: line   96) ok        https://github.com/canonical/cloud-init/blob/b4746b6aed7660510071395e70b2d6233fbdc3ab/config/cloud.cfg.tmpl#L70
(  topics/testing: line   34) ok        https://github.com/canonical/cloud-init/blob/fbcb224bc12495ba200ab107246349d802c5d8e6/cloudinit/tests/test_subp.py#L20
(   topics/format: line  108) ok        https://github.com/canonical/cloud-init/blob/main/cloudinit/cmd/devel/make_mime.py
(topics/module_creation: line   67) ok        https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/versions.schema.cloud-config.json
(topics/module_creation: line  103) ok        https://github.com/canonical/cloud-init/blob/main/config/cloud.cfg.tmpl
(topics/integration_tests: line   45) ok        https://github.com/canonical/cloud-init/blob/main/tests/integration_tests/integration_settings.py
(topics/contributing: line   17) ok        https://github.com/canonical/cloud-init/blob/main/tools/.github-cla-signers
(topics/datasources/ovf: line   42) ok        https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/helpers/vmware/imc/config.py
(      topics/faq: line  139) ok        https://github.com/canonical/cloud-init/blob/main/tools/validate-yaml.py
(topics/contributing: line   87) ok        https://github.com/canonical/cloud-init/pull/344
(topics/code_review: line   88) ok        https://github.com/canonical/cloud-init/pull/237
(      topics/faq: line  267) ok        https://github.com/canonical/cloud-utils/
(  topics/modules: line   50) ok        https://github.com/openssh/openssh-portable/blob/master/sshkey.c
(topics/contributing: line   87) ok        https://github.com/canonical/cloud-init/pull/345
(topics/datasources/vmware: line  243) redirect  https://github.com/vmware/govmomi/blob/master/govc - permanently to https://github.com/vmware/govmomi/tree/master/govc
(     topics/bugs: line   39) ok        https://help.launchpad.net/YourAccount/NewAccount
(topics/datasources/vmware: line   10) ok        https://github.com/vmware/govmomi/blob/master/govc/USAGE.md
(topics/debugging: line  260) ok        https://kiwiirc.com/nextclient/irc.libera.chat/cloud-init
(topics/contributing: line  107) ok        https://launchpad.net
(topics/contributing: line   37) redirect  https://launchpad.net/%7Econtributor-agreement-canonical/+members - with unknown code to https://launchpad.net/~contributor-agreement-canonical/+members
(  topics/modules: line   13) ok        https://launchpad.net/cloud-initramfs-tools
(   topics/events: line   10) ok        https://launchpad.net/cloud-init
(      topics/faq: line  212) ok        https://linuxcontainers.org/
( topics/tutorial: line    6) ok        https://linuxcontainers.org/lxd/
(      topics/faq: line  256) ok        https://linuxcontainers.org/lxd/docs/master/cloud-init
(topics/datasources/lxd: line    6) ok        https://linuxcontainers.org/lxd/docs/master/dev-lxd
(      topics/faq: line  256) ok        https://linuxcontainers.org/lxd/docs/master/instances
(           index: line   26) ok        https://launchpad.net/~cloud-init
( topics/tutorial: line   24) ok        https://linuxcontainers.org/lxd/getting-started-cli/#other-installation-options
( topics/security: line   57) ok        https://lists.launchpad.net/cloud-init/
(topics/datasources/maas: line    8) ok        https://maas.io/docs
(      topics/faq: line  188) ok        https://multipass.run/
(topics/network-config-format-v2: line    6) ok        https://netplan.io
(topics/network-config: line  193) ok        https://networkmanager.dev
(topics/network-config: line  207) ok        https://netplan.io/
(      topics/faq: line  324) ok        https://powersj.io/post/cloud-init-summit18/
(      topics/faq: line  326) ok        https://powersj.io/post/cloud-init-summit17/
(      topics/faq: line  321) ok        https://powersj.io/post/cloud-init-summit19/
(  topics/modules: line   70) redirect  https://puppet.com/docs/puppet/latest/config_file_csr_attributes.html - permanently to https://puppet.com/docs/puppet/7/config_file_csr_attributes.html
(topics/integration_tests: line   59) ok        https://pycloudlib.readthedocs.io/en/latest/configuration.html#configuration
(topics/integration_tests: line   59) ok        https://pycloudlib.readthedocs.io/en/latest/index.html
(topics/network-config: line  139) ok        https://specs.openstack.org/openstack/nova-specs/specs/liberty/implemented/metadata-service-network-info.html
(topics/network-config-format-v1: line  430) redirect  https://tools.ietf.org/html/rfc4862 - with Found to https://datatracker.ietf.org/doc/html/rfc4862
(topics/contributing: line   23) redirect  https://tox.readthedocs.io/en/latest/ - with Found to https://tox.wiki/en/latest/
(  topics/modules: line   29) ok        https://ubuntu.com/advantage
(      topics/faq: line  323) ok        https://ubuntu.com/blog/cloud-instance-initialisation-with-cloud-init
(topics/datasources/rbxcloud: line    6) redirect  https://rootbox.com/ - with Found to https://www.rootbox.com/
(topics/contributing: line   16) ok        https://ubuntu.com/legal/contributors
(topics/datasources/upcloud: line    6) ok        https://upcloud.com/
(      topics/faq: line  322) ok        https://ubuntu.com/engage/azure-cloud-init-whitepaper
(topics/datasources/upcloud: line    6) redirect  https://upcloud.com/community/tutorials/upcloud-metadata-service/ - permanently to https://upcloud.com/resources/tutorials/upcloud-metadata-service/
(topics/datasources/vmware: line   20) ok        https://vdc-repo.vmware.com/vmwb-repository/dcr-public/723e7f8b-4f21-448b-a830-5f22fd931b01/5a8257bd-7f41-4423-9a73-03307535bd42/doc/vim.vm.ConfigInfo.html
(topics/debugging: line  173) ok        https://wiki.ubuntu.com/CloudinitUpdates
(     topics/bugs: line   94) redirect  https://wiki.archlinux.org/index.php/Bug_reporting_guidelines - permanently to https://wiki.archlinux.org/title/Bug_reporting_guidelines
(topics/datasources/aliyun: line   10) redirect  https://www.alibabacloud.com/help/zh/faq-detail/49122.htm - with Found to https://www.alibabacloud.com/help/zh/elastic-compute-service/latest/overview-of-ecs-instance-metadata
(     topics/bugs: line   75) ok        https://www.debian.org/Bugs/Reporting
(topics/datasources/e24cloud: line    5) ok        https://www.e24cloud.com/en/
(     topics/boot: line   19) ok        https://www.freedesktop.org/software/systemd/man/systemd.generator.html
(topics/contributing: line  235) redirect  https://www.python.org/dev/peps/pep-0484/ - with Found to https://peps.python.org/pep-0484/
(topics/contributing: line  235) redirect  https://www.python.org/dev/peps/pep-0526/ - with Found to https://peps.python.org/pep-0526/
(topics/datasources/altcloud: line    6) redirect  https://www.redhat.com/virtualization/rhev/desktop/rhevm/ - permanently to https://www.redhat.com/en/technologies/virtualization/enterprise-virtualization
(topics/datasources/altcloud: line    6) redirect  https://www.vmware.com/products/datacenter-virtualization/vsphere/overview.html - permanently to https://www.vmware.com/products/vsphere.html
(topics/datasources/vultr: line    6) ok        https://www.vultr.com/
(topics/datasources/vultr: line    6) ok        https://www.vultr.com/metadata/
(      topics/faq: line  327) ok        https://www.youtube.com/watch?v=1joQfUZQcPg
(topics/debugging: line  170) ok        https://wiki.ubuntu.com/StableReleaseUpdates
(      topics/faq: line  320) ok        https://www.youtube.com/watch?v=2_m6EUo6VOI
(      topics/faq: line  329) ok        https://www.youtube.com/watch?v=RHVhIWifVqU
(topics/network-config-format-v1: line   70) ok        https://yaml.org/type/int.html
(topics/datasources/zstack: line    5) broken    https://www.zstack.io - HTTPSConnectionPool(host='www.zstack.io', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Comment by holmanb** [comment]
> Am I doing something wrong? I checked out the branch and see a handful of errors and it hangs after the last line

I should have documented the limitations, sorry. It does eventually time out.

It looks like we could maybe add [some configs](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder)

Given the nature of the internet I don't think this is something we want in a CI loop (unless the test is permissive of failure), so in my mind automating away the noise doesn't have much value.

My intended use case is:
```
1. tox -e linkcheck | grep broken
2. coffee break
3. manually verify the list of broken links, mostly false positives
```

Since this is something I expect to be occur once per release or every other release, I didn't want to sink much time into it.

Thoughts?

**Review by TheRealFalcon — APPROVED** [review]
Sounds good to me!

**Comment by holmanb** [comment]
> Sounds good to me!

Thanks. I'll add a comment before merging.

**Pull request merged**
