### PR TITLE
distro: add FreeBSD code path for eject

### PR DESCRIPTION
**Pull request by igalic**
## Proposed Commit Message

```
distro: add eject FreeBSD code path

OpenBSD, and NetBSD both have an eject(1), so they should be covered in
the default code path.

FreeBSD and Dragonfly however, do not have eject in base. Here, eject is
an (unmaintained) port. In base, we do however, have camcontrol(8) and
cdcontrol(1), both of which have an eject subcommand.

Let's use camcontrol(8) here.

Sponsored by: The FreeBSD Foundation
```

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by holmanb — COMMENTED** [review]
Since the Dragonflybsd class inherits from the Freebsd class this actually overrides dragonfly's eject_media() function as well, which I don't think we want.

I think we also need the following:
```diff
diff --git a/cloudinit/distros/dragonflybsd.py b/cloudinit/distros/dragonflybsd.py
index 5032ff5a7..9a7a53eee 100644
--- a/cloudinit/distros/dragonflybsd.py
+++ b/cloudinit/distros/dragonflybsd.py
@@ -2,8 +2,13 @@
 #
 # This file is part of cloud-init. See LICENSE file for license information.
 
-import cloudinit.distros.freebsd
+from cloudinit.distros import Distro as base
+from cloudinit.distros import freebsd
 
 
-class Distro(cloudinit.distros.freebsd.Distro):
+class Distro(freebsd.Distro):
     home_dir = "/home"
+
+    @staticmethod
+    def eject_media(device: str) -> None:
+        base.eject_media(device)
```

**Comment by igalic** [comment]
yeah, we could do that, but dragonfly has [camcontrol(8)](https://man.dragonflybsd.org/?command=camcontrol&section=8).

cam is very old, as you can see from the history section.

more importantly: i have misread https://man.dragonflybsd.org/?command=eject&section=ANY this is just the same port (unmaintained) eject port: https://man.freebsd.org/cgi/man.cgi?eject

so, that commit message needs adapting.
I'll also add a test case. tomorrow.

**Comment by holmanb** [comment]
> yeah, we could do that, but dragonfly has [camcontrol(8)](https://man.dragonflybsd.org/?command=camcontrol&section=8).
> 
> cam is very old, as you can see from the history section.
> 
> more importantly: i have misread https://man.dragonflybsd.org/?command=eject&section=ANY this is just the same (unmaintained) eject port: https://man.freebsd.org/cgi/man.cgi?eject
> 
> so, that commit message needs adapting. I'll also add a test case. tomorrow.

That sounds good, thanks @igalic!

**Comment by igalic** [comment]
n.b.: Tomorrow has turned into much later, as I'm at a conference right now.

**Review by holmanb — APPROVED** [review]
LGTM

**Pull request merged**
