### PR TITLE
Export warning logs to status.json

### PR DESCRIPTION
**Pull request by holmanb**
```
Export warning logs to status.json
```

Work continued from https://github.com/canonical/cloud-init/pull/2164

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
@holmanb I'll wait for this one to be rebased before I review.

**Comment by holmanb** [comment]
> @holmanb I'll wait for this one to be rebased before I review.

@TheRealFalcon Done

**Review by TheRealFalcon — COMMENTED** [review]
Overall LGTM!

I think this functionality is worth an integration test though (that would probably get expanded on later). It could be to launch something that causes a warning in the logs, then ensure the expected warning is in /run/cloud-init/status.json

**Review by TheRealFalcon — APPROVED** [review]
LGTM! I'll leave it to you to merge.

**Pull request merged**
