### PR TITLE
sources/azure: remove bind/unbind logic for hot attached nic

### PR DESCRIPTION
**Pull request by cjp256**
Wait up to 10 seconds for link to come up before continuing. This
typically takes just a few seconds once the NIC is hotplugged.

If it takes longer than 10 seconds for whatever reason, dhclient
should eventually succeed on its next attempt after the link does
come online.

Signed-off-by: Chris Patterson <cpatterson@microsoft.com>

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
@cjp256 I haven't reviewed this because of the draft state. If it's ready for review, let me know and I can review it.

**Comment by cjp256** [comment]
Thanks James, given the nature of this change I've just had it in testing for quite some time :D Opened for review.

**Review by anhvoms — APPROVED** [review]
LGTM

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
