### PR TITLE
Remove distutils usage

### PR DESCRIPTION
**Pull request by sshedi**
distutils is getting deprecated soon. Let's replace it with alternatives as suggested in:
https://www.python.org/dev/peps/pep-0632/

Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>

## Proposed Commit Message

```
Remove distutils usage
distutils is getting deprecated soon. Let's replace it with alternatives as suggested in:
https://www.python.org/dev/peps/pep-0632/
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by holmanb** [comment]
Hi @sshedi, thanks for the PR.

In addition to fixing the failing tests, I think that it would be better if we could avoid adding a dependency in this PR.  Since `distutils.version` is only used twice in one file I don't think the 3rd party dep is justified (distutils is standard library). 

Furthermore that usage is for a workaround for a version of `requests` that I doubt is supported with any version of python we support. According to the requests [1.0.0 pypi page](https://pypi.org/project/requests/1.0.0/), Python 3.3 was the highest Python version supported at the time of the 1.0.0 release.


It looks like requests on Ubuntu Bionic, for example, is currently 
```
root@me:~# python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.18.4'
>>> quit()
```

Removing this workaround code and adding a minimum version to requests might be a workable solution.

**Comment by sshedi** [comment]
Thanks @holmanb for the inputs. I will do the needed.

**Comment by sshedi** [comment]
@holmanb & @TheRealFalcon can you guys please take a look at integration test failures?

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
Thanks @sshedi . It'll be good to avoid deprecation warnings on 3.10+.

I left some inline comments. The cause of the integration test failures is one of the changed imports. More details on that inline as well.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
