### PR TITLE
Fix daily recipe: ubuntu/focal

### PR DESCRIPTION
**Pull request by blackboxsw**
Perform new_upstream_snapshot,py to sync unreleased tip of main into ubuntu/focal in order to fix daily recipe builds which are failing due to commit 9cc458c drift in systemd files which no-singleprocess.patch removes.

## Proposed Commit Message
-- see top three most recent separate commits

## Additional Context
[failed build recipe logs](https://launchpadlibrarian.net/748388415/buildlog.txt.gz) 
the error:
```

patching file systemd/cloud-init-main.service.tmpl
Hunk #1 FAILED at 1.
Not deleting file systemd/cloud-init-main.service.tmpl as content differs from patch
```

### steps to create this branch
```
new_upstream_snapshot.py # expect failure
quilt push -a
quilt push -f
rm systemd/cloud-init-main.service.tmpl
quilt refresh
quilt pop -a 
git commit -am 'refresh patches....'
new_upstream_snapshot.py -p quilt
# enter no SRU bug to leave UNRELEASED state
# manually add refreshed patches to d/changelog
```

## Test Steps
```
git checkout main
git pull
git reset --hard upstream/main
git merge ubuntu/focal
quilt push -a
tox -e py3
quilt pop -a
````

## Merge type
- [x] git push upstream ubuntu/focal from command line once approved
- [ ] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Comment by TheRealFalcon** [comment]
Looks like the packaging tests didn't run here?

**Comment by blackboxsw** [comment]
> Looks like the packaging tests didn't run here?

I believe that's because I originally targeted this PR against main (not ubuntu/focal) and quickly edited the PR with github actions were in flight. Let's test with ubuntu/jammy to ensure github workflows are working properly.

**Comment by blackboxsw** [comment]
Proper github workflow working on correctly targeted jammy https://github.com/canonical/cloud-init/pull/5691

**Pull request merged**
