### PR TITLE
Ubuntu/bionic 23.1.x: backport ubuntu_pro config keys, deprecate ubuntu_advantage

### PR DESCRIPTION
**Pull request by blackboxsw**
```
    feat(pro): deprecate ubuntu_advantage key for ubuntu_pro
    
    Backport deprecatation of ubuntu_advantage_key in favor of ubuntu_pro
    to standardize product branding for Ubuntu Pro.
    
    This allows for common behavior, documentation and tooling on all
    supported and maintained releases including those Ubuntu releases
    under active Expanded Security Maintenance(ESM).
    
    LP: #2067660
```

## Proposed Commit Message(s)
Rebase merge:uise separate commits

## Additional Context
http://pad.lv/2067660

## Test Steps
```
build-package
sbuild --dist=bionic --arch=amd64 --arch-all ../out/cloud-init_23.1.2-0ubuntu0~18.04.2.dsc
lxc launch ubuntu-daily:bionic test-pro-b
lxc file push cloud-init_23.1.2-0ubuntu0~18.04.2_all.deb test-pro-b/
lxc exec test-pro-b -- apt update
lxc exec test-pro-b -- apt upgrade  --yes
lxc exec test-pro-b -- apt install ubuntu-advantage-tools --yes
lxc exec test-pro-b -- apt install /cloud-init_23.1.2-0ubuntu0~18.04.2_all.deb
cat > pro.yaml <<EOF
#cloud-config
ubuntu_pro:
  token: <your_token_from_ubuntu.com/pro>
EOF
# assert not attached
lxc exec test-pro-b -- pro status
lxc config set test-pro-b user.user-data="$(cat pro.yaml)"
lxc config test-pro-b -- cloud-init clean --logs --reboot
# assert no warnings in cloud-init status
lxc exec test-pro-b -- cloud-init status --wait --format=yaml
# assert pro attached
lxc exec test-pro-b -- pro status
```

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [x] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [x] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
This should target `ubuntu/bionic`, not `ubuntu/bionic-23.1.x`. We released `23.2` to bionic.

Also, do you think it might make sense to silence the deprecations in Bionic? It makes sense to support the Pro key, but I'm not sure it makes sense to push an update with a new message saying "you shouldn't be using this key anymore" on an OS that should generally only be receiving security updates.

**Comment by TheRealFalcon** [comment]
Did you mean to merge this? I don't think we targeted the right branch here.

**Comment by blackboxsw** [comment]
> This should target `ubuntu/bionic`, not `ubuntu/bionic-23.1.x`. We released `23.2` to bionic.
> 


Looks like our upstream/ubuntu/bionic branch is a lie here. We intended on releasing to bionic, but opted out as Bionic entered ESM state at the time Note the `won't fix` on the bionic task for this SRU bug.
https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2023110

rmadison also agrees (and pro attach doesn't offer an additional cloud-init pkg for install either)
```
 cloud-init | 18.2-14-g6d48d265-0ubuntu1         | bionic          | source, all
 cloud-init | 23.1.2-0ubuntu0~18.04.1            | bionic-security | source, all
 cloud-init | 23.1.2-0ubuntu0~18.04.1            | bionic-updates  | source, all
```

> Also, do you think it might make sense to silence the deprecations in Bionic? It makes sense to support the Pro key, but I'm not sure it makes sense to push an update with a new message saying "you shouldn't be using this key anymore" on an OS that should generally only be receiving security updates.

It probably makes sense to silence this deprecation message even though it doesn't generate warning or non-zero exit codes in bionic. I'll revert this merge from ubuntu/bionic/23.1.x and recreate the PR that will take into account.

**Comment by blackboxsw** [comment]
> Did you mean to merge this? I don't think we targeted the right branch here.

Opened https://github.com/canonical/cloud-init/pull/5597 to track this changeset against ubuntu/bionic branch.

**Pull request merged**
