### PR TITLE
schema: Enable deprecations in cc_growpart

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
schema: Enable deprecations in cc_growpart
```

## Additional Context

SC-1173

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Schema changes look good, but docs rendered don't look like they handle this case well:

Here's a diff of `PYTHONPATH=. python3 -m cloudinit.cmd.main schema --docs all` of main vs your PR


```diff
--- docs.main	2022-08-03 09:55:10.217744060 -0600
+++ docs.growpart	2022-08-03 09:55:27.994107590 -0600
@@ -3026,7 +3026,7 @@
 **Config schema**:
     **growpart:** (object)
 
-        **mode:** (``false``/``auto``/``growpart``/``gpart``/``off``) The utility to use for resizing. Default: ``auto``
+        **mode:** (UNDEFINED) The utility to use for resizing. Default: ``auto``
 
         Possible options:
 
@@ -3036,9 +3036,7 @@
 
         * ``gpart`` - Use BSD gpart utility
 
-        * ``off`` - Take no action
-
-        Specifying a boolean ``false`` value for this key is deprecated. Use ``off`` instead.
+        * ``off`` - Take no action.
 
         **devices:** (array of string) The devices to resize. Each entry can either be the path to the device's mountpoint in the filesystem or a path to the block device in '/dev'. Default: ``[/]``
```


I think we need to sort schema property doc rendering to avoid the UNDEFINED for this unique oneOf type approach.

I'd like to see us render docs on the non-deprecated enum if we can and ignore any deprecated oneOf values in those docs.

**Comment by aciba90** [comment]
> Schema changes look good, but docs rendered don't look like they handle this case well:
> 
> Here's a diff of `PYTHONPATH=. python3 -m cloudinit.cmd.main schema --docs all` of main vs your PR
> 
> ```diff
> --- docs.main	2022-08-03 09:55:10.217744060 -0600
> +++ docs.growpart	2022-08-03 09:55:27.994107590 -0600
> @@ -3026,7 +3026,7 @@
>  **Config schema**:
>      **growpart:** (object)
>  
> -        **mode:** (``false``/``auto``/``growpart``/``gpart``/``off``) The utility to use for resizing. Default: ``auto``
> +        **mode:** (UNDEFINED) The utility to use for resizing. Default: ``auto``
>  
>          Possible options:
>  
> @@ -3036,9 +3036,7 @@
>  
>          * ``gpart`` - Use BSD gpart utility
>  
> -        * ``off`` - Take no action
> -
> -        Specifying a boolean ``false`` value for this key is deprecated. Use ``off`` instead.
> +        * ``off`` - Take no action.
>  
>          **devices:** (array of string) The devices to resize. Each entry can either be the path to the device's mountpoint in the filesystem or a path to the block device in '/dev'. Default: ``[/]``
> ```
> 
> I think we need to sort schema property doc rendering to avoid the UNDEFINED for this unique oneOf type approach.
> 
> I'd like to see us render docs on the non-deprecated enum if we can and filter out any `oneOf` values with `deprecated: true`in docs.

https://github.com/canonical/cloud-init/pull/1627 includes a partial fix to that issue and https://warthogs.atlassian.net/browse/SC-1175 was created to solve exactly that problem.

Who should we proceed, @blackboxsw ? We could either:

1. Merge 1627 before this one and see if the issue is gone.
2. Postpone its solution to SC-1175.
3. Block this PR until SC-1175 is done.

**Review by blackboxsw — COMMENTED** [review]
Waiting on #1627 for schema changes handling enum deprecated types

**Comment by aciba90** [comment]
> Waiting on #1627 for schema changes handling enum deprecated types

Ready to be merged after https://github.com/canonical/cloud-init/pull/1627 is merged.

**Review by blackboxsw — APPROVED** [review]
* behavior changes good w/ deprecation handling/permissive schema
```
csmith@uptown:~/src/cloud-init$ PYTHONPATH=. python3 -m cloudinit.cmd.main schema -c test.yaml --annotate
#cloud-config
            growpart:                                                           
              mode: false		# D1
              devices: ["/"]                                                    
              ignore_growroot_disabled: false       

# Deprecations: -------------
# D1: DEPRECATED: Specifying a boolean ``false`` value for this key is deprecated. Use ``off`` instead.


Valid cloud-config: test.yaml
```
* doc changes good
```diff
            growpart:                                                           
              mode: auto                                                        
              devices: ["/"]                                                    
              ignore_growroot_disabled: false       
```

**Pull request merged**
