### PR TITLE
Ensure bond property name formatting matches schema definition

### LINKED ISSUE #5366: Cloud config schema error for bond properties
# Bug report
When using OpenStack with a network_data.json file which specifies a bonded interface with properties for the bond, there is a mismatch between the schemas for these properties between OpenStack and cloudinit.

## Steps to reproduce the problem
Create an OpenStack node with the following network_data.json:
```
{
  "links": [
    {
      "id": "ens1f0np0",
      "name": "ens1f0np0",
      "type": "phy",
      "ethernet_mac_address": "xx:xx:xx:xx:xx:00",
      "mtu": 9000
    },
    {
      "id": "ens1f1np1",
      "name": "ens1f1np1",
      "type": "phy",
      "ethernet_mac_address": "xx:xx:xx:xx:xx:01",
      "mtu": 9000
    },
    {
      "id": "bond0",
      "name": "bond0",
      "type": "bond",
      "bond_links": [
        "ens1f0np0", "ens1f1np1"
      ],
      "mtu": 9000,
      "ethernet_mac_address": "xx:xx:xx:xx:xx:00",
      "bond_mode": "802.3ad",
      "bond_xmit_hash_policy": "layer3+4",
      "bond_miimon": 100
    },
    {
      "id": "bond0.123",
      "name": "bond0.123",
      "type": "vlan",
      "vlan_link": "bond0",
      "vlan_id": 123,
      "vlan_mac_address": "xx:xx:xx:xx:xx:00"
    }
  ],
  "networks": [
    {
      "id": "publicnet-ipv4",
      "type": "ipv4",
      "link": "bond0.123",
      "ip_address": "x.x.x.x",
      "netmask": "255.255.255.0",
      "routes": [
        {
          "network": "0.0.0.0",
          "netmask": "0.0.0.0",
          "gateway": "x.x.x.1"
        }
      ],
      "network_id": "00000000-0000-0000-0000-000000000000"
    }
  ],
  "services": [
    {
      "type": "dns",
      "address": "1.1.1.1"
    }
  ]
}
```
Cloudinit will produce the following network-config.json:
```
{
 "config": [
  {
   "mac_address": "xx:xx:xx:xx:xx:00",
   "mtu": 9000,
   "name": "ens1f0np0",
   "subnets": [],
   "type": "physical"
  },
  {
   "mac_address": "xx:xx:xx:xx:xx:01",
   "mtu": 9000,
   "name": "ens1f1np1",
   "subnets": [],
   "type": "physical"
  },
  {
   "bond_interfaces": [
    "ens1f0np0",
    "ens1f1np1"
   ],
   "mac_address": "xx:xx:xx:xx:xx:00",
   "mtu": 9000,
   "name": "bond0",
   "params": {
    "bond_miimon": 100,
    "bond_mode": "802.3ad",
    "bond_xmit_hash_policy": "layer3+4"
   },
   "subnets": [],
   "type": "bond"
  },
  {
   "mac_address": "xx:xx:xx:xx:xx:00",
   "name": "bond0.123",
   "subnets": [
    {
     "address": "x.x.x.x",
     "ipv4": true,
     "netmask": "255.255.255.0",
     "routes": [
      {
       "gateway": "x.x.x.1",
       "netmask": "0.0.0.0",
       "network": "0.0.0.0"
      }
     ],
     "type": "static"
    }
   ],
   "type": "vlan",
   "vlan_id": 123,
   "vlan_link": "bond0"
  },
  {
   "address": "1.1.1.1",
   "type": "nameserver"
  }
 ],
 "version": 1
}
```

When validating the network-config.json file, cloudinit produces an error as the schema for bonded interfaces requires the bond properties to have a prefix of `bond-` instead of `bond_`:
https://github.com/canonical/cloud-init/blob/main/cloudinit/config/schemas/schema-network-config-v1.json#L79

## Environment details
- Cloud-init version: 23.4-7.el9_4.0.1
- Operating System Distribution: Rocky 9
- Cloud provider, platform or installer type: OpenStack Caracal 2024.1

## cloud-init logs
```
Cloud-init v. 23.4-7.el9_4.0.1 running 'init-local' at Tue, 04 Jun 2024 15:28:57 +0000. Up 1741.95 seconds.
2024-06-04 15:28:57,974 - schema.py[WARNING]: Invalid network-config provided:
config.2.params: Additional properties are not allowed ('bond_mode', 'bond_miimon', 'bond_xmit_hash_policy' were unexpected)
```

### PR DESCRIPTION
**Pull request by jcmoore3**
Ensure the bond properties match formatting of within the cloudinit network v1 schema

Fixes #5366

## Proposed Commit Message

```
fix: Ensure bond property name formatting matches schema definition

The cloud-init network config version 1 schema defines the bond
properties with underscores, prepended with 'bond-'. This change
ensures consistency with the schema for the bond property names.

Fixes GH-5366
```

## Checklist

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by catmsred** [comment]
Thank you for contributing to cloud-init!  Can you add some notes on the testing you did to validate that it fixed the bug in question and sign the CLA?

https://cloudinit.readthedocs.io/en/latest/development/first_PR.html#sign-the-cla

**Comment by jcmoore3** [comment]
Apologies that the CLA is taking so long. This needs to go through my company's internal open source approval process. I do not anticipate any issues, it just takes time. I'm hoping to have final internal approval this week.

**Comment by jcmoore3** [comment]
@catmsred - CLA signed, please let me know if anything else is required to get this moving. Change to github-cla-signers is in PR #5369.

**Review by aciba90 — CHANGES_REQUESTED** [review]
Thanks, @jcmoore3, for catching this up and the fixes.

We need to change the occurrences of these properties in v1 network configurations to the correct schema keys and check / adapt the tests.

Preliminary changes:

```diff
diff --git a/tests/unittests/net/network_configs.py b/tests/unittests/net/network_configs.py
index b68319cc8..655922d20 100644
--- a/tests/unittests/net/network_configs.py
+++ b/tests/unittests/net/network_configs.py
@@ -3055,13 +3055,13 @@ pre-down route del -net 10.0.0.0/8 gw 11.0.0.1 metric 3 || true
                 params:
                   bond-mode: active-backup
                   bond_miimon: 100
-                  bond-xmit-hash-policy: "layer3+4"
-                  bond-num-grat-arp: 5
+                  bond-xmit_hash_policy: "layer3+4"
+                  bond-num_grat_arp: 5
                   bond-downdelay: 10
                   bond-updelay: 20
-                  bond-fail-over-mac: active
+                  bond-fail_over_mac: active
                   bond-primary: bond0s0
-                  bond-primary-reselect: always
+                  bond-primary_reselect: always
                 subnets:
                   - type: static
                     address: 192.168.0.2/24
diff --git a/tests/unittests/test_net.py b/tests/unittests/test_net.py
index 080c36b6f..e75e4ff34 100644
--- a/tests/unittests/test_net.py
+++ b/tests/unittests/test_net.py
@@ -169,7 +169,7 @@ config:
         bond-miimon: 100
         bond-mode: 802.3ad
         bond-updelay: 0
-        bond-xmit-hash-policy: layer3+4
+        bond-xmit_hash_policy: layer3+4
     subnets:
     -   address: 10.101.10.47/23
         gateway: 10.101.11.254
@@ -223,7 +223,7 @@ config:
         bond-miimon: 100
         bond-mode: 802.3ad
         bond-updelay: 0
-        bond-xmit-hash-policy: layer3+4
+        bond-xmit_hash_policy: layer3+4
     subnets:
     -   type: manual
     type: bond
@@ -265,7 +265,7 @@ config:
         bond-miimon: 100
         bond-mode: 802.3ad
         bond-updelay: 0
-        bond-xmit-hash-policy: layer3+4
+        bond-xmit_hash_policy: layer3+4
     subnets:
     -   address: 10.101.8.65/26
         routes:
```

Ideally, we also need to cover the case where we render eni configs from v1 including these keys.

**Review by aciba90 — APPROVED** [review]
LGTM, thanks! This pr corrects the translation from network-config-v1 to NetworkManager.

(My previous comment was because reading the PR title and commit, I understood the fix was global and not NM specific.)

**Pull request merged**
