### PR TITLE
chore: remove `--docs` option from `cloud-init schema`

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
chore: remove `--docs` option from `cloud-init schema`

It has been broken and has marginal value, so it is not worth
maintaining. Since it was a developer-facing option, this should
have no backwards compatibility concerns.

Fixes GH-5756
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by holmanb — COMMENTED** [review]
Big thanks for this cleanup @TheRealFalcon.

I haven't had a chance to look at this in depth, but it looks like we lost some coverage. That isn't to say that the code is lower quality, but without looking further it does make me wonder if this means that there is some dead code that we missed cleaning up that is now untested because we removed its test coverage. Thoughts?

Coverage of the new commit
```
Name                                                           Stmts   
cloudinit/config/schema.py                                       603     81    242     32    83%
cloudinit/importer.py                                             42      0     26      3    96%
```

Coverage of the previous commit
```
Name                                                           Stmts   

cloudinit/config/schema.py                                       797     59    344     34    91%
cloudinit/importer.py                                             42      0     26      1    99%
```

**Comment by holmanb** [comment]
>     * `_flatten(xs)` appears to be dead

Agreed - want to smite that too?

>     * `flatten_schema_refs(...)` was used by some of the deleted code, but is still used in conf.py when building the documentation.
> 
> 
> Because it was used by the removed code, the tests that tested the removed code also happened to remove the coverage for this function. I can add in new coverage for it.

What if we just move it to `conf.py`? It isn't used by any cloud-init runtime code, so I would never put it where it is currently if adding it as new code. Also, it wouldn't look out of place alongside the function definitions in conf.py where it gets called - it's doing similar types of things as the current code that is there.

**Comment by TheRealFalcon** [comment]
Rebased and should be ready for re-review

**Review by holmanb — APPROVED** [review]
Thanks! This looks good to me @TheRealFalcon. Feel free to merge as-is.

**Pull request merged**
