### PR TITLE
Add suse distro

### PR DESCRIPTION
**Pull request by holmanb**
Proposed commit message:
```
distros: Add suse
```

## Additional Context
Fixes https://github.com/canonical/cloud-init/issues/4525

### CODE REVIEW

**Comment by holmanb** [comment]
Requesting review from @Rozzii, @smoshiur1237, and @rjschwei

**Comment by Rozzii** [comment]
I am not sure about the commit name, I mean I am honored that my "nick" would be in the cloud-init git history but is it okay thing in this project ? I am not familiar with the conventions here.

**Comment by holmanb** [comment]
> I am not sure about the commit name, I mean I am honored that my "handle" would be in the cloud-init git history but is it okay thing in this project ? I am not familiar with the conventions here.

Agreed :) In this project by default we typically squash merge with a commit message that is defined in the Pull request. The message I'm proposing is:
```
distro: Add suse
```

**Review by CalvoM — APPROVED** [review]
LGTM

**Comment by rjschwei** [comment]
As stated in the issue I think this is incorrect, as no SUSE distro, no openSUSE or SUSE Linux enterprise server identifies itself as "SUSE". The changes do no harm but are superfluous.

**Review by smoshiur1237 — COMMENTED** [review]
Thanks for adding the changes. I was able to go forward with my test where distro name is detected as suse for SUSE SP4 Enterprise version.
LGTM

**Comment by holmanb** [comment]
Hey @smoshiur1237, where did you get this image? I'm confused why this is happening if @rjschwei doesn't expect it to. It might "solve your issue", but I'm concerned that we're barking up the wrong tree if the root cause is using a customized change. Do you have a reproducer that I can poke at? Is this a custom image build you are using or something direct from SUSE?

**Comment by smoshiur1237** [comment]
@holmanb The image I am using is named `SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2` , and it is available in [Suse Enterprise image](https://www.suse.com/download/sles/). After installing cloud-init I was getting the error for suse distro and your changes help to eliminate the error and it is moving on.

**Comment by Rozzii** [comment]
It is not stale, we are waiting for feedback, @holmanb .

**Comment by holmanb** [comment]
> It is not stale, we are waiting for feedback, @holmanb .

I think at this point this just requires a review from another dev (ping @aciba90, @TheRealFalcon @blackboxsw).

@rjschwei doesn't seem to think it is necessary, but apparently this change solves @Rozzii and @smoshiur1237's issue on a suse-provided image, so I'm +1 with including this since it is harmless if unused. If @rjschwei has any thoughts on why that's happening on the image @smoshiur1237 pointed to, I'd be curious, otherwise I'm fine to land this PR and put this issue  behind us.

**Review by TheRealFalcon — APPROVED** [review]
LGTM

**Comment by rjschwei** [comment]
OK, and to close the loop on this, and sorry it took me a while to get there. When cloud-init is built in the build service we build it for a specific distribution by including a so called release package in the build system. This release package then assures that the system identifies itself "correctly" for example as SLES. I suspect, but have not checked, that the qcow image being used as the basis to build cloud-init does not have a release package installed, which is why the system would identify itself as "suse".

**Pull request merged**
