### PR TITLE
Gentoo bugfixes

### PR DESCRIPTION
**Pull request by holmanb**
```
Not ready for review yet
```

## Additional Context
- emerge bugfix
- network bugfix
- dns add search address

## Checklist:

 - [ ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by holmanb** [comment]
Planning to circle back after 22.3 validation is done

**Comment by licebmi** [comment]
I actually joined to commit mostly these changes. Will this be reopened or should I make a different PR?

**Comment by holmanb** [comment]
> I actually joined to commit mostly these changes. Will this be reopened or should I make a different PR?

This one slipped through the cracks, my apologies @phunyguy. On that note, however, I just realized that we never got a CLA signature[1] from you. Would you be willing to sign it? That would really simplify picking this back up.

@licebmi Thanks for bringing this up. This needs a little bit of cleanup still, which I originally planned but never got around to. A new PR would be best, I think. Feel free to submit any commits that I wrote (I've already signed the CLA and I don't require attribution), but we should probably wait to hear back from @phunyguy on CLA signature for those commits, just to be safe.

[1] More info https://cloudinit.readthedocs.io/en/latest/development/contributing.html#summary

**Comment by phunyguy** [comment]
@homanb Sorry for the delay here.  I have signed CLA, and added myself (with PR) to the list.  Hopefully I did that correctly. What else is needed from me?

**Comment by holmanb** [comment]
Thanks @phunyguy! I really appreciate it, and you did it correctly.

Sorry this slipped through the cracks.

@licebmi If you're ready to pick up any of this feel free to submit a PR. If not, please let me know and I'll get this on my backlog.

**Pull request closed without merging**
