### PR TITLE
update azurelinux cloud-init config

### PR DESCRIPTION
**Pull request by rmhsawyer**
## Proposed Commit Message

```
<bug>(azurelinux): update azurelinux cloud-init config 
- Update upstream cloud-init config template for azurelinux distro
- remove modules that not currently supported azurelinux
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — COMMENTED** [review]
I understand why the `disable_ec2_metadata` and `reset_rmc` modules make no sense on azurelinux, but why prevent the rest from running? E.g., why prevent puppet or chef if somebody wants to use them?

**Comment by rmhsawyer** [comment]
> I understand why the `disable_ec2_metadata` and `reset_rmc` modules make no sense on azurelinux, but why prevent the rest from running? E.g., why prevent puppet or chef if somebody wants to use them?

**Comment by rmhsawyer** [comment]
For modules like puppet and chef currently will not have successful runs on azurelinux for various reasons. For example, puppet will have unsuccessfully run due to issue in our puppet packages. For chef, we have installation issues with cloud-init cc_chef.py when using gems install where requires version check. Azurelinux currently don't have support for these modules and there is no need from our customers. So, I think it's best to remove those and limit the risk of people using it. @TheRealFalcon What do you think?

**Review by a-dubs — APPROVED** [review]
Changes look good, and thanks for the context on why puppet and chef need disabled specifically on azurelinux @rmhsawyer!

@TheRealFalcon what are your thoughts on this?

**Review by TheRealFalcon — APPROVED** [review]
LGTM! Thanks for the explanation.

**Pull request merged**
