### PR TITLE
Ubuntu/groovy

### PR DESCRIPTION
**Pull request by TheRealFalcon**

### CODE REVIEW

**Comment by OddBloke** [comment]
I've reproduced the contents of this branch. I performed the following steps:

* `new-upstream-snapshot upstream/master`
* Manually fixed up the `\r\n` that our tooling doesn't escape
* `git cherry-pick 81626fb7` (to pull in the Vultr datasource changes)
* Manually fixed conflicts in timestamps in `debian/po/templates.pot`
* `git cherry-pick 495f1e3c8d54b6be6edbb77bcd71d0fb805c4e63` to pull in the changelog text that James used

**Comment by OddBloke** [comment]
However, during test build, I see the following lintian warning:
```
W: cloud-init source: newer-debconf-templates
```
[Per lintian.debian.org](https://lintian.debian.org/tags/newer-debconf-templates), that means that:

> debconf-updatepo has not been run since the last change to your debconf templates.

If I run that command then I see the following diff:

```diff
diff --git a/debian/po/templates.pot b/debian/po/templates.pot
index ac7b10a6..56b78d06 100644
--- a/debian/po/templates.pot
+++ b/debian/po/templates.pot
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: cloud-init\n"
 "Report-Msgid-Bugs-To: cloud-init@packages.debian.org\n"
-"POT-Creation-Date: 2021-04-20 10:14-0400\n"
+"POT-Creation-Date: 2021-05-12 11:58-0400\n"
 "PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
 "Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
 "Language-Team: LANGUAGE <LL@li.org>\n"
@@ -158,7 +158,7 @@ msgstr ""
 #. Type: multiselect
 #. Choices
 #: ../cloud-init.templates:1001
-msgid "Vultr: Vultr"
+msgid "Vultr: Vultr Cloud"
 msgstr ""
 
 #. Type: multiselect
```

This issue appears present in the `ubuntu/devel` commit that is cherry-picked in various places: I suspect that the text in `debian/cloud-init.templates` was revised without re-running `debconf-updatepo`.

**Comment by TheRealFalcon** [comment]
Amended HEAD~ commit with results from `debconf-updatepo`

**Comment by OddBloke** [comment]
OK, this is just missing the `ubuntu2` update: I'll do that locally so I can kick off my testing.

**Review by OddBloke — APPROVED** [review]
I've applied the version fix locally, which is what I'll upload and push, so +1 on this pending local testing.

**Pull request merged**
