### PR TITLE
Holmanb/python3.13

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

```
ci: Add Python 3.13
```

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Should we close this PR and re-open when the run can work?

**Comment by holmanb** [comment]
> Should we close this PR and re-open when the run can work?

Or maybe the opposite - we open if failing, so that we can easily check in periodically to see if it is failing because of test failures or still failing because of build failures. WDYT?

**Comment by TheRealFalcon** [comment]
Keeping it with a non-vote to CI is good

**Comment by TheRealFalcon** [comment]
> non-vote

Reading about it...is this an option? https://github.com/actions/runner/issues/2347

**Comment by holmanb** [comment]
Requires https://github.com/canonical/cloud-init/pull/4669

**Comment by TheRealFalcon** [comment]
Will this fail CI if the dev job fails?

**Comment by holmanb** [comment]
> Will this fail CI if the dev job fails?

Yep, over 1000 reactions to [the top comment](https://github.com/actions/runner/issues/2347) and Github still hasn't bothered to implement this.

We can let this grow stale until 3.13 is released, if you want, but we had 3.12 as a job before it was released and didn't have any troubles, so alternatively we could just drop 3.13 if it causes troubles. I got a passing run on 3.13, so I'm happy either way.

**Review by TheRealFalcon — APPROVED** [review]
> alternatively we could just drop 3.13 if it causes troubles

Yeah, I think this makes more sense. Better to get the signal if we need it rather than ignore it due to possible breaking changes from Python, which seem pretty unlikely.

**Pull request merged**
