### PR TITLE
change openEuler to openeuler

### PR DESCRIPTION
**Pull request by yangzz-97**
change openEuler to openeuler

### CODE REVIEW

**Review by TheRealFalcon — CHANGES_REQUESTED** [review]
Hey @yangzz-97, before we can accept your change, you need to sign [the CLA](https://ubuntu.com/legal/contributors/agreement) and add your Github username (alphabetically) to [the cla signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) . The full details are described in the last bullet point here: https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#submitting-your-first-pull-request

Additionally, I still see some references left. Did you want to change these as well?
```
config/cloud.cfg.tmpl:
[1]: 179:                  "eurolinux", "fedora", "freebsd", "netbsd", "miraclelinux", "openbsd", "openEuler",
[2]: 234:                    "fedora", "miraclelinux", "openEuler", "rhel", "rocky", "suse", "virtuozzo"] %}

tests/unittests/test_util.py:
[3]: 259:    NAME="openEuler"
[4]: 261:    ID="openEuler"
[5]: 263:    PRETTY_NAME="openEuler 20.03 (LTS-SP2)"

README.md:
[6]: 42:| Alpine Linux<br />ArchLinux<br />Debian<br />DragonFlyBSD<br />Fedora<br />FreeBSD<br />Gentoo Linux<br />NetBSD<br />OpenBSD<br />openEuler<br />RHEL/CentOS/AlmaLinux/Rocky/PhotonOS/Virtuozzo/EuroLinux/CloudLinux/MIRACLE LINUX<br />SLES/openSUSE<br />Ubuntu<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /> | Amazon Web Services<br />Microsoft Azure<br />Google Cloud Platform<br />Oracle Cloud Infrastructure<br />Softlayer<br />Rackspace Public Cloud<br />IBM Cloud<br />DigitalOcean<br />Bigstep<br />Hetzner<br />Joyent<br />CloudSigma<br />Alibaba Cloud<br />OVH<br />OpenNebula<br />Exoscale<br />Scaleway<br />CloudStack<br />AltCloud<br />SmartOS<br />HyperOne<br />Vultr<br />Rootbox<br /> | Bare metal installs<br />OpenStack<br />LXD<br />KVM<br />Metal-as-a-Service (MAAS)<br />VMware<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />|

ChangeLog:
[7]: 83: - Support openEuler OS (#1012) [zhuzaifangxuele]
```

**Comment by yangzz-97** [comment]
> Hey @yangzz-97, before we can accept your change, you need to sign [the CLA](https://ubuntu.com/legal/contributors/agreement) and add your Github username (alphabetically) to [the cla signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) . The full details are described in the last bullet point here: https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#submitting-your-first-pull-request
> 
> Additionally, I still see some references left. Did you want to change these as well?
> 
> ```
> config/cloud.cfg.tmpl:
> [1]: 179:                  "eurolinux", "fedora", "freebsd", "netbsd", "miraclelinux", "openbsd", "openEuler",
> [2]: 234:                    "fedora", "miraclelinux", "openEuler", "rhel", "rocky", "suse", "virtuozzo"] %}
> 
> tests/unittests/test_util.py:
> [3]: 259:    NAME="openEuler"
> [4]: 261:    ID="openEuler"
> [5]: 263:    PRETTY_NAME="openEuler 20.03 (LTS-SP2)"
> 
> README.md:
> [6]: 42:| Alpine Linux<br />ArchLinux<br />Debian<br />DragonFlyBSD<br />Fedora<br />FreeBSD<br />Gentoo Linux<br />NetBSD<br />OpenBSD<br />openEuler<br />RHEL/CentOS/AlmaLinux/Rocky/PhotonOS/Virtuozzo/EuroLinux/CloudLinux/MIRACLE LINUX<br />SLES/openSUSE<br />Ubuntu<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /> | Amazon Web Services<br />Microsoft Azure<br />Google Cloud Platform<br />Oracle Cloud Infrastructure<br />Softlayer<br />Rackspace Public Cloud<br />IBM Cloud<br />DigitalOcean<br />Bigstep<br />Hetzner<br />Joyent<br />CloudSigma<br />Alibaba Cloud<br />OVH<br />OpenNebula<br />Exoscale<br />Scaleway<br />CloudStack<br />AltCloud<br />SmartOS<br />HyperOne<br />Vultr<br />Rootbox<br /> | Bare metal installs<br />OpenStack<br />LXD<br />KVM<br />Metal-as-a-Service (MAAS)<br />VMware<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />|
> 
> ChangeLog:
> [7]: 83: - Support openEuler OS (#1012) [zhuzaifangxuele]
> ```
Yes, these are the places I missed. Could you please help me submit them.Thank you！

**Comment by TheRealFalcon** [comment]
> Could you please help me submit them

What sort of help do you need? It shouldn't be any more than updated the locations I showed.

**Comment by xiaoge1001** [comment]
Why do we change openEuler to openEuler?

**Pull request closed without merging**
