### PR TITLE
chore: Add docstrings and types to Version class

### PR DESCRIPTION
**Pull request by holmanb**
## Additional Context
chore: Add docstrings and types to Version class

### CODE REVIEW

**Review by blackboxsw — APPROVED** [review]
I like that you are following google's python style guide: https://google.github.io/styleguide/pyguide.html

Let's avoid extra empty newlines in the docstrings as we are dedicating a lot of vertical real-estate to these docstrings already.

**Comment by TheRealFalcon** [comment]
I have thoughts...let's not merge this quite yet

**Comment by TheRealFalcon** [comment]
nit: If we change `>>` to `>>>`, these would be valid doctest examples. We don't use it, but it'd be an easy way to gain test coverage for utility functions in the future and ensure our docstring examples are kept up to date.

More broadly, if we're wanting to standardize on a format, I'd prefer we use the [Sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format) format. Reasons:
1. Since we're already using Sphinx, if we ever decide to autogenerate docs docstrings, it should be a fairly easy transition.
2. Since the format is very similar to the epytext strings that are scattered through the codebase, it'd be a much simpler find/replace for those than switching them to Google format would be.
3. Minor point, but Google convention technically breaks pep-8/pep-257 in things like recommending non-imperative mood. If we use a linter and say "use google style", our currently existing docstrings that use imperative mood may not match.

Since [existing tooling](https://pypi.org/project/pydoclint/) generally supports both formats, I don't think there's any loss from not using Google format.

**Comment by holmanb** [comment]
> nit: If we change `>>` to `>>>`, these would be valid doctest examples. We don't use it, but it'd be an easy way to gain test coverage for utility functions in the future and ensure our docstring examples are kept up to date.

No objections from me for cheap test coverage :D

> More broadly, if we're wanting to standardize on a format, I'd prefer we use the [Sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format) format. Reasons:
> 
>     1. Since we're already using Sphinx, if we ever decide to autogenerate docs docstrings, it should be a fairly easy transition.
> 
>     2. Since the format is very similar to the epytext strings that are scattered through the codebase, it'd be a much simpler find/replace for those than switching them to Google format would be.
> 
>     3. Minor point, but Google convention technically breaks pep-8/pep-257 in things like recommending non-imperative mood. If we use a linter and say "use google style", our currently existing docstrings that use imperative mood may not match.
> 
> 
> Since [existing tooling](https://pypi.org/project/pydoclint/) generally supports both formats, I don't think there's any loss from not using Google format.

Good points.

The only reservations that I have are that sphinx has a little more boilerplate and a little more work for my eyes to parse than google-styled docstrings. I'm sure I'll get used to sphinx docstrings without issue. I'll update this PR unless @blackboxsw or @aciba90 has any strong objections.

**Comment by TheRealFalcon** [comment]
> boilerplate

I don't think we need to include every field every time. E.g., there's a [stackoverflow](https://stackoverflow.com/a/24385103/37205) answer that has this:
```python
"""
This is a reST style.

:param param1: this is a first param
:param param2: this is a second param
:returns: this is a description of what is returned
:raises keyError: raises an exception
"""
```
Which is a lot less boilerplate. Since we (ideally) have types specific in the function definition, we shouldn't also need them in the docstring.

**Comment by aciba90** [comment]
Thanks for the discussion.

I do not care much about which docstring format we use, but more about picking up one and be consistent with it.

If we choose a new one, we could use https://github.com/dadadel/pyment to convert existent docstrings if we want.

To lint / enforce docstrings to follow a particular style, we could use https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention, since https://github.com/PyCQA/pydocstyle has been deprecated in favor of ruff.

**Comment by holmanb** [comment]
> If we choose a new one, we could use https://github.com/dadadel/pyment to convert existent docstrings if we want.

I can see this being useful to get started with some modules that are more important. These are the ones that I would start with

```
stages.py/main.py -> because it defines core logic
util.py -> because is so heavily used across the codebase
distros/__init__.py -> because it defines an interface which gets implemented by all distros
sources/__init__.py -> because it defines an interface which gets implemented by all platforms
```

> To lint / enforce docstrings to follow a particular style, we could use https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention, since https://github.com/PyCQA/pydocstyle has been deprecated in favor of ruff.

+1

**Comment by holmanb** [comment]
>> To lint / enforce docstrings to follow a particular style, we could use https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention, since https://github.com/PyCQA/pydocstyle has been deprecated in favor of ruff.
>
> +1

@aciba90 fyi https://github.com/canonical/cloud-init/pull/5277

**Comment by aciba90** [comment]
> > > To lint / enforce docstrings to follow a particular style, we could use https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention, since https://github.com/PyCQA/pydocstyle has been deprecated in favor of ruff.
> > 
> > 
> > +1
> 
> @aciba90 fyi #5277

Thanks for pinging!

@holmanb I went into a rabbit hole: https://github.com/canonical/pycloudlib/pull/374

**Comment by holmanb** [comment]
@TheRealFalcon @aciba90 @blackboxsw I just updated with a sphinx docstring fyi

**Review by TheRealFalcon — APPROVED** [review]
This version LGTM, but lets give @blackboxsw and @aciba90 time for any additional bikeshedding.

**Comment by holmanb** [comment]
@aciba90 I misread your earlier comment, my apologies. I thought that this was suggesting to add docstrings by default to all functions, but now that I've re-read I understand what you said.

> If we choose a new one, we could use https://github.com/dadadel/pyment to convert existent docstrings if we want.

Yes 100% agreed. I think that we should do a bulk update of all comments in the project (or at least in `cloudinit/`) to match this format. Piecemeal updates will take forever. I just filed https://github.com/canonical/cloud-init/issues/5346 to track this effort.

**Pull request merged**
