### PR TITLE
Refresh bionic patches (SC-682)

### PR DESCRIPTION
**Pull request by TheRealFalcon**
Refresh patches due to changes in 039c40f: 

  debian/patches/ec2-dont-apply-full-imds-network-config.patch
  debian/patches/openstack-no-network-config.patch

'test_datasource' directory was renamed to sources.

Note that this also includes an upstream snapshot.

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
I was hoping in this case we could have used our process documented in [uss-tableflip/ubuntu_release_process: When daily recipe fails](https://github.com/canonical/uss-tableflip/blob/main/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails) which should avoid pulling in a full new-upstream-snapshot into the release branch.

But, because we also overhauled/renamed so many other tests in 039c40f9b3d88ee8158604bb18ca4bf2fb5d5e51 we can't re-apply the patches cleanly in this case to ubuntu/bionic without first a `new-upstream-snapshot 039c40f9b3d88ee8158604bb18ca4bf2fb5d5e51` in order to get bionic at least up to the point where that commitish can be applied.

Since we have to new-upstream-snapshot anyway on bionic to get it "far enough" to quilt refresh the rest of the patches, I agree it's worth just grabbing latest new-upstream-snapshot instead of the simpler documented "fix daily build recipes".


That said there is a typo in the cmd which should be "new-upstream-snapshot --update-patches-only". I've updated [a doc PR #81](https://github.com/canonical/uss-tableflip/pull/81) on uss-tableflip now to correct docs. 


Here is the procedure I ran locally
```bash
git checkout upstream/ubuntu/bionic -B ubuntu/bionic
new-upstream-snapshot --skip-release e9634266ea52bf184727fb0782d5dc35f9ed1468
quilt push -f
# Apply the missing openstack test patch  to new tests/unittests/sources/ renamed dir
# Note we couldn't apply test_openstack.py because of renames. quilt add, modify then quilt refresh
quilt add tests/unittests/sources/test_openstack.py
patch -p4 -d tests/unittests/sources/ < debian/patches/openstack-no-network-config.patch
quilt refresh
exit 0 # to sync openstack patch changes before moving onto ec2 patch failures
quilt push -f # to sort ec2 patch failure
# note we couldn't apply test_ec2.py because of the rename. add it to quilt, modify it and refresh patch
quilt add tests/unittests/sources/test_ec2.py
patch -p4 -d tests/unittests/sources/ < debian/patches/ec2-dont-apply-full-imds-network-config.patch
quilt refresh
exit 0
```

I'm seeing a diff between your branch and mine that points to your branch maybe not capturing the test_ec2 changes?
```diff
diff --git a/debian/changelog b/debian/changelog
index 4744e4c4..220d2559 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -53,7 +53,7 @@ cloud-init (21.4-39-ge9634266-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
     - testing: stop chef test from running on openstack (#1102)
     - alpine.py: add options to the apk upgrade command (#1089) [dermotbradley]
 
- -- James Falcon <james.falcon@canonical.com>  Fri, 10 Dec 2021 16:18:55 -0600
+ -- Chad Smith <chad.smith@canonical.com>  Mon, 13 Dec 2021 13:49:29 -0700
 
 cloud-init (21.4-0ubuntu1~18.04.1) bionic; urgency=medium
 
diff --git a/debian/patches/ec2-dont-apply-full-imds-network-config.patch b/debian/patches/ec2-dont-apply-full-imds-network-config.patch
index 1070ecd3..b3ada431 100644
--- a/debian/patches/ec2-dont-apply-full-imds-network-config.patch
+++ b/debian/patches/ec2-dont-apply-full-imds-network-config.patch
@@ -26,3 +26,21 @@ Last-Update: 2020-06-01
  
              # RELEASE_BLOCKER: xenial should drop the below if statement,
              # because the issue being addressed doesn't exist pre-netplan.
+--- a/tests/unittests/sources/test_ec2.py
++++ b/tests/unittests/sources/test_ec2.py
+@@ -447,7 +447,14 @@ class TestEc2(test_helpers.HttprettyTest
+         """
+         ds = self._setup_ds(
+             platform_data=self.valid_platform_data,
+-            sys_cfg={'datasource': {'Ec2': {'strict_id': True}}},
++            sys_cfg={
++                'datasource': {
++                    'Ec2': {
++                        'strict_id': True,
++                        'apply_full_imds_network_config': True
++                    }
++                }
++            },
+             md={'md': SECONDARY_IP_METADATA_2018_09_24})
+         find_fallback_path = M_PATH_NET + 'find_fallback_nic'
+         with mock.patch(find_fallback_path) as m_find_fallback:
```

Other than that, all good here.

**Comment by TheRealFalcon** [comment]
@blackboxsw , updated the branch

**Comment by TheRealFalcon** [comment]
@blackboxsw , 3rd time's a charm???

**Review by blackboxsw — APPROVED** [review]
+1 3rd time is the charm.
* Sensible packaging diff on my side
```diff
diff --git a/debian/changelog b/debian/changelog
index 4f615da3..36ce28c2 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -53,7 +53,7 @@ cloud-init (21.4-39-ge9634266-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
     - testing: stop chef test from running on openstack (#1102)
     - alpine.py: add options to the apk upgrade command (#1089) [dermotbradley]
 
- -- James Falcon <james.falcon@canonical.com>  Mon, 13 Dec 2021 18:46:17 -0600
+ -- Chad Smith <chad.smith@canonical.com>  Tue, 14 Dec 2021 14:45:06 -0700
 
 cloud-init (21.4-0ubuntu1~18.04.1) bionic; urgency=medium
```
* quilt push -a; tox -e py3; quilt pop -a: success
* build-package /sbuild success
* daily recipe build success
```
git checkout upstream/main
git merge ubuntu/bionic
git merge upstream/ubuntu/daily/bionic
quilt push -a; tox -e py; quilt pop -a;
```

**Pull request merged**
