### PR TITLE
cloud.cfg mod names: docs and rename salt_minion and set_password

### PR DESCRIPTION
**Pull request by blackboxsw**
fix e0a96d78  test regression and missed module renames in cloud.cfg.tmpl
## Proposed Commit Message

```
Commit e0a96d78 standardized config module names as underscore-delimited.

Correct config module names in cloud.cfg.tmpl: salt_minion and set_password
Also update docs for all config module references.
Update integration test for expected skip on salt-minion to salt_minion

Co-authored-by: Alberto Contreras <alberto.contreras@canonical.com>
Co-authored-by: dermotbradley <dermot_bradley@yahoo.com>
```

## Additional Context
Broken Jenkins jobs on [tests.integration_tests.modules.test_ca_certs.TestCaCerts.test_clean_log](https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-jammy-lxd_container/lastSuccessfulBuild/testReport/junit/tests.integration_tests.modules.test_ca_certs/TestCaCerts/test_clean_log/)

## Test Steps
```
make deb
CLOUD_INIT_CLOUD_INIT_SOURCE=cloud-init*deb CLOUD_INIT_KEEP_INSTANCE=1 .tox/integration-tests/bin/pytest  tests/integration_tests/modules/test_ca_certs.py::TestCaCerts::test_clean_log
```
## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by blackboxsw** [comment]
@dermotbradley wanted for fwd this FYI for review.

**Comment by dermotbradley** [comment]
I spotted some other changes to make:

https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_ssh_import_id.py#L60

https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config.txt#L158

https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config.txt#L160

https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config.txt#L161

https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config.txt#L163

Quite a few entries in here: https://github.com/canonical/cloud-init/blob/main/doc/rtd/explanation/analyze.rst

**Comment by aciba90** [comment]
Thanks, @blackboxsw and @dermotbradley. LGTM.

I attach a patch fixing the spotted changes by @dermotbradley and more: https://paste.ubuntu.com/p/ZqX6fxtDjH/

**Review by aciba90 — APPROVED** [review]
+1. @blackboxsw, feel free to either merge as is (and I can create a follow-up PR including the extra changes) or include my patch.

**Review by blackboxsw — COMMENTED** [review]
Thanks for the additional catches. Merged both @aciba90 and @dermotbradley's change (minus the ubuntu-advantage suggestions as we still need to honor the "old style" keys there.

Ultimately, we should deprecate hyphenated keys w/ warnings (and schema warnings) in the future. But not this PR.

**Pull request merged**
