### PR TITLE
testing: migrate test_cc_set_passwords to pytest

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
testing: migrate test_cc_set_passwords to pytest
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by blackboxsw** [comment]
Sorry @aciba90 I just merged https://github.com/canonical/cloud-init/pull/1590 which created merge conflicts for this PR. Please rebase and resolve conflicts

**Review by blackboxsw — COMMENTED** [review]
Most of this PR won't be required anymore as James went through and refactored the tests a bit, but I like your doesn_not_raise changes, so maybe it's worth folding that in on top.

**Comment by aciba90** [comment]
Force-push to fix conflicts. I totally forgot James's PR. Ready to review after CI. Thanks, @blackboxsw!

**Review by blackboxsw — APPROVED** [review]
LGTM!

**Pull request merged**
