### PR TITLE
Add AlexBaranowski as contributor

### PR DESCRIPTION
**Pull request by AlexBaranowski**
Hi,

My Ubuntu One username is alexbaranowski (no capital letters ;(().
Launchpad profile https://launchpad.net/~alexbaranowski

Best,
Alex

### CODE REVIEW

**Comment by blackboxsw** [comment]
Thanks for this submittal Alex.

It looks like the CLA signature that was performed did not provide this @AlexBaranowski github username so we can't specifically confirm the accounts are related (although I realize it is highly unlikely that they are not:))


In order to fix this for our tracking and verification, you can follow one of the following procedures so we can validate that the Launchpad account and this account are both tied together.

Either,
1. [re-submit the CLA and note your AlexBaranowski github username in the field](https://ubuntu.com/legal/contributors/agreement)
OR 

2. submit a parallel pull request in launchpad with this content so we can validate this github user has access to launchpad's alexbaranoski Ubuntu One account.


If you choose route 2: There is a tool to push up  the matching Launchpad pull request described here https://cloudinit.readthedocs.io/en/latest/topics/hacking.html#transferring-cla-signatures-from-launchpad-to-github

**Comment by AlexBaranowski** [comment]
Hi,

Sorry for the fuss. I just resubmitted CLA. I hope that this time everything is OK :). If not let me know, then I will try the second solution.

Bests,
Alex

**Comment by blackboxsw** [comment]
> Hi,
> 
> Sorry for the fuss. I just resubmitted CLA. I hope that this time everything is OK :). If not let me know, then I will try the second solution.
> 
> Bests,
> Alex




@AlexBaranowski the second filing of the CLA also seemed to lack a github username filled in with the value "AlexBaranowski"
in the "Github Username" input box.


It might be nearly as efficient if you are able to 
```
cd cloud-init
git remote add launchpad git+ssh://alexbaranowski@git.launchpad.net/~alexbaranowski/cloud-init
git push launchpad master
git push launchpad add-alexbaranowski-contributor
```

Then I can track that you have the authority to push content to the ~alexbaranowski launchpad account.

**Comment by AlexBaranowski** [comment]
Done :). 

https://code.launchpad.net/~alexbaranowski/cloud-init/+git/cloud-init/+ref/add-alexbaranowski-contributor

**Pull request merged**
