### PR TITLE
Ubuntu/impish: fix lintian

### PR DESCRIPTION
**Pull request by aciba90**
do not squash

[SC-1154](https://warthogs.atlassian.net/browse/SC-1154)

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Minor pending discussion on https://github.com/canonical/cloud-init/pull/1563 which applies here.

**Comment by aciba90** [comment]
> Minor pending discussion on #1563 which applies here.

Fixed, ready to be reviewed.

**Comment by aciba90** [comment]
> [#1566 (comment)](https://github.com/canonical/cloud-init/pull/1566#issuecomment-1177629649)

Done. Ready to be reviewed.

**Review by blackboxsw — APPROVED** [review]
- build-package/sbuild success lintian warnings squashed
- travis CI +1
- d/changelog  entry format, package versioning and separate commits +1
- will chat about augmented .XX.YY.1 vs ~XX.YY.1 diminished pacakge versioning  separately

**Pull request merged**
