### PR TITLE
Add deprecation log during init of DataSourceDigitalOcean

### PR DESCRIPTION
**Pull request by tyb-truth**
## Proposed Commit Message

```
Add deprecation log during init of DataSourceDigitalOcean
This PR adds a log warning of deprecation when DataSourceDigitalOcean is initialized. The DigitalOcean data source is not maintained and currently overridden in official DigitalOcean images with DataSourceConfigDrive.

Fixes GH-4172
```

Resolves https://github.com/canonical/cloud-init/issues/4172.

## Additional Context
More context: https://github.com/canonical/cloud-init/pull/4130#issuecomment-1573884030

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by tyb-truth** [comment]
@aciba90 I also see that there's a doc section for the DigitalOcean data source. Is there a specific format for deprecation notices in the official documentation I need to follow?

**Review by aciba90 — CHANGES_REQUESTED** [review]
Thanks, @tyb-truth, for improving cloud-init.

There is a [utility function](https://github.com/canonical/cloud-init/blob/529e108ca1b2e839539588c4cea040232440dbeb/cloudinit/util.py#L3159) to deprecate things that we could use.

I think we should also warn already spawned instances about this deprecation, to do so we could hook into the unpicking system on reboot.

<details>
  <summary>Unified diff including both suggestions.</summary>

```diff
diff --git a/cloudinit/sources/DataSourceDigitalOcean.py b/cloudinit/sources/DataSourceDigitalOcean.py
index fd2cff91b..a966fa28a 100644
--- a/cloudinit/sources/DataSourceDigitalOcean.py
+++ b/cloudinit/sources/DataSourceDigitalOcean.py
@@ -40,8 +40,10 @@ class DataSourceDigitalOcean(sources.DataSource):
                 BUILTIN_DS_CONFIG,
             ]
         )
-        LOG.warning(
-            "DataSourceDigitalOcean is deprecated in favour of DataSourceConfigDrive."
+        util.deprecate(
+            deprecated="DataSourceDigitalOcean",
+            deprecated_version="23.2",
+            extra_message="Deprecated in favour of DataSourceConfigDrive.",
         )
         self.metadata_address = self.ds_cfg["metadata_url"]
         self.retries = self.ds_cfg.get("retries", MD_RETRIES)
@@ -50,6 +52,14 @@ class DataSourceDigitalOcean(sources.DataSource):
         self.wait_retry = self.ds_cfg.get("wait_retry", MD_WAIT_RETRY)
         self._network_config = None
 
+    def _unpickle(self, ci_pkl_version: int) -> None:
+        super()._unpickle(ci_pkl_version)
+        util.deprecate(
+            deprecated="DataSourceDigitalOcean",
+            deprecated_version="23.2",
+            extra_message="Deprecated in favour of DataSourceConfigDrive.",
+        )
+
     def _get_sysinfo(self):
         return do_helper.read_sysinfo()
```

</details>

That will add the following message to the logs:

`WARNING: DataSourceDigitalOcean is deprecated in 23.2 and scheduled to be removed in 28.2. Deprecated in favour of DataSourceConfigDrive.`

@sutton-digitalocean could we get a +1 from your side? And please, any suggestion about the wording will be appreciated.

> I also see that there's a doc section for the DigitalOcean data source. Is there a specific format for deprecation notices in the official documentation I need to follow?

We could probably follow the format used in https://cloudinit.readthedocs.io/en/latest/reference/modules.html
Something in the lines of:

```rst
.. warning::
    Deprecated in version 23.2. Use ``DataSourceConfigDrive`` instead.
```

**Comment by sutton-digitalocean** [comment]
@aciba90 The unfied diff in your most recent comment LGTM. I've reached out internally to see if we have any resources for adding documents to the DigitalOcean support pages.

**Comment by tyb-truth** [comment]
Thanks for the suggestions, they look on the mark @aciba90, will look into it and the corresponding tests early next week (heading off on vacation till Tuesday)!

**Comment by aciba90** [comment]
Thanks, @tyb-truth, for the heads-up and taking care of it. Being the unit-test already there, I think it would be good to at least unit-test it.

**Review by aciba90 — CHANGES_REQUESTED** [review]
LGTM, thanks!

Could you please fix the [linting issues](https://github.com/canonical/cloud-init/actions/runs/5473848604/jobs/9969899321?pr=4194)?

**Review by aciba90 — CHANGES_REQUESTED** [review]
Thanks for addressing the linting issues.

Now there is another one. Could you please run `tox -e do_format` to format the code, and `tox -e check_format` to verify that all lints pass?

**Comment by tyb-truth** [comment]
> Thanks for addressing the linting issues.
> 
> Now there is another one. Could you please run `tox -e do_format` to format the code, and `tox -e check_format` to verify that all lints pass?

Apologies, I ran those on the `main` branch instead of my feature branch by accident. I'm running into some issues with `tox -e check_format` when it gets to the pylint command:

```
 python /Users/<..>/code/cloud-init/venv/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  pylint: FAIL code 2 (106.76=setup[55.01]+cmd[51.75] seconds)
  evaluation failed :( (107.02 seconds)
```
Changing the verbosity level in tox.ini testenv with `TOX_LOG_LEVEL=DEBUG PYTHONWARNINGS=default` only yields some deprecation warnings before that `_backend.py` file so I'm not sure how to proceed.

**Review by aciba90 — APPROVED** [review]
+1. Thanks, @tyb-truth, for driving this!

**Pull request merged**
