### PR TITLE
Ensure schemas for all modules starting A-D (SC-646)

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
Ensure schemas for all modules starting A-D

Provide/update schemas (including docs) for the following modules:
  cc_apk_configure
  cc_apt_configure
  cc_apt_pipelining
  cc_bootcmd
  cc_byobu
  cc_ca_certs
  cc_debug
  cc_disable_ec2_metadata
  cc_disk_setup
```

## Additional Context
Checked/Updated so that for every schema defintion we:
* define the schema and meta dictionaries per metaschema
* define `__doc__` using `get_meta_doc`
* call `validate_cloudconfig_schema` early in `handle`
* ensure `test_schema.py` passes
* generated docs look correct

For very large schema and doc definitions (e.g., apt configure and disk setup), I moved their definitions to their own files. At times I lean towards defining these in non-python files entirely, but most schemas are much smaller and simpler.

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — COMMENTED** [review]
Thanks for this first grouping @TheRealFalcon. I'd like to see us get some negative tests against the newly added schema keys/values in general to ensure the schema behaves as intended for certain types and values.

I cheated and took the easiest schema for an example of what I am hoping. I'll go through the rest of the schemas and validate behavior and conditionals as best I can tomorrow.

```diff
diff --git a/tests/unittests/config/test_cc_byobu.py b/tests/unittests/config/test_cc_byobu.py
new file mode 100644
index 00000000..947b6104
--- /dev/null
+++ b/tests/unittests/config/test_cc_byobu.py
@@ -0,0 +1,30 @@
+# This file is part of cloud-init. See LICENSE file for license information.
+
+import pytest
+
+from cloudinit.config.cc_byobu import schema
+from cloudinit.config.schema import validate_cloudconfig_schema
+from tests.unittests.helpers import skipUnlessJsonSchema
+
+
+@skipUnlessJsonSchema()
+class TestSchema:
+    @pytest.mark.parametrize(
+        "config,error_match",
+        (
+            (
+                {"byobu_by_default": 1},
+                "byobu_by_default: 1 is not of type 'string'",
+            ),
+            (
+                {"byobu_by_default": "bad-enum"},
+                "byobu_by_default: byobu_by_default: 'bad-enum' is not"
+                " one of ['enable-system', 'enable-user', 'disable-system',"
+                " 'disable-user', 'enable', 'disable', 'user', 'system']",
+            ),
+        ),
+    )
+    def test_invalid_schema(self, config, error_match):
+        """Errors are raised on invalid schema values."""
+        with pytest.raises(Exception, match=error_match):
+            validate_cloudconfig_schema(config, schema, strict=True)
```

**Comment by blackboxsw** [comment]
We mentioned before break about a potential overhaul of json schema definitions. What if we just used a single JSON file for the entire schema. It'd provide us the opportunity to do schema validation only once on the full userdata for the full schema. Here's what a strawman looks like for this doing a partial conversion of some of the A-C modules.
https://github.com/TheRealFalcon/cloud-init/pull/3/files

**Comment by blackboxsw** [comment]
I refactored @TheRealFalcon and migrated his schema definitions in this PR from legacy module-local schema attributes to consolidated static JSON schema in cloudinit/config/cloud-init-schema.json. schema failure cases are added for each definition.
https://github.com/canonical/cloud-init/pull/1211 The only module missing from this PR is cc_disk_setup

**Comment by TheRealFalcon** [comment]
Closing in favor of #1211

**Pull request closed without merging**
