### PR TITLE
Explicit set IPV6_AUTOCONF and IPV6_FORCE_ACCEPT_RA on static6

### PR DESCRIPTION
**Pull request by otubo**
## Proposed Commit Message
The static and static6 subnet types for network_data.json were
being ignored by the Openstack handler, this would cause the code to
break and not function properly.

As of today, if a static6 configuration is chosen, the interface will
still eventually be available to receive router advertisements or be set
from NetworkManager to wait for them and cycle the interface in negative
case.

It is safe to assume that if the interface is manually configured to use
static ipv6 address, there's no need to wait for router advertisements.
This patch will set automatically IPV6_AUTOCONF and IPV6_FORCE_ACCEPT_RA
both to "no" in this case.

This patch fixes the specific behavior only for RHEL flavor and
sysconfig renderer. It also introduces new unit tests for the specific
case as well as adjusts some existent tests to be compatible with the
new options. This patch also addresses this problem by assigning the 
appropriate subnet type for each case on the openstack handler.

rhbz: #1889635
rhbz: #1889635

Signed-off-by: Eduardo Otubo <otubo@redhat.com>

## Additional Context
This behavior was noticed while running tests for the PowerVM support on cloud-init (#584).

As a formality I posted only the first commit message on the "Proposed Commit Message" above. But it would be better if both patches could be merged separately, only to maintain the logical link between them.

## Test Steps
The bug can be verified by using the following `network_data.json` file:
```json
{
    "services": [
        {
            "type": "dns",
            "address": "9.0.128.50"
        },
        {
            "type": "dns",
            "address": "9.12.16.2"
        }
    ],
    "networks": [
        {
            "network_id": "2deaa60f-e9f4-4264-a25c-329aac1a77b1",
            "netmask": "255.255.255.0",
            "link": "tap6604fdd5-23",
            "mode": "auto",
            "routes": [
                {
                    "netmask": "0.0.0.0",
                    "network": "0.0.0.0",
                    "gateway": "60.0.0.1"
                }
            ],
            "ip_address": "60.0.0.247",
            "type": "ipv4",
            "id": "network0",
            "services": [
                {
                    "type": "dns",
                    "address": "9.0.128.50"
                },
                {
                    "type": "dns",
                    "address": "9.12.16.2"
                }
            ]
        },
        {
            "network_id": "mgmt",
            "netmask": "ffff:ffff:ffff:ffff::",
            "link": "interface1",
            "mode": "link-local",
            "routes": [],
            "ip_address": "fe80::c096:67ff:fe5c:6e84",
            "type": "static6",
            "id": "network1",
            "services": [],
            "accept-ra": "false"
        }
    ],
    "links": [
        {
            "ethernet_mac_address": "fa:61:e3:d8:59:20",
            "mtu": 1500,
            "type": "vif",
            "id": "tap6604fdd5-23",
            "vif_id": "6604fdd5-2312-433d-942e-729fa177fa66"
        },
        {
            "ethernet_mac_address": "c2:96:67:5c:6e:84",
            "mtu": null,
            "type": "vif",
            "id": "interface1",
            "vif_id": "mgmt_vif"
        }
    ]
}
```
With the net-convert tool:
```
cloud-init devel net-convert  -p ./network_data.json -k network_data.json -D rhel -d ./  -O sysconfig
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by smoser** [comment]
> As a formality I posted only the first commit message on the "Proposed Commit Message" above. But it would be better if both patches could be merged separately, only to maintain the logical link between them.

I think that if you want two commits on head (which I agree is useful sometimes) that you really need 2 PRs.

Maybe there is another way, but I don't know.

**Review by smoser — APPROVED** [review]
This looks fine to me.  I'm largely accepting that you've tested in real life, in addition to changing unit tests, as I can't personally vouch for the sysconfig settings.

**Comment by vijarad1** [comment]
Tested this on a Powervm based vm and it works fine. I have tried both type: ipv6 and also as type: static6 for IPV6 interface, both seems to be working fine

**Comment by otubo** [comment]
> > As a formality I posted only the first commit message on the "Proposed Commit Message" above. But it would be better if both patches could be merged separately, only to maintain the logical link between them.
> 
> I think that if you want two commits on head (which I agree is useful sometimes) that you really need 2 PRs.
> 
> Maybe there is another way, but I don't know.

Let's keep that in mind. @OddBloke or @blackboxsw have any inputs on this? Do I need to have another PR or you can manually squash my flake8 commit into 31999e9 and treat f1f1efb as a separate commit?

**Pull request merged**
