### PR TITLE
fix daily recipe ubuntu/noble new_upstream_snaphot to refresh quilt patches

### PR DESCRIPTION
**Pull request by blackboxsw**
Perform new_upstream_snapshot,py to sync unreleased tip of main into ubuntu/noble in order to fix daily recipe builds which are failing due to commit 9cc458c drift in systemd files which no-singleprocess.patch removes.

## Proposed Commit Message
-- see top three most recent separate commits

## Additional Context
[failed build recipe logs](https://launchpadlibrarian.net/748388534/buildlog.txt.gz) 
the error:
```

patching file systemd/cloud-init-main.service.tmpl
Hunk #1 FAILED at 1.
Not deleting file systemd/cloud-init-main.service.tmpl as content differs from patch
```

### steps to create this branch
```
new_upstream_snapshot.py # expect failure
quilt push -a
quilt push -f
rm systemd/cloud-init-main.service.tmpl
quilt refresh
quilt pop -a 
git commit -am 'refresh patches....'
new_upstream_snapshot.py -p quilt
# enter no SRU bug to leave UNRELEASED state
# manually add refreshed patches to d/changelog
```

## Test Steps
```
git checkout main
git pull
git reset --hard upstream/main
git merge ubuntu/noble
quilt push -a
tox -e py3
quilt pop -a
````

## Merge type
- [x] git push upstream ubuntu/noble from command line once approved
- [ ] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by holmanb** [comment]
@blackboxsw it looks like this has a rebase conflict

**Comment by blackboxsw** [comment]
> @blackboxsw it looks like this has a rebase conflict

shouldn't that rebase conflict be resolved via https://github.com/canonical/cloud-init/pull/5694/commits/26ed3949e82725bc17c0572d9ee3a81f28afef0c?

**Review by TheRealFalcon — APPROVED** [review]
LGTM! @holmanb , what do you mean by rebase conflict?

**Comment by TheRealFalcon** [comment]
Actually...should the changelog include the patch update?

**Comment by holmanb** [comment]
> LGTM! @holmanb , what do you mean by rebase conflict?

Screenshot from 2024-09-12 09-38-35

**Review by TheRealFalcon — APPROVED** [review]
LGTM! I don't see the rebase conflict, so I think whatever was there is gone now?

**Comment by holmanb** [comment]
> LGTM! I don't see the rebase conflict, so I think whatever was there is gone now?

+1 No problem on merging, I'm guessing the UI is just buggy since I haven't seen this before.

**Pull request merged**
