### PR TITLE
d/patches/ds-identify-behavior-xenial.patch: refresh against master

### PR DESCRIPTION
**Pull request by OddBloke**
## Additional Context

The failure to build can be seen here: https://code.launchpad.net/~cloud-init-dev/+archive/ubuntu/daily/+recipebuild/2673624

## Test Steps

I manually replicated the tree the recipe produces (merge `ubuntu/xenial` into `master`, then merge this PR branch into that) and confirmed that `quilt push -a` succeeds.

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by smoser** [comment]
For what its worth, this process is codified in new-upstream-snapshot with `--update-patches-only`

    $ rm -Rf *
    $ git checkout .
    Updated 912 paths from the index
    $ git remote -v | grep upstream
    upstream	https://github.com/canonical/cloud-init.git (fetch)
    upstream	https://github.com/canonical/cloud-init.git (push)
    $ git checkout upstream/ubuntu/xenial 
    HEAD is now at 2dc8c8eaa d/changelog: drop unaltered quilt patches from changelog
    $ SKIP_BRANCH_NAME_CHECK=1 new-upstream-snapshot --update-patches-only
    updating remote upstream for default commitish upstream/master.
    Applying ds-identify-behavior-xenial.patch failed: Applying patch ds-identify-behavior-xenial.patch
    patching file tools/ds-identify
    Hunk #1 FAILED at 93.
    Hunk #2 succeeded at 132 (offset 1 line).
    1 out of 2 hunks FAILED -- rejects in file tools/ds-identify
    Patch ds-identify-behavior-xenial.patch does not apply (enforce with -f)
    Dropping you into a shell. Either do
       a.) hand-apply fix ('quilt push -f' and 'quilt refresh'
       b.) remove the patch from debian/patches if no longer needed.
    
    When finished, 'exit 0'.
    To abort, exit 1.
    (refresh-fix)smoser@crabapple:~/src/cloud-init$ 
    (refresh-fix)smoser@crabapple:~/src/cloud-init$ quilt push -f
    Applying patch ds-identify-behavior-xenial.patch
    patching file tools/ds-identify
    Hunk #1 FAILED at 93.
    Hunk #2 succeeded at 132 (offset 1 line).
    1 out of 2 hunks FAILED -- saving rejects to file tools/ds-identify.rej
    Applied patch ds-identify-behavior-xenial.patch (forced; needs refresh)
    
    $ vi tools/ds-identify.rej vi tools/ds-identify
    ## make the change by hand.
    
    $ exit 0
    exit
    Removing patch renderer-do-not-prefer-netplan.patch
    Restoring tests/unittests/test_render_cloudcfg.py
    Restoring config/cloud.cfg.tmpl
    
    Removing patch ec2-dont-apply-full-imds-network-config.patch
    Restoring tests/unittests/test_datasource/test_ec2.py
    Restoring cloudinit/sources/DataSourceEc2.py
    
    Removing patch ubuntu-advantage-revert-tip.patch
    Restoring cloudinit/config/tests/test_ubuntu_advantage.py
    Restoring cloudinit/config/cc_ubuntu_advantage.py
    
    Removing patch ec2-classic-dont-reapply-networking.patch
    Restoring cloudinit/sources/DataSourceEc2.py
    
    Removing patch azure-apply-network-config-false.patch
    Restoring cloudinit/sources/DataSourceAzure.py
    
    Removing patch openstack-no-network-config.patch
    Restoring tests/unittests/test_datasource/test_openstack.py
    Restoring cloudinit/sources/DataSourceOpenStack.py
    
    Removing patch stable-release-no-jsonschema-dep.patch
    Restoring requirements.txt
    
    Removing patch ds-identify-behavior-xenial.patch
    Restoring tools/ds-identify
    
    No patches applied
    [detached HEAD 09379050b] refresh patches against upstream/master commit cf6c36a1
     6 files changed, 20 insertions(+), 30 deletions(-)
    [detached HEAD 35a3b7775] update changelog.
     1 file changed, 12 insertions(+)
    No patches updated. Nothing to commit.
    
    $ git log
    commit 35a3b77758e7b4dd0372d7678d3a5092a1353428 (HEAD)
    Author: Scott Moser <smoser@brickies.net>
    Date:   Wed Nov 4 12:13:50 2020 -0500
    
        update changelog.
    
    commit 09379050bafc95269a368fdd1d9271b34a2ac92c
    Author: Scott Moser <smoser@brickies.net>
    Date:   Wed Nov 4 12:13:50 2020 -0500
    
        refresh patches against upstream/master commit cf6c36a1
        
        refresh patches against upstream/master commit cf6c36a1:
          debian/patches/azure-apply-network-config-false.patch
          debian/patches/ds-identify-behavior-xenial.patch
          debian/patches/ec2-classic-dont-reapply-networking.patch
          debian/patches/ec2-dont-apply-full-imds-network-config.patch
          debian/patches/openstack-no-network-config.patch
          debian/patches/renderer-do-not-prefer-netplan.patch
    
    commit 077e5b340041b296ba441299190a6ee436a85b8e
    Merge: 2dc8c8eaa cf6c36a18
    Author: Scott Moser <smoser@brickies.net>
    Date:   Wed Nov 4 12:11:54 2020 -0500
    
        merge from upstream/master at 20.3-73-gcf6c36a1

**Comment by igalic** [comment]
I'm so sorry._. 🙇🏻‍♀️

**Comment by OddBloke** [comment]
On Wed, Nov 04, 2020 at 02:34:23PM -0800, Mina Galić wrote:
> I'm so sorry._. 🙇🏻‍♀️ 

No need to be, this is just a regular part of distro maintenance!

**Review by smoser — APPROVED** [review]
I can approve this.  But my personal feeling is you should use the tools in place to do it.

**Pull request merged**
