### PR TITLE
- Fix typo iff -> if in comment

### PR DESCRIPTION
**Pull request by rjschwei**
## Proposed Commit Message
Fix typo in comment

## Additional Context
N/A

## Test Steps
N/A

## Checklist:

 - [x ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by mitechie — APPROVED** [review]

**Comment by mitechie** [comment]
Thank you for the fix.

**Comment by mitechie** [comment]
Looks like something hung between Github and Travis. Travis shows the build as success but Github says it's "build created" for a day and change. I'm going to see if I can close this and reopen it and reset the status there.

**Review by smoser — COMMENTED** [review]
FWIW ("for what it's worth"), `iff` is not really a typo.  It is math/logic shorthand for "if and only if". https://en.wikipedia.org/wiki/If_and_only_if.

My spelling out "fwiw" above was an attempt at a joke (I don't want to come off as rude :wink:).
You are welcome to make the change.  `iff` is also used in `cloudinit/net/network_state.py`.

**Comment by rjschwei** [comment]
OK, learned something new. Thanks.

**Pull request closed without merging**
