### PR TITLE
Simplify systemd service files

### PR DESCRIPTION
**Pull request by holmanb**
## Additional Context
https://github.com/canonical/cloud-init/issues/5818

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [x] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Comment by Jalle19** [comment]
This introduces a regression on non-Ubuntu systems. cloud-final.service now suddenly has `After=multi-user.target` which causes cyclic dependencies for any unit that is WantedBy multi-user.target and depends on cloud-final.service.

Noticed this on Rocky Linux that recently upgraded from cloud-init 23.4 to 24.4.

**Comment by holmanb** [comment]
> cloud-final.service now suddenly has After=multi-user.target which causes cyclic dependencies for any unit that is WantedBy multi-user.target and depends on cloud-final.service.

I wasn't able to reproduce. Can you please include the service file of the affected service?

I created `/etc/systemd/system/my-service.service` which contained:
```
[Unit]
Description=my service
After=cloud-final.service

[Service]
Type=oneshot
ExecStart=sh -c 'echo "hi world"'

[Install]
WantedBy=multi-user.target
```

Then I enabled the service `systemctl enable my-service.service` and did a `cloud-init clean --reboot`.

On reboot I see:
```
Jul 03 22:10:01 profound-hippo systemd[1]: Starting my service...
Jul 03 22:10:01 profound-hippo sh[186]: hi world
Jul 03 22:10:01 profound-hippo systemd[1]: my-service.service: Deactivated successfully.
Jul 03 22:10:01 profound-hippo systemd[1]: Finished my service.
```

This is with 25.1.2 on arch, which includes the `multi-user.target` dependency:

```
$ cloud-init --version
/usr/bin/cloud-init 25.1.2
```

**Comment by Jalle19** [comment]
Add Wants=cloud-final.service too

**Comment by holmanb** [comment]
@Jalle19 I was able to reproduce this. `Wants=cloud-final.service` isn't necessary to reproduce, but systemd isn't making any noise in the journal about breaking the cycle.

The issue is that systemd automatically adds a `Before=multi-user.target` to your service. You can eliminate the cycle by adding `After=multi-user.target` to your service file. Compare:

cycle
```ini
[Unit]
Description=my service
After=cloud-final.service

[Service]
Type=oneshot
ExecStart=sh -c 'echo "hi world"'

[Install]
WantedBy=multi-user.target
```

no cycle
```ini
[Unit]
Description=my service
After=cloud-final.service multi-user.target

[Service]
Type=oneshot
ExecStart=sh -c 'echo "hi world"'

[Install]
WantedBy=multi-user.target
```

**Comment by Jalle19** [comment]
Seems counter-intuitive, haven't seen anyone use the same service in After and WantedBy before. I'd appreciate if the recommended approach to create systemd services that depend on cloud-init was documented somewhere canonically.

**Comment by holmanb** [comment]
>  I'd appreciate if the recommended approach to create systemd services that depend on cloud-init was documented somewhere canonically.

Agreed, we should do that.

**Pull request merged**
