### PR TITLE
doc: add diagram with boot stages

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
doc: add diagram with boot stages

SC-1835
Fixes GH-5334
```

## Test Steps

```
tox -e doc && (cd doc/rtd_html/ && python3 -m http.server)
open http://0.0.0.0:8000/explanation/boot.html
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by aciba90** [comment]
Diff:

image

**Review by s-makin — COMMENTED** [review]
Looks really good!

I only have two real suggestions for changes. 
1) Can we make the diagram vertical rather than horizontal? Where it gets sized to fit on the screen width it makes the text quite small. I think a vertical approach would avoid that problem and also make it easier for people to view on smaller screens.
2) Can we make the "Detect" box yellow as well? I think since we have the list of stages at the top, and the other four are in the larger yellow boxes, it would make it nicely correspond to the list if all the main stages looked the same as each other in the diagram

**Comment by a-dubs** [comment]
> Can we make the "Detect" box yellow as well? I think since we have the list of stages at the top, and the other four are in the larger yellow boxes, it would make it nicely correspond to the list if all the main stages looked the same as each other in the diagram

@aciba90 @s-makin Is "detect" an actual stage of cloud-init? If not, shouldn't it be left as is so that only official cloud-init stages are given yellow boxes?

**Comment by holmanb** [comment]
> > Can we make the "Detect" box yellow as well? I think since we have the list of stages at the top, and the other four are in the larger yellow boxes, it would make it nicely correspond to the list if all the main stages looked the same as each other in the diagram
> 
> @aciba90 @s-makin Is "detect" an actual stage of cloud-init? If not, shouldn't it be left as is so that only official cloud-init stages are given yellow boxes?

A small legend which describes the differences would give the boxes and color more meaning to users.

It might make sense to break out [the boot page](https://docs.cloud-init.io/en/latest/explanation/boot.html) into a "logical" main page with "implementation" sub-pages so that we can talk about the systemd implementation (and other implementations) in more detail without making the logical boot stages page too busy.

**Comment by a-dubs** [comment]
+ 1 to @holmanb's idea about breaking out into more details sub pages. But just to be clear, that work should be captured in an issue and tackled separately, right?

**Review by s-makin — APPROVED** [review]
LGTM :)

**Comment by blackboxsw** [comment]
Taking [this comment](https://github.com/canonical/cloud-init/pull/5539#issuecomment-2248642808) as a separate issue to follow up on separately

**Review by blackboxsw — APPROVED** [review]
diagram looks good. I changed diagram alignment to be top to bottom TB and provided supplemental links to various boot stage sections in this page so others can dig into details easily by clicking elements in the diagram.

**Pull request merged**
