### PR TITLE
Check for updates to GitHub Actions every weekday

### PR DESCRIPTION
**Pull request by jlosito**

### CODE REVIEW

**Comment by igalic** [comment]
what's that do if there's an update?

**Comment by jlosito** [comment]
It should create a PR with the proposed version change.

**Comment by jlosito** [comment]
The same could be done for python packages.

**Comment by jlosito** [comment]
@OddBloke I submitted the PR as a individual contributor. 

I don't believe this is an IS requirement. It might not be worth it then.

Feel free to reject this.

**Comment by OddBloke** [comment]
Yep, I think I will go ahead and close this out. Nevertheless, thanks for taking the time to propose it!

**Pull request closed without merging**
