### PR TITLE
fix: Use monotonic time

### PR DESCRIPTION
**Pull request by holmanb**
```
fix: Use monotonic time

Prevent time change races.
```

### CODE REVIEW

**Comment by a-dubs** [comment]
Why is this change only needed in these two package related source files?

**Comment by holmanb** [comment]
> Why is this change only needed in these two package related source files?

After https://github.com/canonical/cloud-init/pull/5420 lands, I *think* these are the only remaining spots where `time()` was used to diff against `time()` in cloud-init. There are a few spots in cloud-init where `time()` compares against system uptime, which could also be problematic, but those are harder to solve.

**Review by a-dubs — CHANGES_REQUESTED** [review]
Any chance you want to add typehints and a docstring to `_fire_reboot`? :P

**Review by TheRealFalcon — APPROVED** [review]
LGTM!

**Pull request merged**
