### PR TITLE
Add 'peers' and 'allow' directives in cc_ntp

### PR DESCRIPTION
**Pull request by jacobsalmela**
## Proposed Commit Message

```
Adds the 'peer' and 'allow' directives to the NTP template.  This also adds additional debug logging for these settings.
```

## Additional Context

When deploying NTP servers and peers in a complex system, these additional settings enable the hostnames and IP ranges to be dynamically set in the config file.

## Test Steps

Set a `peers` or `allow` directive in the template and run the NTP module.

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by dermotbradley** [comment]
Hi. You haven't updated any of the chrony or ntpd template files to actually make use of either "peer" or "allow" (Chrony supports both, ntpd seems to only support "peer").

**Comment by jacobsalmela** [comment]
I will do that.

**Comment by TheRealFalcon** [comment]
Thanks for the contribution @jacobsalmela ! Generally this change looks good to me.

I noticed you signed the CLA, but haven't yet added yourself to the CLA signers file. As part of this PR, please also add your name (alphabetically) to [the CLA signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers). The full details are described in the last bullet point [of the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request).

Additionally, some formatting related changes are failing. You can fix this by running
`tox -e do_format` and check it with `tox -e check_format` (or run all checks running `tox` without arguments).

**Comment by jacobsalmela** [comment]
Thanks for the guidance @TheRealFalcon, apologies I missed it first time around.  

The test passed locally now, so LMK if you see the same on your end.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
