### PR TITLE
Ubuntu/focal: Drop d/p/revert-dhcp6-on-ec2.patch and fix dailies

### PR DESCRIPTION
**Pull request by TheRealFalcon**
https://github.com/canonical/cloud-init/pull/5145#pullrequestreview-1982462921 .

Due to merge conflicts, this was mostly manual.

My process:
```
$ git merge --strategy-option=theirs upstream/main -m "merge from upstream/main"
# No idea why these persist...
$ git checkout main -- cloudinit/sources/DataSourceEc2.py
$ git checkout main -- tests/unittests/net/test_dhcp.py
$ git checkout main -- tests/unittests/sources/test_ec2.py
$ git diff --name-only main  # Ensure nothing outside the debian directory shows up
$ git commit --amend  # keep the message

# as mentioned in https://github.com/canonical/cloud-init/pull/5145#pullrequestreview-1982462921
$ git revert 172d42cf7306d167df6da965bcf773ba6de582cc
# Update changelog to remove d/p/revert-dhcp6-on-ec2.patch section. Then...
$ git commit -am "update changelog"
$ new_upstream_snapshot.py
# Edit d/changelog to merge patch refresh and remove old upstream snapshot line, then amend latest commit with these changes.
```

### CODE REVIEW

**Comment by holmanb** [comment]
is this a duplicate of https://github.com/canonical/cloud-init/pull/5151?

**Comment by holmanb** [comment]
oh I see it's also finishing what https://github.com/canonical/cloud-init/pull/5154 started

**Comment by holmanb** [comment]
@TheRealFalcon I didn't have

**Comment by holmanb** [comment]
@TheRealFalcon Mine looks very different after this process - did you start with an up-to-date `ubuntu/focal` branch?

All of the following succeeded for me:
```
git reset --hard upstream/ubuntu/focal
git merge --strategy-option=theirs upstream/main -m "merge from upstream/main"
git revert 172d42cf7306d167df6da965bcf773ba6de582cc
new_upstream_snapshot.py
```

**Comment by TheRealFalcon** [comment]
@holmanb , what happens if you run `git diff --name-only  main` after `git merge ...` ?

For me, I still have 3 files ouside of the debian directory with changes. That shouldn't be happening on an upstream snapshot, correct?

**Review by holmanb — APPROVED** [review]
My bad, I had a stale git cache. Looks good to me!

**Pull request merged**
