### PR TITLE
Do not override existing value for PYTHON and do not hardocde the binary in unittest target

### PR DESCRIPTION
**Pull request by Jehops**

### CODE REVIEW

**Review by igalic — APPROVED** [review]
👍

**Comment by TheRealFalcon** [comment]
Hi @Jehops . The change here looks good, but before we can accept your change, you need to sign [the CLA](https://ubuntu.com/legal/contributors/agreement) and add your Github username (alphabetically) to [the cla signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) . The full details are described in the last bullet point [of the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#submitting-your-first-pull-request)

**Comment by Jehops** [comment]
Hi @TheRealFalcon.  I signed the CLA and proposed to add my GitHub username to the cla signers file.

**Comment by holmanb** [comment]
> ... and proposed to add my GitHub username to the cla signers file.

@Jehops I don't see that in this PR or any other open ones at the moment. Do you have a link to the PR?

**Comment by Jehops** [comment]
@holmanb Sorry, I thought editing the filing through the web interface submitted the pull request, but it just created a new branch in my fork.  [Here is a new pull request](https://github.com/canonical/cloud-init/pull/1784).

**Comment by holmanb** [comment]
> @holmanb Sorry, I thought editing the filing through the web interface submitted the pull request, but it just created a new branch in my fork.  [Here is a new pull request](https://github.com/canonical/cloud-init/pull/1784).

No problem, thanks 👍

**Review by TheRealFalcon — APPROVED** [review]
Just needs a rebase now

**Comment by TheRealFalcon** [comment]
Thanks for the contribution!

**Pull request merged**
