### PR TITLE
Correct documentation and testcase data for some user-data YAML

### PR DESCRIPTION
**Pull request by dermotbradley**
## Proposed Commit Message

For cc_users_groups the user setting "expiredate" **must be quoted** in order for the
relevant flag and value to be then passed to the useradd command. It its vaiue is not
quoted then it is treated as Python type datetime.date and in ```cloudinit/distros/__init__.py```
the below "_is it a string_" condition fails and so no "--expiredate" parameter is passed
to useradd and therefore it has no effect:

```
if key in useradd_opts and val and isinstance(val, str):
    useradd_cmd.extend([useradd_opts[key], val])
```

For cc_users_groups, the user setting "inactive" does not actually disable
accounts, the useradd "--inactive" option actually defines the number of
days after password expiry that users can still login. So I have changed
the docs to show it taking a **quoted** value of days (which works with the
current code) rather than a boolean value. **The quotes are necessary**,
like expiredate above, so that the value is also passed to the useradd command.

For cc_power_state_change.py the "delay" setting value needs to have quotes around
it **as otherwise its leading plus sign will be stripped off**.

## Additional Context

freebsd.py, which doesn't use useradd, *already* has broken handling of
"inactive" as it passes a non-existant "-E" option to the "pw useradd"
command - it should actually pass "-e" instead followed by ```+<DAYS>d```.

I talked to @goneri and @OddBloke about this on IRC.

The existing testcases for users haven't picked up on "expiredate" and
"inactive" not working as they don't check/mock /etc/shadow where
these values end up. I see the testcases using "getent passwd" but
**"getent shadow" will not work when running testcases as a non-root user**.

## Test Steps

User-data:

```
power_state:
  delay: '+5'
users:
  - name: testuser
    expiredate: '2020-12-25'
    gecos: Test User
    inactive: '5'
```

Afterwards check the "testuser" entry in /etc/shadow:

```
grep testuser /etc/shadow
testuser:<ENCRYPTED PASSWORD>:<LAST PWD CHANGE>:<MIN AGE>:<MAX AGE>:<WARN>:<INACTIVITY>:<EXPIRE DATE>:
```
where ```<INACTIVITY>``` is the number specified by "inactive" user-data and ```<EXPIRE DATE>``` is the value of "expiredate" as number of days from 1/1/1970.

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/hacking.html)
 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by dermotbradley** [comment]
@OddBloke as discussed on IRC yesterday.

**Comment by dermotbradley** [comment]
@goneri @igalic as you appear to be the resident BSD experts, as mentioned in the comments above:

freebsd.py, which doesn't use useradd, currently has broken handling of "inactive"
as it passes a non-existant "-E" option to the "pw useradd" command - it should
actually pass "-e" instead followed by ```+<DAYS>d```.

This was discussed on IRC with @OddBloke and @goneri on 19th Oct.

**Comment by TheRealFalcon** [comment]
Is there a reason the yaml values need quotes as opposed to using plain scalars?

**Comment by dermotbradley** [comment]
> Is there a reason the yaml values need quotes as opposed to using plain scalars?

Yes, I had updated the description shortly before your comment to clarify the reasoning. - Basically the code in ```cloudinit/distro/__init__.py``` that builds up a "useradd" command line will only use these values if they are Python string objects - using quotes for the values of "expiredate" and "inactive" ensure they are string objects, not datetime or int respectively.

Likewise the value for power state's "delay" is supposed to be either ```now``` or ```+number```, the quotes are necessary to retain the leading plus symbol.

**Review by OddBloke — APPROVED** [review]
LGTM, and I've confirmed that the test steps work locally. Thanks!

**Comment by dermotbradley** [comment]
> LGTM, and I've confirmed that the test steps work locally. Thanks!

Thanks @OddBloke 

The "expiredate" and "inactive" changes wouldn't cause any testcase failures **as there are no testcases that actually check if these work or not** - to do so would require either checking the resultant contents of /etc/shadow (a root-only readable file) or to mock /etc/shadow.

Also as mentioned above, "inactive" has never worked for FreeBSD at all as it is passing an invalid command-line option to the "pw" tool. Someone with BSD expertise would need to look into that.

**Comment by OddBloke** [comment]
> The "expiredate" and "inactive" changes wouldn't cause any testcase failures **as there are no testcases that actually check if these work or not** - to do so would require either checking the resultant contents of /etc/shadow (a root-only readable file)

Root ownership shouldn't be an issue in our integration tests; we assume that we're logging in as a user with sudo access.

> or to mock /etc/shadow.

This could work too, though I suspect to really see these issues we'd need a full-stack test which is probably more appropriate as an integration test anyway: if the test doesn't exercise the YAML->Python boundary *and* the Python->filesystem boundary then it's not covering what we need here and something covering those two boundaries does not sound like a unit test to me. (Any interest in expanding https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/modules/test_users_groups.py#L43-L68 to cover this case? I think adding/modifying the user-data for these cases, adding parameters to `test_users_groups` and prepending `sudo` to the `getent` call would do the trick?)

> Also as mentioned above, "inactive" has never worked for FreeBSD at all as it is passing an invalid command-line option to the "pw" tool. Someone with BSD expertise would need to look into that.

+1.

Thanks again!

**Pull request merged**
