### PR TITLE
clarify OpenNebula example

### PR DESCRIPTION
**Pull request by igalic**
- use `sh` as highlight language of the code block
- change order so that the confusing indentation is less confusing

### CODE REVIEW

**Review by OddBloke — COMMENTED** [review]
I'm +1 on the syntax highlighting, that's way easier to read. Are we sure that we can safely reorder the items in here? I'm not familiar with this configuration format, so don't want to assume that something that looks like a key-value mapping actually _is_.

**Comment by igalic** [comment]
perhaps we can ask someone from OpenNebula?

**Comment by km4rcus** [comment]
@igalic @OddBloke it is safe to reorder items (Attribute=value) in the CONTEXT section.

**Review by OddBloke — APPROVED** [review]
LGTM, thanks for the improvement. And thanks to @km4rcus for the confirmation!

**Pull request merged**
