### PR TITLE
Release 24.1

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message
```
Release 24.1

Bump the version in cloudinit/version.py to 24.1 and update ChangeLog.
```

## Additional Context
Steps:

1. pushed new branch 24.1.x which matches upstream main
2. `upstream-release 24.1 23.4.4`
3. redact minor release changelog entries

## Merge type

- [ ] Squash merge using "Proposed Commit Message"
- [x] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
LGTM! I would just ensure @blackboxsw 's release notes don't also include any changelog changes too

**Review by blackboxsw — COMMENTED** [review]
LGTM. only minor ChangeLog diff to avoid duplicate entries given previous release 23.4.1-4 Changelog entries sync'd earlier from hotfix branch
```diff
--- a/ChangeLog
+++ b/ChangeLog
@@ -13,8 +13,6 @@
  - test: Fix xfail to check the dhcp client name (#4971)
  - tests: avoid console prompts when removing gpg on Noble
  - test: fix test_get_status_systemd_failure
- - fix(nocloud): smbios datasource definition
- - tests: Check that smbios seed works
  - fix: Remove hardcoded /var/lib/cloud hotplug path (#4940)
  - refactor: Refactor status.py (#4864)
  - test: Use correct lxd network-config keys (#4950)
@@ -94,7 +92,6 @@
  - fix(schema cli): avoid netplan validation on net-config version 1
  - tests: reduce expected reports due to dropped rightscale module
  - tests(net-config): add awareness of netplan on stable Ubuntu
- - fix(source): fix argument boundaries when parsing cmdline (#4825)
    [Gilbert Gilb's]
  - feat: fall back to cdrom_id eject if eject is not available (#4769)
    [Cat Red]
@@ -208,7 +205,6 @@
  - doc: Document boot status meaning (#4670)
  - doc: Set expectations for new datasources (#4670)
  - ci: Show linkcheck broken links in job output (#4670)
- - fix: Handle systemctl commands when dbus not ready (#4681)
  - dmi: Add support for OpenBSD (#4654) [Mina Galić]
  - ds-identify: fake dmidecode support on OpenBSD (#4654) [Mina Galić]
  - ds-identify: add OpenBSD support in uname (#4654) [Mina Galić]
```

**Review by blackboxsw — APPROVED** [review]
approved given minor diff ti Changelog to redact duplicates. not critical if you want to avoid that work.

**Comment by TheRealFalcon** [comment]
I just noticed that this PR wasn't again main. This should go into main too

**Pull request merged**
