### PR TITLE
nocloud: drop work around for Linux 2.6

### PR DESCRIPTION
**Pull request by goneri**
These two lines were a requirement for RHEL6, and they have been added 7
years ago:

- https://github.com/canonical/cloud-init/commit/984c72e522c585c6d3f6b3d3aec39fb21dd84028
- https://github.com/canonical/cloud-init/commit/48a3b4ca0ba55699825d6eabe75d843286c23545

RHEL6 comes with Python 2.6, since Python3 is now a strong requirement, I
think it's save to remove this hack.

### CODE REVIEW

**Comment by OddBloke** [comment]
> RHEL6 comes with Python 2.6, since Python3 is now a strong requirement, I think it's save to remove this hack.

This is conflating Python versions and kernel versions (which both happened to be 2.6 in RHEL 6, I think). I'm not 100% sure that we can remove these lines, as I don't know if this was fixing behaviour in old kernels at the time, or new kernels at the time (in which case it may still be necessary).

**Comment by goneri** [comment]
> > RHEL6 comes with Python 2.6, since Python3 is now a strong requirement, I think it's save to remove this hack.
> 
> This is conflating Python versions and kernel versions (which both happened to be 2.6 in RHEL 6, I think). I'm not 100% sure that we can remove these lines, as I don't know if this was fixing behaviour in old kernels at the time, or new kernels at the time (in which case it may still be necessary).

If it was still a thing, we would have similar workaround for the other CDROM providers.

**Comment by raharper** [comment]
Just to confirm, this is still needed on Centos6 images:

```
wget https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2
qemu-system-x86_64 -smp 2 -m 1024 --enable-kvm -snapshot \
    -drive id=disk0,if=none,format=qcow2,file=CentOS-6-x86_64-GenericCloud.qcow2 \
    -device virtio-blk-pci,drive=disk0,bootindex=0 \
    -cdrom seed.img \
    -net user,hostfwd=tcp::22222-:22 \
    -net nic,model=virtio -monitor stdio \
    -vnc 0.0.0.0:0 \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-pci,rng=rng0 \
    -serial telnet:localhost:2446,nowait,server

% ssh -p 22222 centos@localhost
Warning: Permanently added '[localhost]:22222' (RSA) to the list of known hosts.
X11 forwarding request failed on channel 0
[centos@localhost ~]$
[centos@localhost ~]$ cat /etc/blkid/blkid.tab
<device DEVNO="0x0b00" TIME="1587667708.419166" LABEL="cidata" TYPE="iso9660">/dev/sr0</device>
<device DEVNO="0xfc01" TIME="1587667708.428031" UUID="1768745c-f048-4534-851c-f8a47ce987bb" TYPE="ext4">/dev/vda1</device>
[centos@localhost ~]$ sudo bash
[root@localhost centos]# mv /etc/blkid/blkid.tab .
[root@localhost centos]# blkid
/dev/vda1: UUID="1768745c-f048-4534-851c-f8a47ce987bb" TYPE="ext4"
[root@localhost centos]# blkid -tTYPE=iso9660
[root@localhost centos]# blkid /dev/sr0
/dev/sr0: LABEL="cidata" TYPE="iso9660"
[root@localhost centos]# blkid -tTYPE=iso9660
/dev/sr0: LABEL="cidata" TYPE="iso9660"
[root@localhost centos]# uname -r
2.6.32-754.17.1.el6.x86_64
[root@localhost centos]# rpm -qa | grep util-linux
util-linux-ng-2.17.2-12.28.el6_9.2.x86_64
```

**Comment by goneri** [comment]
So CentOS6 is still supported?

**Comment by raharper** [comment]
No, you're right, Centos6 is py26 so not on master.

**Pull request merged**
