### PR TITLE
Updated OpenStack default timeouts

### PR DESCRIPTION
**Pull request by eandersson**
In some rare cases, the metadata service may not be reachable at the very first attempt. Other cloud-init sources set max_wait and the timeout to higher values to help combat this; e.g. the EC2 and CloudStack sources. Lets do the same for OpenStack to make sure that we give it ample time to detect the metadata service.

### CODE REVIEW

**Comment by eandersson** [comment]
@powersj if you have time can you please take a look

**Comment by powersj** [comment]
@eandersson someone will get back to you soon! thanks for the ping

**Comment by OddBloke** [comment]
@eandersson Apologies for the delay!

@smoser @raharper We had a conversation about this in #cloud-init (on 7/24, if you want to find it in your logs), and I don't feel like we came to a solid agreement about whether this was appropriate.

The primary issue raised was that non-Intel systems don't use `ds-identify` and therefore run through all configured datasources: bumping this timeout could substantially impact boot speed of non-Intel systems on non-OpenStack platforms.

What do you think to landing this?

**Comment by raharper** [comment]
Can we get logs of the failure?

Previous timeouts where seen at *local* time when bringing up EphemeralDHCP due to cloud-init not handling classless-static-routes; then cloud-init would write a dhcp config on eth0, when dhcp came up it correctly configured the routes and the datasource was then reachable.  I'd like to confirm that this is not that bug. 

https://bugs.launchpad.net/cloud-init/+bug/1821102

**Comment by eandersson** [comment]
Examples of failures
`Giving up on OpenStack md from ['http://169.254.169.254/openstack'] after 0 seconds`
`[10/-1s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /openstack (Caused by ConnectTimeoutError`
`'Connection aborted.', error(101, 'Network is unreachable'`

There are many reasons why you may hit one of these issues, and I fully understand that it may cause other slowdowns, but not even having the code retry once is a little too aggressive in my opinion. I would be open to raising it from -1 (zero retries), to something like retry for 10 seconds? Maybe a better solution would be to skip on reasonable HTTP return codes like 404 when hitting the /openstack url?

**Comment by raharper** [comment]
After a long IRC discussion, thanks @eandersson ; the reason for not retrying at all is that cloud-init's datasource has a default url_param.max_wait = -1  which when url_helper.py:wait_for_url() runs, that setting makes it try exactly *once*.

Other important points;  On Xenial (and non-x86 architectures on newer releases, or any OS using cloud-init without ds-identify) OpenStack would then attempt to hit it's IMDS for 120 seconds; this likely would impact Ubuntu Xenial on EC2)

We should test an EC2 Xenial instance with the suggested changes in the PR, cloud-init clean --logs --reboot and observe the new total time as way to capture the potential impact.

**Comment by powersj** [comment]
I think this was autoclosed. I know there was some discussion on IRC and some asks above. Should this actually be closed?

**Comment by raharper** [comment]
No, it should remain open; generally we are awaiting testing as described earlier.

**Comment by mitechie** [comment]
Thanks, yes this should be open and it's on the queue to get the testing done after we get the 20.3 release set. Thanks for your patience.

**Comment by powersj** [comment]
@raharper 

> After a long IRC discussion, thanks @eandersson ; the reason for not retrying at all is that cloud-init's datasource has a default url_param.max_wait = -1 which when url_helper.py:wait_for_url() runs, that setting makes it try exactly _once_.
> 
> Other important points; On Xenial (and non-x86 architectures on newer releases, or any OS using cloud-init without ds-identify) OpenStack would then attempt to hit it's IMDS for 120 seconds; this likely would impact Ubuntu Xenial on EC2)
> 
> We should test an EC2 Xenial instance with the suggested changes in the PR, cloud-init clean --logs --reboot and observe the new total time as way to capture the potential impact.

Does this boil down to:

1. Boot EC2 c5.large instance with Xenial
2. `cloud-init analyze > before`
2. Make the change on the system
3. `cloud-init clean --logs --reboot`
4. `cloud-init analyze > after`

And then report back the difference?

Does this also need to happen on an EC2 arm64 instance?

**Comment by powersj** [comment]
@raharper thoughts on my comment above?

**Comment by raharper** [comment]
> @raharper
>
> > After a long IRC discussion, thanks @eandersson ; the reason for not retrying at all is that cloud-init's datasource has a default url_param.max_wait = -1 which when url_helper.py:wait_for_url() runs, that setting makes it try exactly _once_.
> > Other important points; On Xenial (and non-x86 architectures on newer releases, or any OS using cloud-init without ds-identify) OpenStack would then attempt to hit it's IMDS for 120 seconds; this likely would impact Ubuntu Xenial on EC2)
> > We should test an EC2 Xenial instance with the suggested changes in the PR, cloud-init clean --logs --reboot and observe the new total time as way to capture the potential impact.
>
> Does this boil down to:
>
>     1. Boot EC2 c5.large instance with Xenial
>
>     2. `cloud-init analyze > before`
>
>     3. Make the change on the system
>
>     4. `cloud-init clean --logs --reboot`
>
>     5. `cloud-init analyze > after`
>
>
> And then report back the difference?

Yes, though please do caputure cloud-init.log and journals.

>
> Does this also need to happen on an EC2 arm64 instance?

We should test x86 and arm64; the reason is that non-x86 arches on OpenStack
must return ds_maybe since there isn't a non-network way to detect if an
instance is on OpenStack (ie no DMI setting).

We want to test how much time penalty will occur on Ec2 with the changes as on
Xenial, cloud-init still returns a full list of Datasources to try;

**Comment by powersj** [comment]
I tested in AWS using these Ubuntu 16.04 LTS AMIs (us-west-2):

* `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20201210` - `ami-00f1e37d20049f858` 
* `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-arm64-server-20201210` - `ami-020d314a20e95e9d3`

## C5.large results
### 1st Boot Results

* [/var/log/cloud-init.log](https://paste.ubuntu.com/p/HmBWkPyBfT/)
* [/var/log/cloud-init-output.log](http://paste.ubuntu.com/p/hkqDC7HGsY/)
* [cloud-init analyze blame](http://paste.ubuntu.com/p/MttbR5wfR6/)
* [cloud-init analyze show](http://paste.ubuntu.com/p/k3QFdyQqQt/)
* [cloud-init analyze boot](http://paste.ubuntu.com/p/ZNc9B8zMCS/)
* [journalctl --no-pager -b -x](http://paste.ubuntu.com/p/3dN2GRgxdM/)

### Branch Applied

Edited `/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOpenStack.py` with the 2 line change. Deleted the pycache file for DataSourceOpenStack.py. Ran `sudo cloud-init clean --logs --reboot`

### 2nd Boot Result

* [/var/log/cloud-init.log](http://paste.ubuntu.com/p/CzynhZw4Dy/)
* [/var/log/cloud-init-output.log](http://paste.ubuntu.com/p/H8rNPvxwHw/)
* [cloud-init analyze blame](http://paste.ubuntu.com/p/zZwXPBDNfn/)
* [cloud-init analyze show](http://paste.ubuntu.com/p/mWs7yRqwWN/)
* [cloud-init analyze boot](http://paste.ubuntu.com/p/K3ZQQBNDyV/)
* [journalctl --no-pager -b -x](http://paste.ubuntu.com/p/69ZxmCQvCx/)

## C6g.large Results

### 1st Boot Results

* [/var/log/cloud-init.log](http://paste.ubuntu.com/p/HNYkFmrRMq/)
* [/var/log/cloud-init-output.log](http://paste.ubuntu.com/p/ZqY6PXyfvY/)
* [cloud-init analyze blame](http://paste.ubuntu.com/p/YV2f9pHcXf/)
* [cloud-init analyze show](http://paste.ubuntu.com/p/ySJRmDw9mB/)
* [cloud-init analyze boot](http://paste.ubuntu.com/p/gD33ZCqqFc/)
* [journalctl --no-pager -b -x](http://paste.ubuntu.com/p/bXrc9x3pgW/)

### Branch Applied

Edited `/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceOpenStack.py` with the 2 line change. Deleted the pycache file for DataSourceOpenStack.py. Ran `cloud-init clean --logs --reboot`

### 2nd Boot Result

* [/var/log/cloud-init.log](http://paste.ubuntu.com/p/PRZpRsY9yt/)
* [/var/log/cloud-init-output.log](http://paste.ubuntu.com/p/8df3dCpBWG/)
* [cloud-init analyze blame](http://paste.ubuntu.com/p/qhZ6vqnfKc/)
* [cloud-init analyze show](http://paste.ubuntu.com/p/4JgpqdQXGZ/)
* [cloud-init analyze boot](http://paste.ubuntu.com/p/YCCFR6GKZ8/)
* [journalctl --no-pager -b -x](http://paste.ubuntu.com/p/gn74kKjJmY/)

You can clearly see the longer boot on arm64 during the 2nd boot.

**Comment by eandersson** [comment]
Interesting. Another solution would be to allow it to retry at least once or twice before giving up, instead of a set time. Of course this is configurable already, so operators could just increase timeouts themselves. This is what we do.

**Comment by raharper** [comment]
@powersj   Thanks for collecting this data.

> You can clearly see the longer boot on arm64 during the 2nd boot.

Yes; this is expected.  On x86, DataSourceOpenStack runs detect_openstack method which queries DMI table for expected OpenStack values; finds none on ec2 instance, and returns false, so it quickly skips OpenStack ,, but on non-x86 arches, there's no way (yet) for OpenStack instances to announce via non-network based mechanism that it's OpenStack so the detect code returns True (we can't say no for sure without hitting the URL).

**Comment by OddBloke** [comment]
I haven't followed this entire conversation; it sounds like we've found that this approach _is_ problematic on EC2 ARM instances, so we need to look into something else. Have I understood that correctly?

**Comment by raharper** [comment]
> I haven't followed this entire conversation; it sounds like we've found that this approach _is_ problematic on EC2 ARM instances, so we need to look into something else. Have I understood that correctly?

Yes.  That's my understanding as well.

**Comment by OddBloke** [comment]
OK, as we don't intend to land this in its current state, I'm going to move it to Draft.

**Comment by eandersson** [comment]
I assume that changing this to not slow down the EC2 ARM instances is gonna be difficult. How about either increasing the timeout from -1 to something low like 3 seconds to allow it to at least retry once? Another alternative would be to retry a few times at least (more than never retry).

**Comment by eandersson** [comment]
I think we can close this for now. I'll re-open it later if I have a better solution.

**Pull request closed without merging**
