### PR TITLE
test: pytestify and cleanup test_cc_mounts.py

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
test: pytestify and cleanup test_cc_mounts.py

Remove `unittest` constructs and remove base classes
```

## Additional Context
I did a bit more refactoring on the first test to make it feel more pytest-native, but functionally all tests should still be the same.

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
cc @a-dubs

**Comment by TheRealFalcon** [comment]
Ooph...this branch was a pure a refactor, but as I examine the tests a little more there's some major issues in a lot of them. I think this branch can probably be merged as-is, but don't be surprised if you see another commit or two land in this PR.

**Review by a-dubs — APPROVED** [review]
pytest >>> unittest

**Review by aciba90 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
