### PR TITLE
Docs: improved mermaid diagram for better visibility. Add "MaheshG11" as contributor

### PR DESCRIPTION
**Pull request by MaheshG11**
## Proposed Commit Message
```
docs: Adjust arrow color in Mermaid diagrams for improved visibility

1. Changed the color of arrows in Mermaid diagrams to enhance
   visibility in both dark and light mode themes. This change ensures
   that the diagrams are readable regardless of the viewing mode. 
2. IMPORTANT: Changed the order in doc/rtd/conf.py file, this was done 
   because it was giving import errors on running build commands. 
3. Added "MaheshG11" to "tools/.github-cla-signers".

Fixes GH-5837 
```

## Additional Context
Fixes issue #5837 
1. Modified the lineColor property of arrows for all mermaid diagrams in the documentation to a neutral color that stands out in both dark and light modes.
2. Added "MaheshG11" to "tools/.github-cla-signers".
3. IMPORTANT: Changed the order in conf.py file, this was done because it was giving import errors on running build commands. 

## Test Steps
Only for Linux/Unix Operating systems
1. In the main repo ``` cd doc/rtd ```
2. Run ``` sphinx-build -b html . build/html ```
3. Run  ``` xdg-open build/html/index.html ```. This should open up browser with the local build.
4.  In browser you will be on /index.html. Navigate to /explanation/boot.html. Here you will find changes that were made by this commit.

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#5837 )

### CODE REVIEW

**Comment by MaheshG11** [comment]
@aciba90 Thank you for approving workflows on this PR.
Unfortunately, one of the checks failed but I have now fixed it. Please approve the checks/workflows again #5874 
I am sorry for the inconvenience.

**Review by a-dubs — APPROVED** [review]
@MaheshG11 Thank you so much for this contribution! Appreciate the improvements to accessibility. Also thanks for the fixing the CI! It's all green now :partying_face: 

One small nit: Would you mind moving the "Add "MaheshG11" as Contributor" from the first line of the proposed commit message to after the body paragraph so that the first line fits within the 72 character limit and follows the conventional commits format?

**Comment by a-dubs** [comment]
@MaheshG11 Don't apologize! This is a great first time contribution and you already went above expectations by fully filling out the PR template which makes it much easier to review your PR. Also you have been very quick to respond so that is much appreciated, and also makes the PR process much faster for us. :blue_heart: 
 
Two things I notice for now so that we can get this PR merged:

1. Be sure to sign the CLA as per the instructions in the [first time contributor docs](https://docs.cloud-init.io/en/latest/development/first_PR.html). Once you do that, drop a message here and we will verify that you signed it properly. 

3. Your proposed commit message previously had a body to it. I am sorry if my previous instructions were unclear and made you think you needed to remove it. If you could please add a body paragraph back to the proposed commit message (does not need to be long. just a 1-3 sentences explaining what you changed and why). And then also add in the `Fixes GH-4837` footer that would be great. Refer to [this example](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-multi-paragraph-body-and-multiple-footers) from conventional commits for more info. Something like:
```
docs: Adjust arrow color in Mermaid diagrams for improved visibility

This is what i changed and this why.... Just a couple brief sentences.   

Added `MaheshG11` to `tools/.github-cla-signers` 

Fixes GH-4837
```

Thank you so much!

**Comment by MaheshG11** [comment]
@a-dubs, Thanks for such a friendly conversation !
I have already signed the CLA. Please verify it. 
Also, I have made necessary changes to the commit message

**Review by aciba90 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
