### PR TITLE
feat(ec2): Fetch metadata every boot

### PR DESCRIPTION
**Pull request by TheRealFalcon**
WIP as I am manually running integration tests.

## Proposed Commit Message

```
feat(ec2): Fetch metadata every boot

Following 7f87fa33, we'll setup networking first boot and also respond
to hotplug events, but if network is modified while an instance is
powered off, updates won't be visible to the instance upon next boot.

This commit ensures that on ec2, networking information is fetched
every boot.

Salesforce #00378972
```

## Additional Context
Ubuntu: This will be added to 24.04 but patched out of existing releases. The behavior can be manually enabled using update events.

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Ran integration tests with this commit against noble on ec2. Failures are unrelated to this change:
```
FAILED tests/integration_tests/test_networking.py::test_ec2_multi_network_cards - botocore.exceptions.ClientError: An error occurred (InsufficientInstanceCapacity) when calling the RunInstance
s operation (reached max retries: 4): We currently do not have sufficient p5....
FAILED tests/integration_tests/modules/test_ansible.py::test_ansible_pull_pip - AssertionError: Unexpected warning count != 0. Found: ["WARNING]: Running module ansible (<module 'cloudinit.con
fig.cc_ansible' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_an...
FAILED tests/integration_tests/modules/test_ansible.py::test_ansible_pull_distro - assert (not "ls: cannot access '/root/.ansible/collections/ansible_collections/community/grafana': No such fi
le or directory")
FAILED tests/integration_tests/modules/test_package_update_upgrade_install.py::TestPackageUpdateUpgradeInstall::test_apt_packages_are_installed - AssertionError: Package not installed: sl
FAILED tests/integration_tests/modules/test_package_update_upgrade_install.py::TestPackageUpdateUpgradeInstall::test_apt_packages_were_updated - AssertionError: assert None
FAILED tests/integration_tests/modules/test_package_update_upgrade_install.py::TestPackageUpdateUpgradeInstall::test_apt_packages_were_upgraded - assert 'Setting up tree (' in "Cloud-init v. 2
3.4-301-g461e4c33-1~bddeb running 'init-local' at Wed, 27 Mar 2024 22:23:08 +0000. Up 13.58 seconds.\nCloud-init v. 23.4-301-g461e4c33-1~bdde...
FAILED tests/integration_tests/modules/test_package_update_upgrade_install.py::TestPackageUpdateUpgradeInstall::test_snap_packages_are_installed - AssertionError: assert 'curl' in 'Name       
       Version     Rev    Tracking         Publisher    Notes\namazon-ssm-agent  3.2.2303.0  7983   latest/stable/…  aws**        classic\ncor...
======================================================== 7 failed, 204 passed, 64 skipped, 1 xpassed, 4 warnings in 12822.94s (3:33:42) ========================================================
```

**Review by blackboxsw — APPROVED** [review]
LGTM thanks for running through integration tests on this and ensuring the only subclass doesn't get a change in behavior.
I also can confirm at least the apt tests on noble are expected to fail due to https://bugs.launchpad.net/ubuntu/+source/needrestart/+bug/2059337 / https://github.com/canonical/cloud-init/issues/5109

**Comment by blackboxsw** [comment]
Please also put `LP: #2059317` in the commit footer

**Comment by TheRealFalcon** [comment]
Due to cache invalidation, I don't think this PR is necessary anymore. I will reopen if that turns out not to be true.

**Pull request closed without merging**
