### PR TITLE
Update cacerts to support VMware Photon

### PR DESCRIPTION
**Pull request by dark2phoenix**
## Proposed Commit Message
feat(cacerts) : Enable support for VMware Photon
```
<type>(optional scope): <summary>  # no more than 72 characters

This feature enables cacerts functionality for VMware Photon.  It 
allows for adding 3rd party certificates as well as for cloud-init
to use them in modules like phone_home.

## Test Steps
1. Add a certificate in the cloud-init configuration cacerts
2. Execute cloud-init
3. Verify that the certificate has been added to /etc/ssl/certs/ directory
4. Verify that the phone_home module can access a website built from the applied root certifcate

## Checklist
- [X ] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Thanks for the contribution @dark2phoenix . Before we can accept your change, you need to sign [the CLA](https://ubuntu.com/legal/contributors/agreement) and add your Github username (alphabetically) to [the cla signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) . The full details are described in the last bullet point [of the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request)

@sshedi , would you be able to confirm the paths in this PR?

**Comment by dark2phoenix** [comment]
Signed the file, added my name, and incorporated @sshedi's patch.  Thank you for validating the file paths, wasn't sure if the symlink or its target was the proper one to use.

**Comment by dark2phoenix** [comment]
Is there something additional I need to do?

**Comment by dark2phoenix** [comment]
I swear I already did that, but you're right.  I added myself to the file and updated the PR

**Comment by TheRealFalcon** [comment]
Last thing looks to be some minor formatting. If you run `tox -e do_format` it should fix it for you, and you can check with `tox -e check_format`

**Comment by dark2phoenix** [comment]
I'm trying to do that.  Getting tox to install on Windows 11 is turning out to be a real challenge (fails on lots of dependencies).

**Comment by TheRealFalcon** [comment]
Looks like it's just a space after a key:
```diff
diff --git a/cloudinit/config/cc_ca_certs.py b/cloudinit/config/cc_ca_certs.py
index c97f8e495..d254785f7 100644
--- a/cloudinit/config/cc_ca_certs.py
+++ b/cloudinit/config/cc_ca_certs.py
@@ -45,7 +45,7 @@ DISTRO_OVERRIDES = {
         "ca_cert_config": None,
         "ca_cert_update_cmd": ["update-ca-certificates"],
     },
-    "photon":{
+    "photon": {
         "ca_cert_path": "/etc/ssl/certs/",
         "ca_cert_local_path": "/etc/pki/tls/certs/",
         "ca_cert_filename": "cloud-init-ca-cert-{cert_index}.crt",

```

**Comment by dark2phoenix** [comment]
Thank you for the assist - it doesn't look possible to compile tox requirements on Windows 11.  I have updated the pull request with the change you pointed out.

**Review by TheRealFalcon — APPROVED** [review]
Thanks for the contribution and patience on this one!

**Comment by dark2phoenix** [comment]
> @dark2phoenix , I noticed you signed the CLA, but haven't yet added yourself to the CLA signers file. As part of this PR, please also add your name (alphabetically) to [the CLA signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers). The full details are described in the last bullet point [of the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request).

I'm already listed in the signers file as "dark2phoenix".

**Pull request merged**
