### PR TITLE
integration_tests: Support running on non-Ubuntu distros

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

```
integration_tests: Support running on non-Ubuntu distros

Commit 2562f93383 broke cross-platform support. Fix it.

Also remove an unused function.
```

### CODE REVIEW

**Review by TheRealFalcon — COMMENTED** [review]
The code is fine, but I'm not sure this really buys us anything.

The one call site looks like this:
```python
        if len(parts) == 1:
            image_id = None
            os = "ubuntu"
            series = parts[0]
            version = ubuntu_version_from_series(series)
```

so it is still Ubuntu-specific and will only run if you try to use something like `jammy` as the image specification. We could probably restructure the call site to make that a little more clear, but I don't see an advantage to this change as-is.

**Comment by holmanb** [comment]
>  but I don't see an advantage to this change as-is.

@TheRealFalcon  Integration tests cannot run on a non-ubuntu distro with the `main` branch, but they can on this branch. That seems like an advantage to me ¯\_(ツ)_/¯

**Comment by holmanb** [comment]
> @TheRealFalcon Integration tests cannot run on a non-ubuntu distro with the `main` branch, but they can on this branch. That seems like an advantage to me ¯_(ツ)_/¯

This PR is about the distro of the host, not the distro of the instance being tested. Maybe that is the confusion here?

**Review by TheRealFalcon — APPROVED** [review]
> Maybe that is the confusion here?

Yes, I understand now. LGTM!

**Pull request merged**
