### PR TITLE
net: Document use of `ip route append` to add routes

### PR DESCRIPTION
**Pull request by holmanb**
```
net: Document use of `ip route append` to add routes
```

**Update**
I am changing this PR to document the reason that the current code is needed for better context.

### CODE REVIEW

**Review by cjp256 — APPROVED** [review]
LGTM

**Comment by TheRealFalcon** [comment]
This was intentionally changed in #1124, though the code has moved files.

**Comment by holmanb** [comment]
> This was intentionally changed in #1124, though the code has moved files. I can't say I 100% understand the use case, but I think changing this could break some (or at least one) use cases.

Great context, thanks for pointing out the requirement for this behavior @TheRealFalcon.

I just reverted the previous commit and updated this PR to include context alongside the code, since that is currently not obvious.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
