### PR TITLE
Remove vestigal dhclient_hook command

### PR DESCRIPTION
**Pull request by holmanb**
```
dhclient_hook: remove vestigal dhclient_hook command

At inception[1], dhclient hooks were used to filter environment
variables into /run/cloud-init/dhclient.hooks/<interface>.json which was
consumed by WALinuxAgentShim. The fallback method was to parse the dhcp
client lease file.

Today the Azure datasource directly uses the parsed lease file[2], and
loading /run/cloud-init/dhclient.hooks/<interface>.json file was removed
in 22.2[3]. With no other consumers, we can remove this.

[1] https://github.com/canonical/cloud-init/commit/648dbbf6b090c81e989f1ab70bf99f4de16a6a70
[2] https://github.com/canonical/cloud-init/blob/main/cloudinit/sources/DataSourceAzure.py#L447
[3] https://github.com/canonical/cloud-init/commit/5ad0768a796bc07232476d0d29b5225f1e6e131c

```

### Option 1: Remove It (This PR)
This vestigal command is very cloud and environment-specific and is therefore unlikely to have external consumers.

### Option 2: Deprecate
Top level cloud-init commands should probably be deprecated before removal.

### CODE REVIEW

**Comment by holmanb** [comment]
Since this relates to recent changes in the Azure datasource, I am requesting a review from @anhvoms or @cjp256.

**Comment by cjp256** [comment]
LGTM

**Comment by anhvoms** [comment]
LGTM

**Review by aciba90 — APPROVED** [review]
LGTM

**Comment by TheRealFalcon** [comment]
@holmanb @aciba90 Since this is approved, is there a reason we're not merging it?

**Comment by igalic** [comment]
waiting for the release to pass SRU?

**Pull request merged**
