### PR TITLE
Ubuntu/xenial

### PR DESCRIPTION
**Pull request by blackboxsw**
Performed new-upstream-snapshot -v --skip-release (since we aren't pushing this for release yet).

This allows me to refresh failing quilt patches in debian/patches.

Since I had to refresh both ec2 patch and stable*requirements patch I added a common comment prefix SRU_FIX to we can easily see resolved differences in behavior in the cloud-init codebase via a grep.

Followed quilt refresh steps https://github.com/CanonicalLtd/uss-tableflip/blob/master/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails and manually changed the patch comment.

### CODE REVIEW

**Comment by raharper** [comment]
> Since I had to refresh both ec2 patch and stable*requirements patch I added a common comment prefix SRU_FIX to we can easily see resolved differences in behavior in the cloud-init codebase via a grep.

Where is this in the commit history?  And what does it look like?  Is this needed? or can we just document in tableflip docs that when we're getting quilt apply failures on daily recipe builds, we do:

new-upstream-snapshot --skip-release 

etc. ?

**Comment by blackboxsw** [comment]
> > Since I had to refresh both ec2 patch and stable*requirements patch I added a common comment prefix SRU_FIX to we can easily see resolved differences in behavior in the cloud-init codebase via a grep.
> 
> Where is this in the commit history? And what does it look like? Is this needed? or can we just document in tableflip docs that when we're getting quilt apply failures on daily recipe builds, we do:
> 
> new-upstream-snapshot --skip-release

We do have that documented already in uss-tableflip docs per your previous additions there (thanks) @   https://github.com/CanonicalLtd/uss-tableflip/blob/master/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails 

Since I had to manually fix the applied patches for both ec2-classic patch and stable-release-no-jsonschema using quilt, it is only captured in commitish d4cbc7eb4f8d90ef61ad7818f11855250deaa226 as "refresh patches against origin/master...."

**Comment by raharper** [comment]
> > > Since I had to refresh both ec2 patch and stable*requirements patch I added a common comment prefix SRU_FIX to we can easily see resolved differences in behavior in the cloud-init codebase via a grep.
> > 
> > 
> > Where is this in the commit history? And what does it look like? Is this needed? or can we just document in tableflip docs that when we're getting quilt apply failures on daily recipe builds, we do:
> > new-upstream-snapshot --skip-release
> 
> We do have that documented already in uss-tableflip docs per your previous additions there (thanks) @ https://github.com/CanonicalLtd/uss-tableflip/blob/master/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails
> 
> Since I had to manually fix the applied patches for both ec2-classic patch and stable-release-no-jsonschema using quilt, it is only captured in commitish [d4cbc7e](https://github.com/canonical/cloud-init/commit/d4cbc7eb4f8d90ef61ad7818f11855250deaa226) as "refresh patches against origin/master...."

I see.  I don't really want any manual steps added that aren't documented in process you followed.  Let's not include that string.

**Comment by blackboxsw** [comment]
> > > > Since I had to refresh both ec2 patch and stable*requirements patch I added a common comment prefix SRU_FIX to we can easily see resolved differences in behavior in the cloud-init codebase via a grep.
> > > 
> > > 
> > > Where is this in the commit history? And what does it look like? Is this needed? or can we just document in tableflip docs that when we're getting quilt apply failures on daily recipe builds, we do:
> > > new-upstream-snapshot --skip-release
> > 
> > 
> > We do have that documented already in uss-tableflip docs per your previous additions there (thanks) @ https://github.com/CanonicalLtd/uss-tableflip/blob/master/doc/ubuntu_release_process.md#when-the-daily-recipe-build-fails
> > Since I had to manually fix the applied patches for both ec2-classic patch and stable-release-no-jsonschema using quilt, it is only captured in commitish [d4cbc7e](https://github.com/canonical/cloud-init/commit/d4cbc7eb4f8d90ef61ad7818f11855250deaa226) as "refresh patches against origin/master...."
> 
> I see. I don't really want any manual steps added that aren't documented in process you followed. Let's not include that string.

Done +1. Limited need for that level of prescribed commenting.

**Pull request merged**
