### PR TITLE
feat(ec2): Bump url_max_timeout to 240s from 120s.

### PR DESCRIPTION
**Pull request by halfdime-code**
## Proposed Commit Message

```
feat(ec2): Bump url_max_timeout to 240s from 120s.
    
Initialization of IMDS is periodically exceeding the 120s limit on
instance launch. Increase the timeout to allow for this variance.
    
Update docs to reflect change.
```

## Test Steps

This issue was seen during instance launch testing and is inconsistent and difficult to reproduce.
Most of the time, the current timeout is not reached.

``tox -e py3`` was run before and after this change with only hash naming differences.

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by halfdime-code** [comment]
Looks like I missed a doc update in `doc/rtd/reference/datasources/ec2.rst`.

**Comment by holmanb** [comment]
@halfdime-code hey can you please provide logs for the failure you were seeing?

**Comment by halfdime-code** [comment]
No problem.
```
2024-07-25 23:33:27,719 - url_helper.py[WARNING]: Calling 'None' failed [50/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
2024-07-25 23:34:36,971 - url_helper.py[WARNING]: Calling 'None' failed [119/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Exception(s) [UrlError("HTTPConnectionPool(host='fd00:ec2::254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), UrlError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out'))")] during request to http://169.254.169.254:80/latest/api/token, raising last exception
2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Calling 'None' failed [253/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out'))]
2024-07-25 23:36:51,490 - url_helper.py[ERROR]: Timed out, no response from urls: ['http://169.254.169.254:80/latest/api/token', 'http://[fd00:ec2::254]:80/latest/api/token']
```

**Comment by holmanb** [comment]
> No problem.
> 
> ```
> 2024-07-25 23:33:27,719 - url_helper.py[WARNING]: Calling 'None' failed [50/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
> 2024-07-25 23:34:36,971 - url_helper.py[WARNING]: Calling 'None' failed [119/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
> 2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Exception(s) [UrlError("HTTPConnectionPool(host='fd00:ec2::254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), UrlError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out'))")] during request to http://169.254.169.254:80/latest/api/token, raising last exception
> 2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Calling 'None' failed [253/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out'))]
> 2024-07-25 23:36:51,490 - url_helper.py[ERROR]: Timed out, no response from urls: ['http://169.254.169.254:80/latest/api/token', 'http://[fd00:ec2::254]:80/latest/api/token']
> ```

Thanks @halfdime-code since this is difficult to reproduce, could you please include the rest of `/var/log/cloud-init.log`? The `Calling 'None' failed` looks like potentially a type error of some kind so having more of the log will help to diagnose it (and/or verify the proposed fix).

**Comment by halfdime-code** [comment]
Please note that this is not a bug in cloud-init, just a behavioral change in AWS afaict.

I'm assuming that you want the log up until the failure. Everything after is just cloud-init carrying on as usual.

I'm reasonably confident that you won't be able to reproduce it without simply disabling IMDS on an instance and seeing that the timeout occurs. Essentially, this is a timing issue with IMDS availability.

If I look at another host that has a "near miss" the logs that I sent you look like this instead. Note the missing "`Calling 'None' failed [253/120s]:`" log entry here.
```
2024-07-25 23:53:45,500 - url_helper.py[WARNING]: Calling 'None' failed [50/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xffffa7100a90>, 'Connection to 169.254.169.254 timed out. (connect timeout=50.0)'))]
2024-07-25 23:53:45,500 - url_helper.py[DEBUG]: Please wait 0.25 seconds while we wait to try again
2024-07-25 23:53:45,750 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 69.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:53:45,901 - url_helper.py[DEBUG]: [0/1] open 'http://[fd00:ec2::254]:80/latest/api/token' with {'url': 'http://[fd00:ec2::254]:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 69.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:54:54,751 - url_helper.py[WARNING]: Calling 'None' failed [119/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
2024-07-25 23:54:54,751 - url_helper.py[DEBUG]: Please wait 0.25 seconds while we wait to try again
2024-07-25 23:54:55,002 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:54:55,005 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-07-25 23:54:55,005 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
```

The logs from start until `util.py` takes over (which is after IMDS is deemed dead, "`DataSourceEc2.py[WARNING]: IMDS's HTTP endpoint is probably disabled`").
```
2024-07-25 23:32:37,504 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Thu, 25 Jul 2024 23:32:37 +0000. Up 5.02 seconds.
2024-07-25 23:32:37,504 - main.py[DEBUG]: No kernel command line url found.
2024-07-25 23:32:37,505 - main.py[DEBUG]: Closing stdin.
2024-07-25 23:32:37,505 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-07-25 23:32:37,506 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-25 23:32:37,520 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-07-25 23:32:37,520 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-25 23:32:37,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-07-25 23:32:37,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-25 23:32:37,527 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-07-25 23:32:37,528 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-25 23:32:37,532 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-07-25 23:32:37,533 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-25 23:32:37,538 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-07-25 23:32:37,539 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-25 23:32:37,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-07-25 23:32:37,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-25 23:32:37,568 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-07-25 23:32:37,569 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-25 23:32:37,589 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-07-25 23:32:37,599 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-25 23:32:37,611 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-07-25 23:32:37,612 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-07-25 23:32:37,612 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-07-25 23:32:37,613 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-07-25 23:32:37,613 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-07-25 23:32:37,614 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-07-25 23:32:37,615 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-07-25 23:32:37,615 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-07-25 23:32:37,615 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-07-25 23:32:37,616 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-07-25 23:32:37,617 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-07-25 23:32:37,617 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-07-25 23:32:37,625 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-07-25 23:32:37,630 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-07-25 23:32:37,642 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-07-25 23:32:37,642 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-07-25 23:32:37,642 - stages.py[DEBUG]: no cache found
2024-07-25 23:32:37,642 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-07-25 23:32:37,642 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-07-25 23:32:37,661 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-25 23:32:37,661 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-07-25 23:32:37,667 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-07-25 23:32:37,667 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-07-25 23:32:37,667 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-07-25 23:32:37,667 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-07-25 23:32:37,667 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-07-25 23:32:37,668 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-07-25 23:32:37,668 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-07-25 23:32:37,668 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-07-25 23:32:37,668 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-07-25 23:32:37,668 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-07-25 23:32:37,668 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-07-25 23:32:37,668 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-07-25 23:32:37,668 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-07-25 23:32:37,668 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-07-25 23:32:37,668 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-07-25 23:32:37,709 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:32:37,860 - url_helper.py[DEBUG]: [0/1] open 'http://[fd00:ec2::254]:80/latest/api/token' with {'url': 'http://[fd00:ec2::254]:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:33:27,719 - url_helper.py[WARNING]: Calling 'None' failed [50/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
2024-07-25 23:33:27,719 - url_helper.py[DEBUG]: Please wait 0.25 seconds while we wait to try again
2024-07-25 23:33:27,970 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 69.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:33:28,120 - url_helper.py[DEBUG]: [0/1] open 'http://[fd00:ec2::254]:80/latest/api/token' with {'url': 'http://[fd00:ec2::254]:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 69.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:34:36,971 - url_helper.py[WARNING]: Calling 'None' failed [119/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
2024-07-25 23:34:36,971 - url_helper.py[DEBUG]: Please wait 0.25 seconds while we wait to try again
2024-07-25 23:34:37,222 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:34:37,372 - url_helper.py[DEBUG]: [0/1] open 'http://[fd00:ec2::254]:80/latest/api/token' with {'url': 'http://[fd00:ec2::254]:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Exception(s) [UrlError("HTTPConnectionPool(host='fd00:ec2::254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa1c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), UrlError("HTTPConn
ectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out'))")] during request to http://169.254.169.254:80/latest/api/token, raising last exception
2024-07-25 23:36:51,490 - url_helper.py[WARNING]: Calling 'None' failed [253/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9caaa250>: Failed to establish a new connection: [Errno 110] Connection timed out
'))]
2024-07-25 23:36:51,490 - url_helper.py[ERROR]: Timed out, no response from urls: ['http://169.254.169.254:80/latest/api/token', 'http://[fd00:ec2::254]:80/latest/api/token']
2024-07-25 23:36:51,490 - DataSourceEc2.py[WARNING]: IMDS's HTTP endpoint is probably disabled
2024-07-25 23:36:51,490 - util.py[DEBUG]: Crawl of metadata service took 253.822 seconds
2024-07-25 23:36:51,490 - __init__.py[DEBUG]: Datasource DataSourceEc2 not updated for events: boot-new-instance
2024-07-25 23:36:51,490 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: no network data found from DataSourceEc2
2024-07-25 23:36:51,490 - handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
2024-07-25 23:36:51,490 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
2024-07-25 23:36:51,490 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-07-25 23:36:51,490 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2024-07-25 23:36:51,491 - util.py[DEBUG]: Read 126 bytes from /etc/hosts
2024-07-25 23:36:51,492 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-none - wb: [644] 5 bytes
2024-07-25 23:36:51,492 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-none (recursive=False)
2024-07-25 23:36:51,493 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-none (recursive=False)
2024-07-25 23:36:51,493 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-none'
2024-07-25 23:36:51,494 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpu4za_tcb) - w: [600] 5593 bytes/chars
2024-07-25 23:36:51,494 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmp4dwflxtv) - w: [644] 1397 bytes/chars
2024-07-25 23:36:51,494 - handlers.py[DEBUG]: finish: init-network/search-None: SUCCESS: found network data from DataSourceNone
2024-07-25 23:36:51,494 - stages.py[INFO]: Loaded datasource DataSourceNone - DataSourceNone
... and so on ...

```

**Comment by holmanb** [comment]
> Please note that this is not a bug in cloud-init, just a behavioral change in AWS afaict.
> 
> I'm assuming that you want the log up until the failure. Everything after is just cloud-init carrying on as usual.

That should work. Thanks for the response! I'll dig into this soon.

**Comment by halfdime-code** [comment]
Bumping and tagging @TheRealFalcon as requested. @holmanb was looking into this.

**Comment by aciba90** [comment]
Hi, @halfdime-code, thanks for submitting this PR and making cloud-init better. I have removed the stale label and the team will have another look on this. Thanks and sorry for the delay.

**Review by holmanb — APPROVED** [review]
@halfdime-code This should be fine, but it looks like this needs to be rebased on main to fix the failing test.

**Comment by halfdime-code** [comment]
Not 100% sure I got the rebase right here. Please advise if I've gummed up the works.

**Pull request merged**
