### PR TITLE
openstack: consider product_name as valid chassis tag

### PR DESCRIPTION
**Pull request by ader1990**
Consider valid product names as valid chassis asset tags when detecting
OpenStack platform before crawling for OpenStack metadata.

As `ds-identify` tool uses product name as valid chassis asset tags,
let's replicate the behaviour in the OpenStack platform detection too.

This change should be backwards compatible and a temporary fix for the
current limitations on the OpenStack platform detection.

LP: #1895976

### CODE REVIEW

**Comment by ader1990** [comment]
I wonder why in the docs, there is already mentioned that the product names are already valid chassis tags, as the DataSourceOpenStack.py detect_openstack method does not include them.

See docs: https://github.com/canonical/cloud-init/blob/master/doc/rtd/topics/datasources/openstack.rst#discovery
See the implementation: https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceOpenStack.py#L223

**Review by smoser — CHANGES_REQUESTED** [review]
Hi,

Could you please add a test to this.
It should be fairly easy to do, the test wil just lok a lot like
 test_detect_openstack_opentelekomcloud_chassis_asset_tag or 
 test_detect_openstack_sapccloud_chassis_asset_tag

Thanks.

**Comment by smoser** [comment]
> Partially-fixes:
> https://bugs.launchpad.net/cloud-init/+bug/1895976

Why 'Partially fixes' ?
just because it requires changes in openstack also?

I think that is considered 'fixes' here.

change the commit message to have:

    LP: #1895976

**Comment by ader1990** [comment]
@smoser thank you for the review. Will add the unit test asap.

As for the partially fixes, I consider that a good fix for the issue would be to expose a config option (or more) for the OpenStack data source, to either enable or disable the platform check, and to define the valid product name/ chassis asset tags.

But this kind of change would not be backward compatible and would be deemed a little overkill for the issue at hand:

```yaml
OpenStack:
  check_supported_platform: True,
  valid_product_name: [ 'OpenStack Nova', 'OpenStack Compute' ],
  valid_asset_tag: ['OpenTelekomCloud', 'SAP CCloud VM']
```

Maybe add these changes in a separate patch?

Thank you,
Adrian Vladu

**Comment by smoser** [comment]
> @smoser thank you for the review. Will add the unit test asap.
> 
> As for the partially fixes, I consider that a good fix for the issue would be to expose a config option (or more) for the OpenStack data source, to either enable or disable the platform check, and to define the valid product name/ chassis asset tags.
> 
> But this kind of change would not be backward compatible and would be deemed a little overkill for the issue at hand:
> 
> ```yaml
> OpenStack:
>   check_supported_platform: True,
>   valid_product_name: [ 'OpenStack Nova', 'OpenStack Compute' ],
>   valid_asset_tag: ['OpenTelekomCloud', 'SAP CCloud VM']
> ```
> 
> Maybe add these config options in a separate patch?
> 
> Thank you,
> Adrian Vladu

I agree that such changes like that are overkill.  My feeling is that things like that really don't need to be configurable.  I'd rather support *actual* values than expect users to modify images to make them work on their cloud. It make *much* more sense for a cloud/platform to identify itself in a standard way than require all consumers to do custom config.

 Additionally, at this point ds-identify can't really read such a config.

**Comment by ader1990** [comment]
> > @smoser thank you for the review. Will add the unit test asap.
> > As for the partially fixes, I consider that a good fix for the issue would be to expose a config option (or more) for the OpenStack data source, to either enable or disable the platform check, and to define the valid product name/ chassis asset tags.
> > But this kind of change would not be backward compatible and would be deemed a little overkill for the issue at hand:
> > ```yaml
> > OpenStack:
> >   check_supported_platform: True,
> >   valid_product_name: [ 'OpenStack Nova', 'OpenStack Compute' ],
> >   valid_asset_tag: ['OpenTelekomCloud', 'SAP CCloud VM']
> > ```
> > 
> > 
> > Maybe add these config options in a separate patch?
> > Thank you,
> > Adrian Vladu
> 
> I agree that such changes like that are overkill. My feeling is that things like that really don't need to be configurable. I'd rather support _actual_ values than expect users to modify images to make them work on their cloud. It make _much_ more sense for a cloud/platform to identify itself in a standard way than require all consumers to do custom config.
> 
> Additionally, at this point ds-identify can't really read such a config.

I added the small unit tests, hope everything is good to go now.

**Review by smoser — APPROVED** [review]
Thanks for adding tests.

**Review by OddBloke — APPROVED** [review]
This looks to me like it's aligning `DataSourceOpenStack`'s behaviour with `ds-identify`s, has the appropriate testing, and the CLA is signed. Thanks!

**Comment by OddBloke** [comment]
Hey @ader1990, we're currently running through the process to release this change into stable Ubuntu releases. Might you be able to help us out by testing this change? https://cloudinit.readthedocs.io/en/latest/topics/debugging.html#manual-sru-verification-procedure breaks down how to go about it.

**Comment by ader1990** [comment]
> Hey @ader1990, we're currently running through the process to release this change into stable Ubuntu releases. Might you be able to help us out by testing this change? https://cloudinit.readthedocs.io/en/latest/topics/debugging.html#manual-sru-verification-procedure breaks down how to go about it.

Hello,

Can you give me more details on what breaks and on which cloud version, so that I can test / debug?

Thank you,
Adrian.

**Comment by OddBloke** [comment]
On Wed, Dec 09, 2020 at 07:15:57AM -0800, Adrian Vladu wrote:
> > Hey @ader1990, we're currently running through the process to
> > release this change into stable Ubuntu releases. Might you be able
> > to help us out by testing this change?
> > https://cloudinit.readthedocs.io/en/latest/topics/debugging.html#manual-sru-verification-procedure
> > breaks down how to go about it.
> 
> Can you give me more details on what breaks and on which cloud
> version, so that I can test / debug?

What we're currently doing is following Ubuntu's Stable Release Update
process to release cloud-init 20.4 into stable Ubuntu releases, so that
Ubuntu users can start benefitting from the changes in that cloud-init
release.  Part of that process is running through testing to confirm
that everything that we're backporting works as expected in the target
Ubuntu releases.

In the case of this change, the cloud-init team don't have access to an
OpenStack system which triggers this bug, so we can't perform this
testing ourselves.  What we're looking for you to do is follow the
testing steps on an instance in such an environment (if you still have
access) and confirm that the new version of cloud-init does, indeed,
address the issue that this PR was fixing.

The doc I linked to breaks down the steps: launch an instance, enable
-proposed, upgrade cloud-init to the version in -proposed, clean
cloud-init's state, reboot, check that cloud-init behaved correctly.

Is that something you're able to help with?

**Comment by ader1990** [comment]
I understand the problem and I can help, sure. Do you need also some logs before/after or just a confirmation it works?

**Comment by OddBloke** [comment]
On Wed, Dec 09, 2020 at 07:40:47AM -0800, Adrian Vladu wrote:
> I understand the problem and I can help, sure.

Excellent, thank you!

> Do you need also some logs before/after or just a confirmation it
> works?

Some before/after logs would be good, yes.  Looking at the bug, I
believe cloud-init.log included the error message in the failure case,
so I think that's probably all we need?

**Pull request merged**
