### PR TITLE
fix: do not warn in thinpool fallback

### PR DESCRIPTION
**Pull request by holmanb**
## Proposed Commit Message

```
fix: do not warn in thinpool fallback

This path is expected on some images.
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Sorry, should have mentioned during the chat, it's not just the warning. We get a traceback too:
```
2024-10-08 19:38:22,219 - cc_lxd.py[WARNING]: cloud-init doesn't use thinpool by default on Ubuntu due to LP #1982780. This behavior will change in the future.
2024-10-08 19:38:22,220 - subp.py[DEBUG]: Running command ['lxc', 'storage', 'create', 'default', 'lvm', 'lvm.use_thinpool=false'] with allowed return codes [0] (shell=False, capture=True)
2024-10-08 19:38:23,089 - performance.py[DEBUG]: Running ['lxc', 'storage', 'create', 'default', 'lvm', 'lvm.use_thinpool=false'] took 0.870 seconds
2024-10-08 19:38:23,090 - subp.py[DEBUG]: Running command ['lxd', 'init', '--auto', '--storage-backend=lvm'] with allowed return codes [0] (shell=False, capture=True)
2024-10-08 19:38:23,147 - performance.py[DEBUG]: Running ['lxd', 'init', '--auto', '--storage-backend=lvm'] took 0.057 seconds
2024-10-08 19:38:23,147 - handlers.py[DEBUG]: finish: modules-final/config-lxd: FAIL: running config-lxd with frequency once-per-instance
2024-10-08 19:38:23,147 - log_util.py[WARNING]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) failed
2024-10-08 19:38:23,147 - log_util.py[DEBUG]: Running module lxd (<module 'cloudinit.config.cc_lxd' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py", line 128, in handle
    subp.subp(cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 291, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['lxd', 'init', '--auto', '--storage-backend=lvm']
Exit code: 1
Reason: -
Stdout: 
Stderr: Error: Failed to create storage pool "default": Error creating LVM thin pool named "LXDThinPool": Failed to run: lvcreate --yes --wipesignatures y --thinpool default/LXDThinPool --extents 100%FREE: exit status 3 (modprobe: FATAL: Module dm-thin-pool not found in directory /lib/modules/5.15.0-1067-kvm
          /sbin/modprobe failed: 1
          thin-pool: Required device-mapper target(s) not detected in your kernel.
          Run `lvcreate --help' for more information.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 295, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 60, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_lxd.py", line 155, in handle
    subp.subp(cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 291, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['lxd', 'init', '--auto', '--storage-backend=lvm']
Exit code: 1
Reason: -
Stdout: 
Stderr: Error: Storage has already been configured
```

**Comment by holmanb** [comment]
> Sorry, should have mentioned during the chat, it's not just the warning. We get a traceback too:

All good, I might have seen this `traceback_count = 2` in the output. On my "someday" wishlist is to get better traceback reporting in `verify_clean_boot()`.

**Comment by holmanb** [comment]
@TheRealFalcon I haven't tested it, but it looks like the filtering was broken looking for the wrong key name, by the comments.

**Comment by TheRealFalcon** [comment]
@holmanb that didn't work either. I took the liberty of pushing some extra commits to your branch (I think we can squash it all in the end). Let me know if this works for you.

**Comment by holmanb** [comment]
> @holmanb that didn't work either. I took the liberty of pushing some extra commits to your branch (I think we can squash most of them in the end). Let me know if this works for you.

Ahh, the fix makes sense. Thanks for that and the cleanups here. Works for me!

**Review by TheRealFalcon — APPROVED** [review]
I think I need to approve it to merge it :joy:

**Pull request merged**
