### PR TITLE
upgrade from md5 to sha256

### PR DESCRIPTION
**Pull request by raharper**
Print ssh key fingerprints using sha256 hash

LP: #1860789

### CODE REVIEW

**Comment by raharper** [comment]
I’m not sure, why would it matter?

**Comment by OddBloke** [comment]
On Fri, Jan 24, 2020 at 11:32:50AM -0800, Ryan Harper wrote:
> I’m not sure, why would it matter?

As we emit these, I'm assuming people are using them for validation.
Given that, I don't think we should be changing the emitted fingerprint
in existing releases, as that would break people's existing workflows.

OTOH, if the position is that validating an _MD5_ fingerprint is not
really validating much at all, then I'd be comfortable making the change
going back, but we would probably need to clearly communicate it (in
some way) so we don't have a whole bunch of people thinking that they've
been hacked.

**Comment by raharper** [comment]
On Fri, Jan 24, 2020 at 21:39 Daniel Watkins <notifications@github.com>
wrote:

> On Fri, Jan 24, 2020 at 11:32:50AM -0800, Ryan Harper wrote:
> > I’m not sure, why would it matter?
>
> As we emit these, I'm assuming people are using them for validation.
> Given that, I don't think we should be changing the emitted fingerprint
> in existing releases, as that would break people's existing workflows.
>
> OTOH, if the position is that validating an _MD5_ fingerprint is not
> really validating much at all, then I'd be comfortable making the change
> going back, but we would probably need to clearly communicate it (in
> some way) so we don't have a whole bunch of people thinking that they've
> been hacked.


Right.  That makes sense.  Md5 is broken so validating is useless.  I don’t
think we need to keep it around in older releases but we definitely should
advertise this change for focal and sru

**Comment by xnox** [comment]
The default is sha256 on bionic and up, thus by printing md5 actually people can't verify key hashes on the most popular / recent releases of any major operating system.

**Comment by OddBloke** [comment]
On Sun, Jan 26, 2020 at 02:48:31PM -0800, Dimitri John Ledkov wrote:
> The default is sha256 on bionic and up, thus by printing md5 actually
> people can't verify key hashes on the most popular / recent releases
> of any major operating system.

The _default_ doesn't change whether people _can_ verify the hashes.

**Pull request merged**
