### PR TITLE
net/nm: check for presence of ifcfg files when nm connection files are absent

### PR DESCRIPTION
**Pull request by ani-sinha**
On systems where network manager connection files are absent, they may use ifcfg files for configuring interfaces with using ifcfg-rh network manager plugin. We need to check for the presence of ifcfg interface config file if the network manager connection file is absent.

Fixes: GH-4640

### CODE REVIEW

**Comment by ani-sinha** [comment]
Still being tested internally. I put it out here for broader feedback.

**Comment by ani-sinha** [comment]
> Still being tested internally. I put it out here for broader feedback.

QE gave a green signal. Change seems to pass test.

**Comment by ani-sinha** [comment]
@TheRealFalcon please review/comment.

**Review by TheRealFalcon — APPROVED** [review]
LGTM! Thanks!

**Comment by yakhatape** [comment]
hi @TheRealFalcon @ani-sinha ,

I'm facing the issue which is fixed by this PR on my fresh build template of RockyLinux 8.9 (which now use cloud-init 23.1) where on RockyLinux 8.8 (it was the old Cloud-init 22.1-8 version which i didn't catch any issue).
Do you know when a package will be publish/created for fedora/rhel etc.. with this fix ?

Thanks in advance for your job,

**Comment by ani-sinha** [comment]
> hi @TheRealFalcon @ani-sinha ,
> 
> 
> 
> I'm facing the issue which is fixed by this PR on my fresh build template of RockyLinux 8.9 (which now use cloud-init 23.1) where on RockyLinux 8.8 (it was the old Cloud-init 22.1-8 version which i didn't catch any issue).
> 
> Do you know when a package will be publish/created for fedora/rhel etc.. with this fix ?
> 
> 
> 
> Thanks in advance for your job, 

You need to ask your downstream distribution. In this case Rocky folks. They might be able to patch their cloud-init and release a package sooner than an upstream release with a fix.

**Pull request merged**
