### PR TITLE
Recognize opensuse-microos

### PR DESCRIPTION
**Pull request by rjschwei**
## Proposed Commit Message

Update the distro selection code to recognize opensuse-microos as a SUSE based distribution.

## Checklist:

 - [ x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/contributing.html)
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Thanks @rjschwei. Don't we also need opensuse-microos support in the following config modules?
- [cloudinit.config.cc_ntp](https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_ntp.py#L169) 
- [cloudinit.config.cc_zypper_add_repo.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_zypper_add_repo.py#L21)
- [cloudinit/config/cc_resolv_conf.py](https://github.com/canonical/cloud-init/blob/main/cloudinit/config/cc_resolv_conf.py#L62)

**Comment by rjschwei** [comment]
Thanks @blackboxsw glad you are paying attention. Fixed. There were others missing as well.

**Comment by rjschwei** [comment]
@blackboxsw can you give me a hand? I cannot figure out how to fix the cli test. Thanks

**Comment by aciba90** [comment]
> @blackboxsw can you give me a hand? I cannot figure out how to fix the cli test. Thanks

The test matches exact output, so ordering matters. The following patch fixes it:

```diff
diff --git a/tests/unittests/test_cli.py b/tests/unittests/test_cli.py
index 9773ea361..2880f27a9 100644
--- a/tests/unittests/test_cli.py
+++ b/tests/unittests/test_cli.py
@@ -250,9 +250,9 @@ class TestCLI:
                     "cloudlinux, cos, debian, eurolinux, fedora, freebsd, "
                     "mariner, miraclelinux, "
                     "openbsd, openEuler, openmandriva, "
-                    "opensuse, opensuse-microos, opensuse-leap, "
-                    "opensuse-tumbleweed, photon, rhel, rocky, sle-micro, "
-                    "sle_hpc, sles, ubuntu, virtuozzo",
+                    "opensuse, opensuse-microos, opensuse-tumbleweed, "
+                    "opensuse-leap, photon, rhel, rocky, sle_hpc, "
+                    "sle-micro, sles, ubuntu, virtuozzo",
                     "**Config schema**:\n    **resize_rootfs:** "
                     "(``true``/``false``/``noblock``)",
                     "**Examples**::\n\n    runcmd:\n        - [ ls, -l, / ]\n",
```

**Comment by rjschwei** [comment]
@aciba90 Thanks, applied

**Review by blackboxsw — COMMENTED** [review]
Looks really good @rjschwei thank you.

I've put up a couple of extra commits so we can make sure our developer tools still work with building and testing opensuse images using LXC.

Basically tools/read-dependencies and tools/run-container need to be able to properly launch and dependencies on image streams named opensuse/15.4 or opensuse/tumbleweed etc.

I found one unittest which leaks into the underlying filesystem (test_opennebula) which prevents unittests from running appropriately when launching
`./tools/run-container opensuse/15.4 --unittests`.

The combined 3 commits are available in this PR.
   https://github.com/rjschwei/cloud-init/pull/1


If you would rather I provide a separate PR for the tool additions I can do that. Or if you'd like to fold them into this PR I think we could do that as well.

Either way we'll probably land this this week as I would like to get it into upstream release 23.1

**Review by blackboxsw — APPROVED** [review]

**Comment by rjschwei** [comment]
@blackboxsw thanks for helping with the test fixes. #1 can be merged into this PR, works for me.

**Pull request merged**
