### PR TITLE
Fix patches

### PR DESCRIPTION
**Pull request by holmanb**
```
Black broke bionic patch format. Fix it
```

### CODE REVIEW

**Review by TheRealFalcon — APPROVED** [review]
Patches look good to me and I verified the branch merges and quilt patches apply cleanly.

@blackboxsw , can you give a +1 too?

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Thanks for working on this @holmanb.

I think we need to change a couple of things here. 

- The branch on it's own should allow us to `quilt push -a; quilt pop -a` successfully so that it can be built on it's own without any interaction or merge with main
- We should be able to `build-package;  sbuild --dist=bionic --arch=amd64  --arch-all ../out/cloud-init*.dsc` (which also quilt appllies patches before running unit tests/flake etc)
- don't need to add the new d/changelog section, pull content in the top of previous UNRELEASED section


I think the reason we want this branch to be buildable without a merge from main is so that we can easily represent as close as we can, the latest bionic released content in the event that we need to hotfix that release due to a security vulnerability. Once we have drift in an ubuntu/* branch which makes the branch unbuildable, it adds tech debt related to an upcoming release that will make a swift release tougher to both test and publish.


I'll work on this procedure in earnest (and avoid using `new-upstream-snapshot`) to provide you more solid feedback on steps I took and an generated diff I'd like to see here to make sure both our daily recipes continue to build, and that the upstream/ubuntu/bionic branch can continue to build locally without merging main.

**Comment by TheRealFalcon** [comment]
@blackboxsw , if we want the branch to be buildable, then we should just upstream snapshot, correct? It shouldn't be too hard to do that on top of this commit. Either way we'll need the patches here as-is.

> I think the reason we want this branch to be buildable without a merge from main is so that we can easily represent as close as we can, the latest bionic released content in the event that we need to hotfix that release due to a security vulnerability. Once we have drift in an ubuntu/* branch which makes the branch unbuildable, it adds tech debt related to an upcoming release that will make a swift release tougher to both test and publish.

This is why we tag. I did get buy-in from a proposal that included removing daily branches and creating hotfixes branched from tags rather than keeping pristine packaging branches.
image

If we need to revisit it, that's fine. Sounds like we need something a little more concrete. I'll can throw together a spec for this.

**Comment by blackboxsw** [comment]
> 
Thanks @TheRealFalcon for throwing images at this to sear that concept into my head and allow us to reference it in the future. You are right, and I agree. I think the image is good enough for discussion and we might be able to capture the idea in a branching section or doc in RTD which describes the ongoing intent of the branches. We then could reference that doc locally in project as needed.
- Your git tag branching image olidifies how we can create a `ubuntu/bionic/hot-fix-<major-minor>` branch if needed based on the previously released tag without worrying about the ability to continue merging main into `ubuntu/bionic` for daily builds. 
- Any subsequent SRU we perform for cloud-init into Bionic will always end up including that hot-fix commit anyway because we would "cherry-pick" that commit from `main` which gets included on our next `new-upstream-snapshot`.
-  if additional hot-fix releases are needed before a full new-upstream-snapshot SRU,  those fixes can be added to the `ubuntu/bionic/hot-fix-<major-minor>` branch.

>> @blackboxsw , if we want the branch to be buildable, then we should just upstream snapshot, correct? It shouldn't be too hard to do that on top of this commit. Either way we'll need the patches here as-is.
And yes, new-upstream-snapshot doesn't matter then on `upstream/ubuntu/bionic` and we don't need a `ubuntu/daily/bionic` to pop "cpick" files off of that stack currently because we don't actually carry any `debian/patches/cpick-*` files anyway in bionic at the moment and we also will avoid those cpick files in the future by using a `ubuntu/focal/hot-fix-*` branch.

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Ok following the discussion above, we can always use new-upstream-snapshot to resolve any daily build problems and we won't have to use an ubuntu/daily/bionic branch to pop any commits off of the ubuntu/bionic branch as we will eventually release latest main on our next SRU. 

Since you did the hard work to fix the quilt patches (against main), we can fix this current branch with the following procedure:

1. drop your debian/chagelog commit
$ git reset --hard HEAD~1
2. use --skip-release to avoid having to enter an SRU_BUG_NUMBER in changelog
$ new-upstream-snapshot --skip-release
3. Because new-upstream-snapshot appends new entries below existing in an UNRELEASED section, we need to shift the bottom 61 lines back to the top in debian/changelog editor view
   3a. delete the leading duplicated "refresh patches" lines
   3b. Yank the last 61 lines of debian/changelog section and put it up at the top just under the "refresh patches" entries starting at  
       "* New upstream snapshot. (LP: #SRU_BUG_NUMBER_HERE)"


Ultimately your debian/changelog diff against upstream/ubuntu/bionic should be something like
```diff
diff --git a/debian/changelog b/debian/changelog
index cfca64d4..c11eb7d2 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,18 +1,70 @@
-cloud-init (21.4-39-ge9634266-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
+cloud-init (21.4-82-g0d364a29-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
 
   * refresh patches:
    + debian/patches/ec2-dont-apply-full-imds-network-config.patch
    + debian/patches/openstack-no-network-config.patch
    + debian/patches/renderer-do-not-prefer-netplan.patch
-
- -- Brett Holman <brett.holman@canonical.com>  Thu, 20 Jan 2022 15:09:42 -0700
-
-cloud-init (21.4-39-ge9634266-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
-
-  * refresh patches:
-   + debian/patches/ec2-dont-apply-full-imds-network-config.patch
-   + debian/patches/openstack-no-network-config.patch
   * New upstream snapshot. (LP: #SRU_BUG_NUMBER_HERE)
+    - cc_rsyslog: fix typo in docstring (#1207) [Louis Sautier]
+    - Update .github-cla-signers (#1204) [Chris Lalos]
+    - sources/azure: drop unused case in _report_failure() (#1200)
+      [Chris Patterson]
+    - sources/azure: always initialize _ephemeral_dhcp_ctx on unpickle (#1199)
+      [Chris Patterson]
+    - Add support for gentoo templates and cloud.cfg (#1179) [vteratipally]
+    - sources/azure: unpack ret tuple in crawl_metadata() (#1194)
+      [Chris Patterson]
+    - tests: focal caplog has whitespace indentation for multi-line logs
+      (#1201)
+    - Seek interfaces, skip dummy interface, fix region codes (#1192) [eb3095]
+    - integration: test against the Ubuntu daily images (#1198)
+      [Paride Legovini]
+    - cmd: status and cloud-id avoid change in behavior for 'not run' (#1197)
+    - tox: pass PYCLOUDLIB_* env vars into integration tests when present
+      (#1196)
+    - sources/azure: set ovf_is_accessible when OVF is read successfully
+      (#1193) [Chris Patterson]
+    - Enable OVF environment transport via ISO in example (#1195) [Megian]
+    - sources/azure: consolidate DHCP variants to EphemeralDHCPv4WithReporting
+      (#1190) [Chris Patterson]
+    - Single JSON schema validation in early boot (#1175)
+    - Add DatasourceOVF network-config propery to Ubuntu OVF example (#1184)
+      [Megian]
+    - testing: support pycloudlib config file (#1189)
+    - Ensure system_cfg read before ds net config on Oracle (SC-720) (#1174)
+    - Test Optimization Proposal (SC-736) (#1188) [Brett Holman]
+    - cli: cloud-id report not-run or disabled state as cloud-id (#1162)
+    - Remove distutils usage (#1177) [Shreenidhi Shedi]
+    - add .python-version to gitignore (#1186) [Brett Holman]
+    - print error if datasource import fails (#1170)
+      [Emanuele Giuseppe Esposito]
+    - Add new config module to set keyboard layout (#1176) [maxnet]
+    - sources/azure: rename metadata_type -> MetadataType (#1181)
+      [Chris Patterson]
+    - Remove 3.5 and xenial support (SC-711) (#1167)
+    - tests: mock LXD datasource detection in ds-identify on LXD containers
+      (#1178)
+    - pylint: silence errors on compat code for old jsonschema (#1172)
+      [Paride Legovini]
+    - testing: Add 3.10 Test Coverage (#1173) [Brett Holman]
+    - Remove unittests from integration test job in travis (#1141)
+      [Brett Holman]
+    - Don't throw exceptions for empty cloud config (#1130) [Brett Holman]
+    - bsd/resolv.d/ avoid duplicated entries (#1163) [Gonéri Le Bouder]
+    - sources/azure: do not persist failed_desired_api_version flag (#1159)
+      [Chris Patterson]
+    - Update cc_ubuntu_advantage calls to assume-yes (#1158) [John Chittum]
+    - openbsd: properly restart the network on 7.0 (#1150) [Gonéri Le Bouder]
+    - Add .git-blame-ignore-revs (#1161)
+    - Adopt Black and isort (SC-700) (#1157)
+    - Include dpkg frontend lock in APT_LOCK_FILES (#1153)
+    - tests/cmd/query: fix test run as root and add coverage for defaults
+      (#1156) [Chris Patterson]
+    - Schema processing changes (SC-676) (#1144)
+    - Add dependency workaround for impish in bddeb (#1148) [Brett Holman]
+    - netbsd: install new dep packages (#1151) [Gonéri Le Bouder]
+    - find_devs_with_openbsd: ensure we return the last entry (#1149)
+      [Gonéri Le Bouder]
     - sources/azure: remove unnecessary hostname bounce (#1143)
       [Chris Patterson]
     - find_devs/openbsd: accept ISO on disk (#1132) [Gonéri Le Bouder]
@@ -62,7 +114,7 @@ cloud-init (21.4-39-ge9634266-0ubuntu1~18.04.1) UNRELEASED; urgency=medium
     - testing: stop chef test from running on openstack (#1102)
     - alpine.py: add options to the apk upgrade command (#1089) [dermotbradley]
 
- -- James Falcon <james.falcon@canonical.com>  Mon, 13 Dec 2021 18:46:17 -0600
+ -- Brett Holman <brett.holman@canonical.com>  Thu, 20 Jan 2022 15:09:42 -0700
 
 cloud-init (21.4-0ubuntu1~18.04.1) bionic; urgency=medium
 
```

I can validate that `quilt push -a; quilt pop -a` both work on the new branch, and I can `build-package; sbuild .... ../out/cloud-init*.dsc without problems. This will result in a working build recipe.

**Review by blackboxsw — CHANGES_REQUESTED** [review]
Looks like in the manual quilt patch creation we mangled test_openstack.py a bit and patched the wrong unit test `test_network_config_disabled_from_network_json` instead of `test_network_config_from_network_jsoon`. This results in unittest failures when either during package build or when running `quilt push -a; tox -e py3 tests/unittests/sources/test_openstack.py`




I think we can apply the following diff and squash it into your commit 63c85f672b2f0ebf0ea81254b79f6110ac251b4f:

```diff
diff --git a/debian/patches/openstack-no-network-config.patch b/debian/patches/openstack-no-network-config.patch
index fadc5a9d..5ce89a4a 100644
--- a/debian/patches/openstack-no-network-config.patch
+++ b/debian/patches/openstack-no-network-config.patch
@@ -31,12 +31,19 @@ Author: Chad Smith <chad.smith@canonical.com>
          if self.network_json == sources.UNSET:
 --- a/tests/unittests/sources/test_openstack.py
 +++ b/tests/unittests/sources/test_openstack.py
-@@ -371,7 +371,7 @@ class TestOpenStackDataSource(test_helpe
+@@ -371,7 +371,6 @@ class TestOpenStackDataSource(test_helpers.HttprettyTestCase):
          ds_os = ds.DataSourceOpenStack(
              settings.CFG_BUILTIN, None, helpers.Paths({"run_dir": self.tmp})
          )
 -        ds_os.ds_cfg = {"apply_network_config": False}
-+        ds_os.ds_cfg = {"apply_network_config": True}  # Default is False
          sample_json = {
              "links": [{"ethernet_mac_address": "mymac"}],
              "networks": [],
+@@ -395,6 +394,7 @@ class TestOpenStackDataSource(test_helpers.HttprettyTestCase):
+             "services": [],
+         }
+         ds_os.network_json = sample_json
++        ds_os.ds_cfg = {"apply_network_config": True}  # Default is False
+         with test_helpers.mock.patch(mock_path) as m_convert_json:
+             m_convert_json.return_value = example_cfg
+             self.assertEqual(example_cfg, ds_os.network_config)
```

**Review by blackboxsw — APPROVED** [review]
- [x] `quilt push -a; tox -re py3; quilt pop -a` SUCCESS
- [x] `build-package; sbuild --resolve-alternatives ../out/cloud-init*dsc` build SUCCESS and no new  lintian errors now.

**Pull request merged**
