### PR TITLE
Update cloud-config-user-groups.txt

### PR DESCRIPTION
**Pull request by scorpion44**
Added " " around the crypted password or it will not apply.

## Proposed Commit Message

```
Added " " around the crypted password or it will not apply.
```

## Checklist:

 - [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [x] I have updated or added any unit tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by scorpion44** [comment]
passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/

has to be changed to 

  passwd: "$6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/"

Or it will not work.

**Review by aciba90 — APPROVED** [review]
Thanks, @scorpion44, for making `cloud-init` better!

**Comment by aciba90** [comment]
Could you please sign the CLA and add yourself to [tools/.github-cla-signers](https://github.com/canonical/cloud-init/blob/main/tools/.github-cla-signers) ?

More info: https://cloudinit.readthedocs.io/en/latest/topics/contributing.html#summary

**Comment by scorpion44** [comment]
> 

Cheers, have done this now.

**Comment by aciba90** [comment]
CLA PR: https://github.com/canonical/cloud-init/pull/1588

**Comment by holmanb** [comment]
> Added " " around the crypted password or it will not apply.

Really? Why is that? Can you share a log (`/var/log/cloud-init.log`) showing the issue please?

I just tested this locally and couldn't reproduce the issue.

running:
```bash
root@me:~# cloud-init query userdata
```
I see the following config:
```yaml
#cloud-config
users:
  - default
  - name: foobar
    gecos: Foo B. Bar
    primary_group: foobar
    groups: users
    expiredate: '2032-09-01'
    ssh_import_id:
      - lp:falcojr
      - gh:TheRealFalcon
    lock_passwd: false
    passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/
  - name: barfoo
    gecos: Bar B. Foo
    sudo: ALL=(ALL) NOPASSWD:ALL
```

additionally I see:
```bash
root@me:~# grep foobar /etc/shadow
foobar:$6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/:19186:0:99999:7::22889:
root@me:~# grep -i -e WARN -e ERROR -e stack /var/log/cloud-init.log
root@me:~# exit
logout
```

Note that I did have to remove the selinux_user key from the config to run on locally on Ubuntu, since selinux is not built into Ubuntu kernels.

**Comment by scorpion44** [comment]
>  I just tested this locally and couldn't reproduce the issue.
holmanb: You are correct.  I went back and removed the quotes as was able to boot up a VM and have it create the user correctly.

I was able to find a hdd img file from the time period with the error still occurring.  It seems that I did not have a space in the -name part under  - default.  I must have fixed this and added the quotes at the same time.

E.G.

 - default
  -name: foobar


Many aplologies.

**Comment by holmanb** [comment]
> Many aplologies.

@scorpion44 All good, no problem :)

**Pull request closed without merging**
