### PR TITLE
Gracefully handle missing userdata files during cloud-init query operations

### LINKED ISSUE #5396: cloud-init query produces no output with missing userdata files
# Bug report
When running any of the `cloud-init query` commands (example `cloud-init query -l`) as the root user, there is no output when the files specified by `user_data_fn` or `vendor_data_fn` do not exist:
https://github.com/canonical/cloud-init/blob/bbc72bfed03584317353c7ccf2b40fd3afd3dea8/cloudinit/cmd/query.py#L215C1-L216C68

When running as a non-root user, `cloud-init query -l` produces output as expected.

When `uid == 0` (the else case), the call to `load_userdata()` calls `load_binary_file()` which raises a `FileNotFoundError` when these files do not exist:
https://github.com/canonical/cloud-init/blob/bbc72bfed03584317353c7ccf2b40fd3afd3dea8/cloudinit/util.py#L1589C1-L1595C22

Since this error is raised when `user_data_fn` does not exist, the remainder of the instance_data is not loaded, thus an empty data structure is returned.

To resolve this, the call to `load_binary_file()` should include the `quiet=True` option so that an exception is not raised when a file does not exist. This would allow the execution to continue and load the remaining data.

## Steps to reproduce the problem
Create a node using the `ConfigDrive` provider, ensure the files `/var/lib/cloud/instance/user-data.txt` and `/var/lib/cloud/instance/vendor-data.txt` do not exist.

Run `cloud-init query -l` as the root user, there will be no output.

Run `cloud-init query -l` as a non-root user, data will be present as expected.

## Environment details
- Cloud-init version: 23.4-7.el9_4.0.1
- Operating System Distribution: Rocky 9
- Cloud provider, platform or installer type: OpenStack Caracal 2024.1

## cloud-init logs
Running as root:
```
[root@testnode tmp]# cloud-init query -l
[root@testnode tmp]#
```
Running as non-root:
```
[rocky@testnode ~]$ cloud-init query -l
_beta_keys
availability-zone
availability_zone
base64_encoded_keys
cloud-name
cloud_id
cloud_name
combined_cloud_config
distro
distro_release
distro_version
ds
instance-id
instance_id
kernel_release
local-hostname
local_hostname
machine
merged_cfg
merged_system_cfg
platform
public_ssh_keys
python_version
region
sensitive_keys
subplatform
sys_info
system_platform
userdata
v1
variant
vendordata
[rocky@testnode ~]$
```

### PR DESCRIPTION
**Pull request by jcmoore3**
Do not raise an error when userdata files are missing during cloud-init query operations

Fixes #5396

## Proposed Commit Message

```
Gracefully handle missing files

Do not raise an error when userdata files are missing

Fixes: GH-5396
```

## Checklist

- [X] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/development/index.html)
- [ ] I have updated or added any [unit tests](https://cloudinit.readthedocs.io/en/latest/development/testing.html) accordingly
- [ ] I have updated or added any [documentation](https://cloudinit.readthedocs.io/en/latest/development/contribute_docs.html) accordingly

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Changes look good to me. Just waiting on the CLA.

**Comment by jcmoore3** [comment]
Apologies that the CLA is taking so long. This needs to go through my company's internal open source approval process. I do not anticipate any issues, it just takes time. I'm hoping to have final internal approval this week.

**Comment by jcmoore3** [comment]
@TheRealFalcon - CLA signed, please let me know if anything else is required to get this moving. Change to github-cla-signers is in PR #5369.

**Review by TheRealFalcon — APPROVED** [review]
Thanks!

**Pull request merged**
