### PR TITLE
add OpenCloudOS and TencentOS support

### PR DESCRIPTION
**Pull request by wynnfeng**
Proposed Commit Message
add OpenCloudOS and TencentOS support

Checklist:

- [x] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
- [x] I have updated or added any unit tests accordingly
- [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by igalic — COMMENTED** [review]
are ntp and yum_add_repo the only modules that need to be adapted?

**Comment by wynnfeng** [comment]
> are ntp and yum_add_repo the only modules that need to be adapted?

I added some other changes just now

**Review by holmanb — COMMENTED** [review]
Hi and welcome @wynnfeng! Can you please start by [signing the CLA, then adding your username to `tools/.github-cla-signers`](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request)?

In addition to that, if you have cloud-init logs of OpenCloudOS and TencentOS that you could attach to this initial submission, that would be much appreciated.

**Comment by wynnfeng** [comment]
> Hi and welcome @wynnfeng! Can you please start by [signing the CLA, then adding your username to `tools/.github-cla-signers`](https://cloudinit.readthedocs.io/en/latest/development/contributing.html#submitting-your-first-pull-request)?
> 
> In addition to that, if you have cloud-init logs of OpenCloudOS and TencentOS that you could attach to this initial submission, that would be much appreciated.

Thank you! I finish signing CLA，and cloud-init logs on OpenCloudOS and TencentOS will be attached after Spring Festival

**Comment by holmanb** [comment]
- [x] verified CLA signature

Thanks, enjoy the holiday! We'll keep an eye out for the logs after the Spring Festival.

**Comment by wynnfeng** [comment]
> * [x]  verified CLA signature
> 
> Thanks, enjoy the holiday! We'll keep an eye out for the logs after the Spring Festival.

[OpencloudOS-cloud-init.log](https://github.com/canonical/cloud-init/files/10533075/OpencloudOS-cloud-init.log)
[TencentOS-cloud-init.log](https://github.com/canonical/cloud-init/files/10533076/TencentOS-cloud-init.log)
Thanks,I've uploaded cloud-init logs on OpenCloudOS and TencentOS

**Review by holmanb — CHANGES_REQUESTED** [review]
I left a couple of minor changes to make, but otherwise that looks mostly good.

Additionally, there are a couple of peculiar things I noticed in the logs you shared that I'd like to ask about.

1. I see a warning log that I can't correlate to the source anywhere:
```
DataSourceConfigDrive.py[WARNING]: Exception Occur when append network_data: 'resolv_conf'
```
Is this running on a different version of cloud-init source than was submitted in this PR?

2. The logs appear to be using the rhel distro class:
```
stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>
```

I realize that current distro implementation don't customize the RHEL distro outside of the `osfamily`, so this _should_ be fine, however it would make more sense to include logs from the distro being added, I think. This can be set in `/etc/cloud/cloud.cfg`, note the `distro` key under `system_info`.

**Comment by holmanb** [comment]
Any updates on this @wynnfeng?

**Comment by wynnfeng** [comment]
> Any updates on this @wynnfeng?

yes,I updates the codes, sorry I've been delayed for a few days because of something,and I've just installed the cloud-init-22.4 which I modifed on OpenCloudOS and TencentOS,so I re-upload the cloud-init logs on OpenCloudOS and TencentOS,also the cloud.cfg
but it still has `DataSourceConfigDrive.py[WARNING]: Exception Occur when append network_data: 'resolv_conf'` even though I install the cloud-init-22.4
[OpenCloudOS-cloud-init.log](https://github.com/canonical/cloud-init/files/10763430/OpenCloudOS-cloud-init.log)
[OpenCloudOS-cloud-cfg.txt](https://github.com/canonical/cloud-init/files/10763434/OpenCloudOS-cloud-cfg.txt)
[TencentOS-cloud-init.log](https://github.com/canonical/cloud-init/files/10763436/TencentOS-cloud-init.log)
[TencentOS-cloud-cfg.txt](https://github.com/canonical/cloud-init/files/10763437/TencentOS-cloud-cfg.txt)

**Comment by holmanb** [comment]
I see that you included the changes from the recent conflict, but since this branch is still based on an old commit we still get a merge conflict.

I just resolved the issue.

**Review by holmanb — APPROVED** [review]
LGTM, thanks!

**Comment by wynnfeng** [comment]
> I see that you included the changes from the recent conflict, but since this branch is still based on an old commit we still get a merge conflict.
> 
> I just resolved the issue.

Thank you! great!

**Comment by cospotato** [comment]
The modify in `cloudinit/net/sysconfig.py` has a mistake:
the variant should be `tencentos` and `opencloudos`
CleanShot 2025-04-25 at 17 34 59@2x

 @wynnfeng

**Pull request merged**
