### PR TITLE
docs: Remove mention of resolv.conf

### PR DESCRIPTION
**Pull request by TheRealFalcon**
## Proposed Commit Message

```
docs: Remove mention of resolv.conf

Use of resolv.conf is renderer-specific.
Not every renderer uses it.
```

## Merge type

- [x] Squash merge using "Proposed Commit Message"
- [ ] Rebase and merge unique commits. Requires commit messages per-commit each referencing the pull request number (#<PR_NUM>)

### CODE REVIEW

**Comment by a-dubs** [comment]
looks good!

**Review by a-dubs — APPROVED** [review]
Looks good!

**Review by holmanb — APPROVED** [review]
Approved once tests pass. Thanks!

**Comment by TheRealFalcon** [comment]
Hrm...weird. They're passing locally for me.

**Pull request merged**
