### PR TITLE
Prefer shorter NIC names when sorting.

### PR DESCRIPTION
**Pull request by garloff**
When cloud-init guesses the first NIC to bring it up and retrieve
network meta-data, it used alphabetic sorting (corrected for numbers to
ensure that 10 is larger than 9).
On some clouds, secondary and later NICs are attached to a secondary
PCI bus (behind a PCI brige) -- on Ubuntu, we'll then see ensX for the
first NIC and enpYsZ for secondary NICs. Unfortunately enp < ens, so the
sorting did not yield the wanted result.

This approach simplifies the sorting. We first sort by length of the NIC
name (shorter names come first) and then alphabetically.
So: ens3 < ens9 < eth0 < eth8 < ens10 < eth10 < enp4s4 < enp4s9 < enp5s2
No guarantee to always guess correctly this way, but better.
The priority on length maintains then correct handling of numbers (9<10).

Signed-off-by: Kurt Garloff <scs@garloff.de>

### CODE REVIEW

**Comment by garloff** [comment]
There is a failing unittest, which trips on the changed ordering.
I could patch as well of course. But before I do, let's have a discussion whether or not the new order is indeed better.

**Comment by garloff** [comment]
I'm open to a discussion how to best proceed, here.
For me, it's clear that ens3 should be sorted prior to enp4s4, which currently is not the case.
(A NIC attached to the primary PCI bus is before NICs behind a PCI bridge -- this is how qemu does it.)
There are several ways to achieve it:
1. I chose a very simplistic approach by preferring short names. This also removes the need for splitting letters from numbers to ensure ens9 < ens10. However, enp0s9 < enp1s9 < enp0s10 which is a change to prior behavior.
2. We could count letters and prefer shorter letter counts and then proceed as before.
3. We could reverse the letter sorting, i.e. eth0 < ens0 < enp0 (< ib0). It is a coincidence that this matches what is normally wanted, but it would probably work.
4. We could sort by numbers first, letters second ... so enp4s5 would be sorted (5,s,4,enp).

We need to be clear that this is and remains a heuristic that can fail. This patch is about reducing the chance for it to fail. (Prior to cloud-init chosing the interface it was the job of the image builder to ensure the right NIC is up for getting the network meta_data, but now we have that responsibility.)

To make this foolproof, we'd need to allow overriding the order (e.g. by allowing to specify regexps in the wanted order.
first_nic: ens3, eth[0-9]*, ens[0-9], enp[0-9]*s[0-9]*
which cloud-init would then use as the primary key for sorting (ens3 match -> 0, eth[0-9]* match -> 1, .... no match -> 9999).
We'd still need the heuristic to avoid this parameter being always required (which is a compat issue) or becoming overly tedious to specify.

**Comment by smoser** [comment]
> I'm open to a discussion how to best proceed, here.
> For me, it's clear that ens3 should be sorted prior to enp4s4, which currently is not the case.
> (A NIC attached to the primary PCI bus is before NICs behind a PCI bridge -- this is how qemu does it.)
> There are several ways to achieve it:
> 
>     1. I chose a very simplistic approach by preferring short names. This also removes the need for splitting letters from numbers to ensure ens9 < ens10. However, enp0s9 < enp1s9 < enp0s10 which is a change to prior behavior.
> 
>     2. We could count letters and prefer shorter letter counts and then proceed as before.
> 
>     3. We could reverse the letter sorting, i.e. eth0 < ens0 < enp0 (< ib0). It is a coincidence that this matches what is normally wanted, but it would probably work.
> 
>     4. We could sort by numbers first, letters second and start from the back ... so enp4s5 would be sorted (5,s,4,enp).
> 
> 
> We need to be clear that this is and remains a heuristic that can fail. This patch is about reducing the chance for it to fail. (Prior to cloud-init chosing the interface it was the job of the image builder to ensure the right NIC is up for getting the network meta_data, but now we have that responsibility.)

The really sucky thing about heuristic is that the change here will potentially break some people.  Its by no means obvious that 'ens3' is more likely the "first nic" than eth0 or ensp4s9.  And we have no data that says so.

So I am *really* hesitant to suggest we should patch this one way.  That would potentially  some users in order to enable otheres.

> 
> To make this foolproof, we'd need to allow overriding the order (e.g. by allowing to specify regexps in the wanted order.

The right way to make it fullproof is really to make it cloud (datasource) specific.  Once cloud-init knows that it is running on a given provider, then it can absolutely use different heuristic for that provider.  Even better, the provider could give the MAC of the nic that should be used in some non-network-dependent source.  Last, if we *know* that we're on 'cloudX', then I'm even OK in principal to try to dhcp on all NICs and use the first one that returns an answer.  That'd take some implementation work, but I'm not opposed in principal.

**Comment by raharper** [comment]
> When cloud-init guesses the first NIC to bring it up and retrieve
network meta-data

Interesting, is this an OpenStack cloud where there _is_ a network-facing metadata service which would include network configuration for the end point? 

If it is, then I would suggest that instead of picking just *one* interface that our EphemeralDHCP should attempt to bring up *all* viable interfaces and attempt to fetch IMDS data.  Some thought needs to go into how this is done to prevent slowdown on the fast path but that feels more like a solution than a different guess.

**Comment by garloff** [comment]
Scott,
thanks for your fast response!

> The really sucky thing about heuristic is that the change here will potentially break some people. Its by no means obvious that 'ens3' is more likely the "first nic" than eth0 or ensp4s9. And we have no data that says so.

I dare to disagree. It's certainly possible to some manually start qemu such that the first NIC is behind a PCI bridge (-> name enpXsY) and later on add one to the primary PCI bus (-> name ensZ). But this is not happening on any cloud I've seen. Many clouds have them all on the primary PCI bus, some on the secondary and some start with one or two on the primary and add the rest to the secondary bus (behind a PCI bridge).
So while we have no guarantee, this is not happening in real life AFACIT.

But I agree that a heuristics is never perfect.
And as you need to fix many bugs to compensate for a regression I do agree that carefulness here is needed.

> So I am _really_ hesitant to suggest we should patch this one way. That would potentially some users in order to enable otheres.
> 
> > To make this foolproof, we'd need to allow overriding the order (e.g. by allowing to specify regexps in the wanted order.
> 
> The right way to make it fullproof is really to make it cloud (datasource) specific. Once cloud-init knows that it is running on a given provider, then it can absolutely use different heuristic for that provider. 

Well, there's two points where knowledge can be injected.
1. cloud-init could indeed have complete knowledge of all relevant clouds. I'm not sure how realisitic this is. Using your wording datasource specific, this might suggest that you define own datasource types for clouds that are the same except for some details how they set up kvm/qemu ... Consider that the PCI topology might differ by flavor (and maybe even by region). This looks like a proliferation of 99% identical datasources ... Not my desrired scenario.

So I indeed prefer the second way:

> Even better, the provider could give the MAC of the nic that should be used in some non-network-dependent source.

Yes! Give the cloud provider a good way to communicate what the NIC for network metadata retrieval is. Easy if the cloud provider uses a cloud specific image (just have a way to specify it in the config file). More difficult otherwise ... Where to put it? Some custom DMI field?

> Last, if we _know_ that we're on 'cloudX', then I'm even OK in principal to try to dhcp on all NICs and use the first one that returns an answer. That'd take some implementation work, but I'm not opposed in principal.

Cloud detection by DMI codes is already done in a few cases, so it's at least an option that would not go into completely unchartered territory.

**Comment by garloff** [comment]
> > When cloud-init guesses the first NIC to bring it up and retrieve
> > network meta-data
> 
> Interesting, is this an OpenStack cloud where there _is_ a network-facing metadata service which would include network configuration for the end point?

Providing network_data via a network meta-data source would be unreasonable, unless the network config for the first interface (that gets us access to the meta-data) is trivial and would not require the config ...
The cloud I'm dealing with here does (for normal flavors) not do anything fancy with network_data ... and does not provide it. It does indeed use the 169.254.169.254 openstack style network metadata.
 
> If it is, then I would suggest that instead of picking just _one_ interface that our EphemeralDHCP should attempt to bring up _all_ viable interfaces and attempt to fetch IMDS data. Some thought needs to go into how this is done to prevent slowdown on the fast path but that feels more like a solution than a different guess.

This would indeed help. Bring all interfaces up (with trivial dhcp config if no matching config is provided in image) and see which one provides a route to 169.254.169.254 and then do the curling ... The one with a response stays up, the others can be shut down again to avoid changing the (historical) behavior.
Note that some care is needed to avoid restarting systemd-resolved many times in a row which would make us run into the systemd restart limit. (Either increase the limit or be more clever to not restart after each interface ...)

**Comment by raharper** [comment]
> Scott,
> thanks for your fast response!
> 
> > The really sucky thing about heuristic is that the change here will potentially break some people. Its by no means obvious that 'ens3' is more likely the "first nic" than eth0 or ensp4s9. And we have no data that says so.
> 
> I dare to disagree. It's certainly possible to some manually start qemu such that the first NIC is behind a PCI bridge (-> name enpXsY) and later on add one to the primary PCI bus (-> name ensZ). But this is not happening on any cloud I've seen. Many clouds have them all on the primary PCI bus, some on the secondary and some start with one or two on the primary and add the rest to the secondary bus (behind a PCI bridge).
>
> So while we have no guarantee, this is not happening in real life AFACIT.

Cloud-init runs on many virtualization platforms, not all of them are QEMU based.  Ec2 still runs some instances on Xen, or a customized KVM with a different user-space, GCE runs KVM with customized qemu, HyperV, VMWare, etc.  In some cases the location on the PCI bus isn't even the same from boot to boot.  It most definitely _is_ happening today.  These instabilities were a key driver of abstracting 'eth0' and other hard-coding of the "right" interface in images vs. having cloud-init make a better run-time guess.

**Comment by raharper** [comment]
> > > When cloud-init guesses the first NIC to bring it up and retrieve
> > > network meta-data
> > 
> > 
> > Interesting, is this an OpenStack cloud where there _is_ a network-facing metadata service which would include network configuration for the end point?
> 
> Providing network_data via a network meta-data source would be unreasonable, unless the network config for the first interface (that gets us access to the meta-data) is trivial and would not require the config ...

It's definitely not unreasonble and it is already done and supported today.  OpenStack, Ec2, Azure all provide platform specific network-configuration;  cloud-init brings up an ephemeral networking to access the DataSource specific IMDS service, this data is fetched and the network configuration is rendered to the instance prior to the OS networking service layer.

> The cloud I'm dealing with here does (for normal flavors) not do anything fancy with network_data ... and does not provide it. It does indeed use the 169.254.169.254 openstack style network metadata.

OK.  Providing network-config is desirable, but not required.


> 
> > If it is, then I would suggest that instead of picking just _one_ interface that our EphemeralDHCP should attempt to bring up _all_ viable interfaces and attempt to fetch IMDS data. Some thought needs to go into how this is done to prevent slowdown on the fast path but that feels more like a solution than a different guess.
> 
> This would indeed help. Bring all interfaces up (with trivial dhcp config if no matching config is provided in image) and see which one provides a route to 169.254.169.254 and then do the curling ... The one with a response stays up, the others can be shut down again to avoid changing the (historical) behavior.

Yes; this is a slight modification of our existing EphemeralDHCP which takes a single interface (the fallback nic guessed via heuristic.  This could be modified to bring up all interfaces, and as you say, whichever one actually responds to the IMDS url will be used in the 'fallback' network config generated (if the platform does not provide a network-config).

> Note that some care is needed to avoid restarting systemd-resolved many times in a row which would make us run into the systemd restart limit. (Either increase the limit or be more clever to not restart after each interface ...)

This is already generally handled by having a DataSource run at "local" time; cloud-init-local.service runs before networking layer is up (including resolved); renders network config to the instance disk, and then networking comes up and cloud-init.service continues.

What datasource is involved?  It may already be configured to run at local time, if not, it can be done so;   here's a conversion of OpenStack to run at local time:

https://github.com/canonical/cloud-init/commit/cd1de5f47ab6b82f2c6fd61a5f6681f33b3e5705

**Comment by garloff** [comment]
> > > Interesting, is this an OpenStack cloud where there _is_ a network-facing metadata service which would include network configuration for the end point?
> > 
> > 
> > Providing network_data via a network meta-data source would be unreasonable, unless the network config for the first interface (that gets us access to the meta-data) is trivial and would not require the config ...
> 
> It's definitely not unreasonble and it is already done and supported today. OpenStack, Ec2, Azure all provide platform specific network-configuration; cloud-init brings up an ephemeral networking to access the DataSource specific IMDS service, this data is fetched and the network configuration is rendered to the instance prior to the OS networking service layer.

Well, that does not work if you need complex network config to get to network-config on a networked datasource. I would thus advise ConfigDrive for such cases ....
But that's really a side-discussion now.

> > The cloud I'm dealing with here does (for normal flavors) not do anything fancy with network_data ... and does not provide it. It does indeed use the 169.254.169.254 openstack style network metadata.
> 
> OK. Providing network-config is desirable, but not required.
> 
> > > If it is, then I would suggest that instead of picking just _one_ interface that our EphemeralDHCP should attempt to bring up _all_ viable interfaces and attempt to fetch IMDS data. Some thought needs to go into how this is done to prevent slowdown on the fast path but that feels more like a solution than a different guess.
> > 
> > 
> > This would indeed help. Bring all interfaces up (with trivial dhcp config if no matching config is provided in image) and see which one provides a route to 169.254.169.254 and then do the curling ... The one with a response stays up, the others can be shut down again to avoid changing the (historical) behavior.
> 
> Yes; this is a slight modification of our existing EphemeralDHCP which takes a single interface (the fallback nic guessed via heuristic. This could be modified to bring up all interfaces, and as you say, whichever one actually responds to the IMDS url will be used in the 'fallback' network config generated (if the platform does not provide a network-config).
> 
> > Note that some care is needed to avoid restarting systemd-resolved many times in a row which would make us run into the systemd restart limit. (Either increase the limit or be more clever to not restart after each interface ...)
> 
> This is already generally handled by having a DataSource run at "local" time; cloud-init-local.service runs before networking layer is up (including resolved); renders network config to the instance disk, and then networking comes up and cloud-init.service continues.
> 
> What datasource is involved? It may already be configured to run at local time, if not, it can be done so; here's a conversion of OpenStack to run at local time:
> 
> [cd1de5f](https://github.com/canonical/cloud-init/commit/cd1de5f47ab6b82f2c6fd61a5f6681f33b3e5705)

It is OpenStack datasource indeed.
Good to see we don't run into this particular trap.

**Comment by raharper** [comment]
> It is OpenStack datasource indeed.
> Good to see we don't run into this particular trap.

Would you be able to file a bug in launchpad[1] and include 'cloud-init collect-logs' tarball, or a cloud-init.log file?  

1. https://bugs.launchpad.net/cloud-init/+filebug

**Pull request closed without merging**
