### PR TITLE
Ubuntu/devel

### PR DESCRIPTION
**Pull request by TheRealFalcon**
~ran `new-upstream-snapshot --first-sru main`.~

~Is `21.4-0ubuntu1~21.10.1` for the version number? I just went with what the script output, but it seems like in the past we haven't always appended the `~21.10.1` type suffixes.~

ran `new-upstream-snapshot --first-devel-upload`

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Oh wait...was `--first-sru` supposed to apply to impish, and not jammy? Also, is there a reason we don't see the commit hash number like normal?

**Review by blackboxsw — CHANGES_REQUESTED** [review]
We need to make sure debian/chanelog represents 22.04 and jammy

Also on devel release we always include the related LP bug numbers, so we don't want that redacted from debian/changelog entries.
Try reviewing this script change https://github.com/canonical/uss-tableflip/pull/78 to perform `new-upstream-snapshot --first-devel-upload`

**Review by blackboxsw — COMMENTED** [review]
Here's the diff I generated with the related `new-upstream-snapshot --first-devel-upload`

```diff
diff --git a/debian/changelog b/debian/changelog
index 3a87bfa6..5380561d 100644
--- a/debian/changelog
+++ b/debian/changelog
@@ -1,4 +1,4 @@
-cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
+cloud-init (21.4-0ubuntu1~22.04.1) jammy; urgency=medium
 
   * d/upstream/metadata: Change contact to James Falcon
   * d/cloud-init.templates: Add LXD to default datasource_list with
@@ -9,8 +9,8 @@ cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
     + cpick-612e3908-Add-connectivity_url-to-Oracle-s-EphemeralDHCPv4-988
     + cpick-dc227869-Set-Azure-to-apply-networking-config-every-BOOT-1023
     + cpick-9c147e83-Allow-disabling-of-network-activation-SC-307-1048
-  * New upstream release. (LP: #1949521)
-    - Release 21.4 (#1091)
+  * New upstream release.
+    - Release 21.4 (#1091) (LP: #1949405)
     - Azure: fallback nic needs to be reevaluated during reprovisioning
       (#1094) [Anh Vo]
     - azure: pps imds (#1093) [Anh Vo]
@@ -19,11 +19,11 @@ cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
     - Fix unhandled apt_configure case. (#1065) [Brett Holman]
     - Allow libexec for hotplug (#1088)
     - Add necessary mocks to test_ovf unit tests (#1087)
-    - Remove (deprecated) apt-key (#1068) [Brett Holman]
+    - Remove (deprecated) apt-key (#1068) [Brett Holman] (LP: #1836336)
     - distros: Remove a completed "TODO" comment (#1086)
     - cc_ssh.py: Add configuration for controlling ssh-keygen output (#1083)
       [dermotbradley]
-    - Add "install hotplug" module (SC-476) (#1069)
+    - Add "install hotplug" module (SC-476) (#1069) (LP: #1946003)
     - hosts.alpine.tmpl: rearrange the order of short and long hostnames
       (#1084) [dermotbradley]
     - Add max version to docutils
@@ -41,26 +41,27 @@ cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
     - Leave the details of service management to the distro (#1074)
       [Andy Fiddaman]
     - Fix typos in setup.py (#1059) [Christian Clauss]
-    - Update Azure _unpickle (SC-500) (#1067)
+    - Update Azure _unpickle (SC-500) (#1067) (LP: #1946644)
     - cc_ssh.py: fix private key group owner and permissions (#1070)
       [Emanuele Giuseppe Esposito]
     - VMware: read network-config from ISO (#1066) [Thomas Weißschuh]
     - testing: mock sleep in gce unit tests (#1072)
-    - CloudStack: fix data-server DNS resolution (#1004) [Olivier Lemasle]
+    - CloudStack: fix data-server DNS resolution (#1004)
+      [Olivier Lemasle] (LP: #1942232)
     - Fix unit test broken by pyyaml upgrade (#1071)
     - testing: add get_cloud function (SC-461) (#1038)
     - Inhibit sshd-keygen@.service if cloud-init is active (#1028)
       [Ryan Harper]
     - VMWARE: search the deployPkg plugin in multiarch dir (#1061)
-      [xiaofengw-vmware]
-    - Fix set-name/interface DNS bug (#1058) [Andrew Kutz]
+      [xiaofengw-vmware] (LP: #1944946)
+    - Fix set-name/interface DNS bug (#1058) [Andrew Kutz] (LP: #1946493)
     - Use specified tmp location for growpart (#1046) [jshen28]
     - .gitignore: ignore tags file for ctags users (#1057) [Brett Holman]
     - Allow comments in runcmd and report failed commands correctly (#1049)
-      [Brett Holman]
+      [Brett Holman] (LP: #1853146)
     - tox integration: pass the *_proxy, GOOGLE_*, GCP_* env vars (#1050)
       [Paride Legovini]
-    - Allow disabling of network activation (SC-307) (#1048)
+    - Allow disabling of network activation (SC-307) (#1048) (LP: #1938299)
     - renderer: convert relative imports to absolute (#1052) [Paride Legovini]
     - Support ETHx_IP6_GATEWAY, SET_HOSTNAME on OpenNebula (#1045)
       [Vlastimil Holer]
@@ -78,15 +79,16 @@ cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
     - Cleanup Vultr support (#987) [eb3095]
     - docs: update cc_disk_setup for fs to raw disk (#1017)
     - HACKING.rst: change contact info to James Falcon (#1030)
-    - tox: bump the pinned flake8 and pylint version (#1029) [Paride Legovini]
+    - tox: bump the pinned flake8 and pylint version (#1029)
+      [Paride Legovini] (LP: #1944414)
     - Add retries to DataSourceGCE.py when connecting to GCE (#1005)
       [vteratipally]
     - Set Azure to apply networking config every BOOT (#1023)
-    - Add connectivity_url to Oracle's EphemeralDHCPv4 (#988)
+    - Add connectivity_url to Oracle's EphemeralDHCPv4 (#988) (LP: #1939603)
     - docs: fix typo and include sudo for report bugs commands (#1022)
-      [Renan Rodrigo]
+      [Renan Rodrigo] (LP: #1940236)
     - VMware: Fix typo introduced in #947 and add test (#1019) [PengpengSun]
-    - Update IPv6 entries in /etc/hosts (#1021) [Richard Hansen]
+    - Update IPv6 entries in /etc/hosts (#1021) [Richard Hansen] (LP: #1943798)
     - Integration test upgrades for the 21.3-1 SRU (#1001)
     - Add Jille to tools/.github-cla-signers (#1016) [Jille Timmermans]
     - Improve ug_util.py (#1013) [Shreenidhi Shedi]
@@ -105,7 +107,7 @@ cloud-init (21.4-0ubuntu1~21.10.1) impish; urgency=medium
     - Azure: Retry dhcp on timeouts when polling reprovisiondata (#998)
       [aswinrajamannar]
 
- -- James Falcon <james.falcon@canonical.com>  Tue, 02 Nov 2021 15:17:59 -0500
+ -- Chad Smith <chad.smith@canonical.com>  Tue, 02 Nov 2021 15:38:46 -0600
 
 cloud-init (21.3-1-g6803368d-0ubuntu3) impish; urgency=medium
 
```

**Comment by TheRealFalcon** [comment]
Updated with your script change. Thanks for that.

Is the lack of a commit hash because this is the same commit as release? For example, this version is:
`21.4-0ubuntu1~22.04.1)`
whereas previous versions have:
`21.3-1-g6803368d-0ubuntu3`
Why isn't this version: 
`21.4-0-db6084bd-0ubuntu1~22.04.1)` ?

**Comment by blackboxsw** [comment]
Diff looks good (only maintainer/author changes in d/changelog), build-package and sbuild successes. no debian/cherry-picks remain. I've uploaded to jammy. Thanks @TheRealFalcon

**Pull request merged**
