### PR TITLE
[Minor] Remove TYPE from sysconfig for vlans

### PR DESCRIPTION
**Pull request by croessner**
Ths fix addresses: https://bugs.launchpad.net/cloud-init/+bug/1788915

### CODE REVIEW

**Comment by TheRealFalcon** [comment]
Hey @croessner , thanks for this PR!

In order for us to merge this pull request, you need to have signed the Contributor License Agreement (CLA). Please sign the CLA by following our hacking guide at https://cloudinit.readthedocs.io/en/latest/topics/hacking.html . In short, you need to [sign the CLA](https://ubuntu.com/legal/contributors) and add your name to the [CLA signers file](https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers) .

In addition, not all of the unit tests pass after this change. Can you modify them appropriately? You can see the details in the Travis job linked to this PR, but the relevant class is `TestRhelSysConfigRendering` in `tests/unittests/test_net.py`

**Comment by croessner** [comment]
I will look at this next week.

**Comment by TheRealFalcon** [comment]
@croessner Thank you for updating the tests. However, we can't incorporate your change until you sign the CLA and add your name to the CLA signers file. You can find instructions at: https://cloudinit.readthedocs.io/en/latest/topics/hacking.html

**Comment by croessner** [comment]
I already signed the CLA. Seems your systems did not recognize this. I was in conversation with Caitlin Gabe-Jones. Maybe you could ask her, what went wrong 😊

**Comment by TheRealFalcon** [comment]
@croessner The second step of signing the CLA is adding your github username to https://github.com/canonical/cloud-init/blob/master/tools/.github-cla-signers .

**Comment by OddBloke** [comment]
Hi @croessner, thanks for the submission and taking the time to sign the CLA! Unfortunately, it looks like #541 is implementing the same functionality as this PR, but it has done so in a slightly different way (with slightly more functionality). I think that implementation is more complete, so I'm going to close this out.

Apologies, I know it's frustrating when this happens! Please do let me know if you don't think this was the right decision, and if you're interested in reviewing the other PR as someone with Red Hat experience, that would be much appreciated.

**Pull request closed without merging**
