### PR TITLE
Add support for Container-Optimized OS

### PR DESCRIPTION
**Pull request by vteratipally**
Signed-off-by: varsha teratipally <teratipally@google.com>

## Proposed Commit Message
Add support for Container-Optimized OS

## Test Steps
Installed cloud-init on an instance, tested manually. 

## Checklist:

 - [X] My code follows the process laid out in [the documentation](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html)
 - [X] I have updated or added any unit tests accordingly
 - [X] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by holmanb** [comment]
Hi @vteratipally, thanks for the PR!

A passing comment: I don't know if you've seen this, but just for context there was [some discussion](https://github.com/canonical/cloud-init/pull/1238) related to adding support for COS, but it was dropped at that time due to broken behavior observed in the downstream images while testing. I think we'll want to make sure the concerns raised in that PR are addressed in this submission.

**Comment by vteratipally** [comment]
> Hi @vteratipally, thanks for the PR!
> 
> A passing comment: I don't know if you've seen this, but just for context there was [some discussion](https://github.com/canonical/cloud-init/pull/1238) related to adding support for COS, but it was dropped at that time due to broken behavior observed in the downstream images while testing. I think we'll want to make sure the concerns raised in that PR are addressed in this submission.

Yes, I have tested whether all the modules are working or not. The modules that don't work are cc_chef,cc-growpart,cc_install_hotplug,cc_locale,cc_mcollective,cc_migrator,cc_package_update_upgrade,cc_phone_home,cc_power_state_change,cc_puppet,cc_refresh_rmc_and_interface,cc_reset_rmc

**Comment by holmanb** [comment]
> Yes, I have tested whether all the modules are working or not. The modules that don't work are ...

Thanks for the response.

How can we test this on an image? The test steps say "Installed cloud-init on an instance, tested manually.", but without a package manager how does one install cloud-init on an instance? I checked the docs, but after reading the "concepts" pages and the "build from open source" page, I still don't know how to test this.

**Comment by vteratipally** [comment]
> > Yes, I have tested whether all the modules are working or not. The modules that don't work are ...
> 
> Thanks for the response.
> 
> How can we test this on an image? The test steps say "Installed cloud-init on an instance, tested manually.", but without a package manager how does one install cloud-init on an instance? I checked the docs, but after reading the "concepts" pages and the "build from open source" page, I still don't know how to test this.

COS uses gentoo package system. COS is based on chromium os build system where we install the package using `emerge cloud-init`. The ebuild for cloud-init is here https://cos.googlesource.com/cos/overlays/board-overlays/+/refs/heads/master/project-lakitu/app-emulation/cloud-init/

**Comment by holmanb** [comment]
Thanks for the background @vteratipally. Since we can't install this on a live image, is there some other way we can test this code on an image?

**Comment by vteratipally** [comment]
> Thanks for the background @vteratipally. Since we can't install this on a live image, is there some other way we can test this code on an image?

I think we can test it on ubuntu image, as in COS(with distro: cos in system_info), we were using the ubuntu version of the cloud-init rather than the gentoo version.

**Comment by holmanb** [comment]
> I think we can test it on ubuntu image, as in COS(with distro: cos in system_info), we were using the ubuntu version of the cloud-init rather than the gentoo version.

No problem, I'll poke around and see if I can make that work. 

Do you have sample logs (`/var/log/cloud-init.log` and `/var/log/cloud-init-output.log`) from a booted COS? If so, that would help with review.

**Comment by vteratipally** [comment]
> > I think we can test it on ubuntu image, as in COS(with distro: cos in system_info), we were using the ubuntu version of the cloud-init rather than the gentoo version.
> 
> No problem, I'll poke around and see if I can make that work.
> 
> Do you have sample logs (`/var/log/cloud-init.log` and `/var/log/cloud-init-output.log`) fro
[cloud-init.log](https://github.com/canonical/cloud-init/files/9709497/cloud-init.log)
[cloud-init-output.log](https://github.com/canonical/cloud-init/files/9709498/cloud-init-output.log)
m a booted COS? If so, that would help with review.

sure, here it is 
[cloud-init.log](https://github.com/canonical/cloud-init/files/9709500/cloud-init.log)
[cloud-init-output.log](https://github.com/canonical/cloud-init/files/9709502/cloud-init-output.log)

**Review by holmanb — APPROVED** [review]
Thanks for the contribution!

**Review by TheRealFalcon — APPROVED** [review]

**Pull request merged**
